### ISSUE TITLE
Cannot build music data set?

### ISSUE THREAD

**Issue by RuchirB** [tensorflow/magenta#1003]
I am trying to build my data set from a collection of midi files. To do so, I ran the following:

`python ./convert_dir_to_note_sequences.py --/Users/ruchirbaronia/Desktop/allMidis `

However got the following error:

```
Traceback (most recent call last):
  File "./convert_dir_to_note_sequences.py", line 31, in <module>
    import tensorflow as tf
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 52, in <module>
    from tensorflow.core.framework.graph_pb2 import *
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/core/framework/graph_pb2.py", line 10, in <module>
    from google.protobuf import descriptor_pb2
  File "/anaconda3/lib/python3.6/site-packages/google/protobuf/descriptor_pb2.py", line 735, in <module>
    options=None, file=DESCRIPTOR),
  File "/anaconda3/lib/python3.6/site-packages/google/protobuf/descriptor.py", line 501, in __new__
    return _message.default_pool.FindFieldByName(full_name)
KeyError: "Couldn't find field google.protobuf.EnumDescriptorProto.EnumReservedRange.start"
```

https://github.com/tensorflow/magenta/tree/master/magenta/scripts
is the script that I saved with the extension of `.py` to prepare my data. Let me know on any suggestions.

**Comment by cghawthorne** [comment]
@RuchirB, because of the way our protobuf code is generated, you can't run the python files directly from the repo. You'll need to either install our pip package or use our development environment: https://github.com/tensorflow/magenta#development-environment
