### ISSUE TITLE
 Assign requires shapes of both tensors to match. lhs shape= [38] rhs shape= [40]

### ISSUE THREAD

**Issue by RuchirB** [tensorflow/magenta#1005]
I'm trying to train the model with the `tfrecord` file that I generated using the following command:

`melody_rnn_train --config=basic_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=/Users/ruchirbaronia/Desktop/outputDir/training_melodies.tfrecord --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --num_training_steps=20000
`
However, this gets the error:

(.env) (py27) Ruchirs-MacBook-Pro:magenta ruchirbaronia$ melody_rnn_train --config=basic_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=/Users/ruchirbaronia/Desktop/outputDir/training_melodies.tfrecord --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --num_training_steps=20000 --num_layers=2
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
INFO:tensorflow:hparams = {'batch_size': 64, 'rnn_layer_sizes': [64, 64], 'dropout_keep_prob': 0.5, 'clip_norm': 5, 'learning_rate': 0.001}
INFO:tensorflow:Train dir: /tmp/melody_rnn/logdir/run1/train
INFO:tensorflow:Counting records in /Users/ruchirbaronia/Desktop/outputDir/training_melodies.tfrecord.
INFO:tensorflow:Number of records is at least 100.
INFO:tensorflow:[<tf.Tensor 'random_shuffle_queue_Dequeue:0' shape=(?, 38) dtype=float32>, <tf.Tensor 'random_shuffle_queue_Dequeue:1' shape=(?,) dtype=int64>, <tf.Tensor 'random_shuffle_queue_Dequeue:2' shape=() dtype=int32>]
WARNING:tensorflow:From /anaconda3/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/training.py:412: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
2018-01-06 16:12:50.208273: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
INFO:tensorflow:Restoring parameters from /tmp/melody_rnn/logdir/run1/train/model.ckpt-0
2018-01-06 16:12:50.342712: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias/Adam not found in checkpoint
2018-01-06 16:12:50.345421: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias not found in checkpoint
2018-01-06 16:12:50.347147: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias/Adam_1 not found in checkpoint
2018-01-06 16:12:50.348205: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel not found in checkpoint
2018-01-06 16:12:50.348341: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel/Adam not found in checkpoint
2018-01-06 16:12:50.349313: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel/Adam_1 not found in checkpoint
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64,38] rhs shape= [64,40]
	 [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fully_connected/weights, save/RestoreV2_5)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/melody_rnn_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 109, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 105, in main
    checkpoints_to_keep=FLAGS.num_checkpoints)
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/shared/events_rnn_train.py", line 79, in run_training
    is_chief=task == 0)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/training.py", line 535, in train
    config=config) as session:
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 368, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 673, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 493, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 851, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 856, in _create_session
    return self._sess_creator.create_session()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 554, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 428, in create_session
    init_fn=self._scaffold.init_fn)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 205, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [64,38] rhs shape= [64,40]
	 [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fully_connected/weights, save/RestoreV2_5)]]

Caused by op 'save/Assign_5', defined at:
  File "/anaconda3/bin/melody_rnn_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 109, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 105, in main
    checkpoints_to_keep=FLAGS.num_checkpoints)
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/shared/events_rnn_train.py", line 68, in run_training
    saver=tf.train.Saver(max_to_keep=checkpoints_to_keep))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 439, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [64,38] rhs shape= [64,40]
	 [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fully_connected/weights, save/RestoreV2_5)]]

(.env) (py27) Ruchirs-MacBook-Pro:magenta ruchirbaronia$ melody_rnn_train --config=basic_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=/Users/ruchirbaronia/Desktop/outputDir/training_melodies.tfrecord --num_training_steps=20000
/anaconda3/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)
INFO:tensorflow:hparams = {'batch_size': 128, 'rnn_layer_sizes': [128, 128], 'dropout_keep_prob': 0.5, 'clip_norm': 5, 'learning_rate': 0.001}
INFO:tensorflow:Train dir: /tmp/melody_rnn/logdir/run1/train
INFO:tensorflow:Counting records in /Users/ruchirbaronia/Desktop/outputDir/training_melodies.tfrecord.
INFO:tensorflow:Number of records is at least 100.
INFO:tensorflow:[<tf.Tensor 'random_shuffle_queue_Dequeue:0' shape=(?, 38) dtype=float32>, <tf.Tensor 'random_shuffle_queue_Dequeue:1' shape=(?,) dtype=int64>, <tf.Tensor 'random_shuffle_queue_Dequeue:2' shape=() dtype=int32>]
WARNING:tensorflow:From /anaconda3/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/training.py:412: get_or_create_global_step (from tensorflow.contrib.framework.python.ops.variables) is deprecated and will be removed in a future version.
Instructions for updating:
Please switch to tf.train.get_or_create_global_step
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
2018-01-06 16:13:50.329497: I tensorflow/core/platform/cpu_feature_guard.cc:137] Your CPU supports instructions that this TensorFlow binary was not compiled to use: SSE4.1 SSE4.2 AVX
INFO:tensorflow:Restoring parameters from /tmp/melody_rnn/logdir/run1/train/model.ckpt-0
2018-01-06 16:13:50.468132: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias not found in checkpoint
2018-01-06 16:13:50.468177: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias/Adam not found in checkpoint
2018-01-06 16:13:50.468367: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/bias/Adam_1 not found in checkpoint
2018-01-06 16:13:50.470744: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel not found in checkpoint
2018-01-06 16:13:50.471029: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel/Adam not found in checkpoint
2018-01-06 16:13:50.471097: W tensorflow/core/framework/op_kernel.cc:1192] Not found: Key rnn/multi_rnn_cell/cell_0/basic_lstm_cell/kernel/Adam_1 not found in checkpoint
Traceback (most recent call last):
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1323, in _do_call
    return fn(*args)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1302, in _run_fn
    status, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [38] rhs shape= [40]
	 [[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fully_connected/biases, save/RestoreV2_2)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/anaconda3/bin/melody_rnn_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 109, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 105, in main
    checkpoints_to_keep=FLAGS.num_checkpoints)
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/shared/events_rnn_train.py", line 79, in run_training
    is_chief=task == 0)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/contrib/training/python/training/training.py", line 535, in train
    config=config) as session:
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 368, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 673, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 493, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 851, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 856, in _create_session
    return self._sess_creator.create_session()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 554, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/monitored_session.py", line 428, in create_session
    init_fn=self._scaffold.init_fn)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 273, in prepare_session
    config=config)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/session_manager.py", line 205, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1666, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 889, in run
    run_metadata_ptr)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1120, in _run
    feed_dict_tensor, options, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1317, in _do_run
    options, run_metadata)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/client/session.py", line 1336, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [38] rhs shape= [40]
	 [[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fully_connected/biases, save/RestoreV2_2)]]

Caused by op 'save/Assign_2', defined at:
  File "/anaconda3/bin/melody_rnn_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 109, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 105, in main
    checkpoints_to_keep=FLAGS.num_checkpoints)
  File "/anaconda3/lib/python3.6/site-packages/magenta/models/shared/events_rnn_train.py", line 68, in run_training
    saver=tf.train.Saver(max_to_keep=checkpoints_to_keep))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 439, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/training/saver.py", line 160, in restore
    self.op.get_shape().is_fully_defined())
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/state_ops.py", line 276, in assign
    validate_shape=validate_shape)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/ops/gen_state_ops.py", line 57, in assign
    use_locking=use_locking, name=name)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/anaconda3/lib/python3.6/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [38] rhs shape= [40]
	 [[Node: save/Assign_2 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/device:CPU:0"](fully_connected/biases, save/RestoreV2_2)]]

**Comment by dantuluri** [comment]
From what I'm looking at, you're using Anacoda, if so run
`conda create -n py36 python=3.6 anaconda`
since you're getting a 

> "RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6

error. If this doesn't work try searching for ways to update your version of python because it seems that you have conda 3.6 but for one reason or another you're getting a runtime warning.
In my personal opinion (I don't know your situation) I would just get jupyter notebook and just install 3.6. To start, run
`brew install python3`
and then run
`pip3 install jupyter`
(something like that).
While you're fixing this issue run
`brew doctor`
to find any problems, if you want to.

**Comment by cghawthorne** [comment]
It looks like sometimes when you run the train command you have hparams that specify a size of [64,64] and sometimes there isn't an hparam, so it goes with the default of [128,128]. I suspect there is a checkpoint in your rundir that was created with a graph that is a different size than what you are trying to run now. I would try using a different rundir or deleting the current contents of the rundir and starting again.
