### ISSUE TITLE
Can't open audio with audioread/librosa  on Xubuntu : audioread.NoBackendError

### ISSUE THREAD

**Issue by KyrillosL** [tensorflow/magenta#1061]
Hi, 

I'm trying to run the example that generate audio from Nsynth. 
I run this script :
```
nsynth_generate \
--checkpoint_path=~/IA/magenta/magenta/models/nsynth/wavenet/wavenet-ckpt/model.ckpt-200000 \
--source_path=~/IA/dataset/source \
--save_path=~/IA/dataset/output \
--encodings=true \
--batch_size=4
```

But I get this error : 
```
WARNING:tensorflow:From /home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/masked.py:116: __init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
Traceback (most recent call last):
  File "/home/kyrillos/miniconda2/envs/magenta/bin/nsynth_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 98, in console_entry_point
    tf.app.run(main)
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 85, in main
    batch_data = fastgen.load_batch(batch_files, sample_length=sample_length)
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/fastgen.py", line 135, in load_batch
    data = utils.load_audio(f, sample_length, sr=16000)
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/utils.py", line 65, in load_audio
    audio, _ = librosa.load(path, sr=sr)
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/librosa/core/audio.py", line 112, in load
    with audioread.audio_open(os.path.realpath(path)) as input_file:
  File "/home/kyrillos/miniconda2/envs/magenta/lib/python2.7/site-packages/audioread/__init__.py", line 116, in audio_open
    raise NoBackendError()
audioread.NoBackendError

```

I'm new to linux and I searched on the internet, but none of the solution worked. (I tried to install ffmpeg to my magenta env for example). 

Does anyone know how to fix it ? 

Thank !

**Comment by cghawthorne** [comment]
That seems to be caused by the lack of a backend for audioread. This page has a list of supported backends: https://github.com/beetbox/audioread

I'd try installing one of those and see if that gets it to work.

**Comment by KyrillosL** [comment]
Thank for your response. 
I installed Gstreamer, Ffmpeg and Mad, but it still doesn't work. 
I installed them via conda directly to my magenta env.

**Comment by cghawthorne** [comment]
Could you try installing with apt-get rather than conda?

**Comment by KyrillosL** [comment]
Hi, 
Still no luck with apt-get.

**Comment by cghawthorne** [comment]
Hmm, sorry not sure what the problem is then. I'd suggest asking over on the audioread github project because they'll have a better idea of how to debug this: https://github.com/beetbox/audioread

**Comment by KyrillosL** [comment]
Hi, 

I found the problem. There was a ._loop.wav in my source folder, created by my mac and copied in my Ubuntu computer. 
I just removed it via rm ._loop.wav and everything is OK.
