### ISSUE TITLE
"No session factory registered" with music_vae_train

### ISSUE THREAD

**Issue by tomduncalf** [tensorflow/magenta#1110]
Hi,

I'm a total newcomer to Tensorflow and Magenta, but am really curious to play around with the MusicVAE stuff.

I set up a Magenta environment on MacOS by following the instructions at https://github.com/tensorflow/magenta/blob/master/README.md#manual-install (the automatic script failed for me) and am running from inside the conda session (? not sure if this is the right terminology!)

When I try to run `music_vae_train`, I get the following output:

```
(magenta) ➜  js git:(master) ✗ music_vae_train \
--config=cat-drums_2bar_small \
--run_dir=/tmp/music_vae/ \
--mode=train \
--examples_path=/tmp/notesequences.tfrecord
INFO:tensorflow:Reading examples from: /tmp/notesequences.tfrecord
2018-03-15 19:43:27.508161: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, CategoricalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 256, 'free_bits': 0.0, 'max_seq_len': 32, 'sampling_schedule': 'constant', 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 'batch_size': 512, 'dec_rnn_size': [256, 256], 'decay_rate': 0.9999, 'beta_rate': 0.0, 'sampling_rate': 0.0, 'enc_rnn_size': [512], 'max_beta': 1.0, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [512]

INFO:tensorflow:
Decoder Cells:
  units: [256, 256]

WARNING:tensorflow:From /Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/lstm_models.py:535: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-03-15 19:43:38.138342: E tensorflow/core/common_runtime/session.cc:69] Not found: No session factory registered for the given session options: {target: "local" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
Traceback (most recent call last):
  File "/Users/td/miniconda2/envs/magenta/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 302, in run
    task=FLAGS.task)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 211, in train
    is_chief=is_chief)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py", line 541, in train
    max_wait_secs=max_wait_secs) as session:
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 446, in create_session
    init_fn=self._scaffold.init_fn)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 275, in prepare_session
    config=config)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 180, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1522, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 638, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/Users/td/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: No session factory registered for the given session options: {target: "local" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
(magenta) ➜  js git:(master) ✗
```

Can anyone help?

Thanks!
Tom

**Comment by adarob** [comment]
@tomduncalf  can you try adding the flag `--master=''` and see if it runs?

**Comment by tomduncalf** [comment]
Hi @adarob, thanks for the quick reply! I actually was just about to reply myself saying I found that solution via https://stackoverflow.com/questions/41809130/tensorflow-slim-training-loop-crashing-no-session-factory-registered and it does indeed work :)

Thanks again!
Tom
