### ISSUE TITLE
Problems training MusicVAE on AWS

### ISSUE THREAD

**Issue by cipher813** [tensorflow/magenta#1118]
I am having trouble running music_vae_train on an AWS p2.xlarge instance.  When passing the following directly from the model readme:

`music_vae_train --config=cat-mel_2bar_small --run_dir=/tmp/music_vae/ --mode=train --examples_path=/tmp/notesequences.tfrecord`

I get the following error:

`/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/matplotlib/__init__.py:1057: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/matplotlib/__init__.py:1057: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
INFO:tensorflow:Reading examples from: /tmp/notesequences.tfrecord
2018-03-20 21:09:58.072001: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-03-20 21:09:58.261392: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-20 21:09:58.261775: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-03-20 21:09:58.261809: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-20 21:10:00.061698: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10764 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, CategoricalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 256, 'free_bits': 0.0, 'max_seq_len': 32, 'sampling_schedule': 'constant', 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 'batch_size': 512, 'dec_rnn_size': [256, 256], 'decay_rate': 0.9999, 'beta_rate': 0.0, 'sampling_rate': 0.0, 'enc_rnn_size': [512], 'max_beta': 1.0, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [512]

INFO:tensorflow:
Decoder Cells:
  units: [256, 256]

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/lstm_models.py:535: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-03-20 21:10:13.154010: E tensorflow/core/common_runtime/session.cc:69] Not found: No session factory registered for the given session options: {target: "local" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/magenta/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 302, in run
    task=FLAGS.task)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 211, in train
    is_chief=is_chief)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py", line 541, in train
    max_wait_secs=max_wait_secs) as session:
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 384, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 795, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 518, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 981, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 986, in _create_session
    return self._sess_creator.create_session()
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 675, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 446, in create_session
    init_fn=self._scaffold.init_fn)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 275, in prepare_session
    config=config)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/session_manager.py", line 180, in _restore_checkpoint
    sess = session.Session(self._target, graph=self._graph, config=config)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1522, in __init__
    super(Session, self).__init__(target, graph, config=config)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 638, in __init__
    self._session = tf_session.TF_NewDeprecatedSession(opts, status)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: No session factory registered for the given session options: {target: "local" config: } Registered factories are {DIRECT_SESSION, GRPC_SESSION}.
`
When adding a --master="" I get the following:

`/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/matplotlib/__init__.py:1057: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/matplotlib/__init__.py:1057: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
INFO:tensorflow:Reading examples from: /tmp/notesequences.tfrecord
2018-03-20 21:15:19.489714: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-03-20 21:15:19.587392: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-20 21:15:19.587762: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-03-20 21:15:19.587799: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-20 21:15:19.885465: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10764 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, CategoricalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 256, 'free_bits': 0.0, 'max_seq_len': 32, 'sampling_schedule': 'constant', 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 'batch_size': 512, 'dec_rnn_size': [256, 256], 'decay_rate': 0.9999, 'beta_rate': 0.0, 'sampling_rate': 0.0, 'enc_rnn_size': [512], 'max_beta': 1.0, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [512]

INFO:tensorflow:
Decoder Cells:
  units: [256, 256]

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/lstm_models.py:535: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
2018-03-20 21:15:32.846152: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-20 21:15:32.846364: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 339 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
2018-03-20 21:15:48.419446: W tensorflow/core/framework/op_kernel.cc:1202] OP_REQUIRES failed at iterator_ops.cc:814 : Invalid argument: buffer_size must be greater than zero.
	 [[Node: ShuffleAndRepeatDataset = ShuffleAndRepeatDataset[output_shapes=[[]], output_types=[DT_STRING]](TensorSliceDataset, ShuffleAndRepeatDataset/buffer_size, ShuffleAndRepeatDataset/seed, ShuffleAndRepeatDataset/seed2, ShuffleAndRepeatDataset/count)]]
Traceback (most recent call last):
  File "/home/ubuntu/anaconda3/envs/magenta/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 302, in run
    task=FLAGS.task)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 211, in train
    is_chief=is_chief)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py", line 544, in train
    loss = session.run(train_op)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 546, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1022, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1113, in run
    raise six.reraise(*original_exc_info)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1098, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1170, in run
    run_metadata=run_metadata)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 950, in run
    return self._sess.run(*args, **kwargs)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 905, in run
    run_metadata_ptr)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1137, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1355, in _do_run
    options, run_metadata)
  File "/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1374, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: buffer_size must be greater than zero.
	 [[Node: ShuffleAndRepeatDataset = ShuffleAndRepeatDataset[output_shapes=[[]], output_types=[DT_STRING]](TensorSliceDataset, ShuffleAndRepeatDataset/buffer_size, ShuffleAndRepeatDataset/seed, ShuffleAndRepeatDataset/seed2, ShuffleAndRepeatDataset/count)]]
	 [[Node: OneShotIterator = OneShotIterator[container="", dataset_factory=_make_dataset_5408f458[], output_shapes=[[?,?,90], [?,?,90], [?,?,?], [?]], output_types=[DT_BOOL, DT_BOOL, DT_BOOL, DT_INT32], shared_name="", _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]
	 [[Node: IteratorGetNext/_235 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_5_IteratorGetNext", tensor_type=DT_BOOL, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]
`
and with --master=grpc://<IP>:1111 it hangs at:

`/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/h5py/__init__.py:36: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/matplotlib/__init__.py:1057: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #2
  (fname, cnt))
/home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/matplotlib/__init__.py:1057: UserWarning: Duplicate key in file "/home/ubuntu/.config/matplotlib/matplotlibrc", line #3
  (fname, cnt))
INFO:tensorflow:Reading examples from: /tmp/notesequences.tfrecord
2018-03-20 21:17:47.658643: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-03-20 21:17:47.755925: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-03-20 21:17:47.756284: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1212] Found device 0 with properties: 
name: Tesla K80 major: 3 minor: 7 memoryClockRate(GHz): 0.8235
pciBusID: 0000:00:1e.0
totalMemory: 11.17GiB freeMemory: 11.10GiB
2018-03-20 21:17:47.756317: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1312] Adding visible gpu devices: 0
2018-03-20 21:17:48.053155: I tensorflow/core/common_runtime/gpu/gpu_device.cc:993] Creating TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10764 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:1e.0, compute capability: 3.7)
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, CategoricalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 256, 'free_bits': 0.0, 'max_seq_len': 32, 'sampling_schedule': 'constant', 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 'batch_size': 512, 'dec_rnn_size': [256, 256], 'decay_rate': 0.9999, 'beta_rate': 0.0, 'sampling_rate': 0.0, 'enc_rnn_size': [512], 'max_beta': 1.0, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [512]

INFO:tensorflow:
Decoder Cells:
  units: [256, 256]

WARNING:tensorflow:From /home/ubuntu/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/lstm_models.py:535: softmax_cross_entropy_with_logits (from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See tf.nn.softmax_cross_entropy_with_logits_v2.

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. Error: OS Error
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:An error was raised while a session was being created. This may be due to a preemption of a connected worker or parameter server. A new session will be created. Error: OS Error
INFO:tensorflow:Graph was finalized.
`
With --hparams=batch_size=32,learning_rate=0.0005 i get the same error as above.

I have been able to run the train on my Ubuntu 17.10 desktop without an issue.  

Any guidance would be sincerely appreciated!

**Comment by adarob** [comment]
Sorry for the confusing error message, but this means that it isn't finding
any files that match your input path.

**Comment by cipher813** [comment]
It appears I spoke too soon as setting --master="" actually solved the problem.  I passed specifically:

`music_vae_train --config=cat-mel_2bar_small --run_dir=/tmp/music_vae/ --mode=train --examples_path=/tmp/notesequences.tfrecord --master=""`

And now it appears to train without a hitch.

Thanks!

**Comment by adarob** [comment]
Ah yes. Which version of magenta's pip package do you have installed? That
should have been fixed already.

**Comment by cipher813** [comment]
I'm using 0.3.6 of the magenta and magenta-gpu pip packages, although I believe I had been using this version while I was having the issue earlier.

**Comment by adarob** [comment]
It's fixed in 0.3.7.
