### ISSUE TITLE
MusicVAE: problem with training my own model

### ISSUE THREAD

**Issue by hubertsiuzdak** [tensorflow/magenta#1126]
I am not able to train a model on my own data. 

input:
```
$ music_vae_train 
--config=cat-mel_2bar_small 
--run_dir=~/magenta/music_vae/logdir/ 
--mode=train 
--examples_path=~/magenta/data/notesequences.tfrecord 

```

output:
```
INFO:tensorflow:Reading examples from: ~/magenta/data/notesequences.tfrecord
Traceback (most recent call last):
  File "/usr/local/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 289, in run
    is_training=is_training)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/data.py", line 1164, in get_dataset
    num_files = len(tf.gfile.Glob(examples_path))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/lib/io/file_io.py", line 333, in get_matching_files
    for single_filename in filename
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 473, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: ~/magenta/data; No such file or directory
```
`~/magenta/data/notesequences.tfrecord`  actually exists, it is a NoteSequence protocol buffer and works pretty well with Polyphony RNN.

**Comment by adarob** [comment]
Hi Hubert. Sorry but MusicVAE doesn't currently have automatic path expansion enabled, so you can't use "~" in your path. I'm going to fix it, but for now you can just use the full path.
