### ISSUE TITLE
MusicVAE - Training your own models - Attribute error

### ISSUE THREAD

**Issue by Gnefi** [tensorflow/magenta#1138]
Hi everyone!
I'm new on the project so please don't kill me LOL.
    I followed the guide from your link https://github.com/tensorflow/magenta/tree/master/magenta/models/music_vae but when I start the example command
    music_vae_train \
    --config=cat-mel_2bar_small \
    --run_dir=/tmp/music_vae/ \
    --mode=train \
    --examples_path=/tmp/music_vae/mel_train_examples.tfrecord

    I found an error: this is the report.

    INFO:tensorflow:Reading examples from: notesequence.tfrecord
    Traceback (most recent call last):
    File "/home/generale/anaconda3/envs/magenta/bin/music_vae_train", line 11, in
    sys.exit(console_entry_point())
    File "/home/generale/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 325, in console_entry_point
    tf.app.run(main)
    File "/home/generale/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 124, in run
    _sys.exit(main(argv))
    File "/home/generale/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 321, in main
    run(configs.CONFIG_MAP)
    File "/home/generale/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_train.py", line 290, in run
    is_training=is_training)
    File "/home/generale/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/data.py", line 1174, in get_dataset
    tf.contrib.data.shuffle_and_repeat(buffer_size=num_files))
    AttributeError: 'module' object has no attribute 'shuffle_and_repeat'

    How can I solve? Can you help me please? Thank you.

**Comment by Gnefi** [comment]
I have the most recent version. Is it 1.7.0 right? 
Anyway this is the report.

pip show tensorflow
Name: tensorflow
Version: 1.7.0
Summary: TensorFlow helps the tensors flow
Home-page: https://www.tensorflow.org/
Author: Google Inc.
Author-email: opensource@google.com
License: Apache 2.0
Location: /home/generale/anaconda3/envs/magenta/lib/python2.7/site-packages
Requires: protobuf, astor, backports.weakref, wheel, mock, enum34, gast, termcolor, absl-py, tensorboard, six, grpcio, numpy

**Comment by adarob** [comment]
@Gnefi have you been able to resolve this yet? If not, I can look into it today.
