### ISSUE TITLE
Pianoroll RNN-NADE: No priming pianoroll could be extracted

### ISSUE THREAD

**Issue by HandsomeDevilv112** [tensorflow/magenta#1141]
Following the instructions for rnn-nade, I'm getting an error while trying to generate pianoroll tracks.
I'm using the docker image for tensorflow 1.7.0 with cuda 9 built in.

My training command line is:
pianoroll_rnn_nade_train --run_dir=/tmp/pianoroll_rnn_nade/logdir/run1 --sequence_example_file=/tmp/pianoroll_rnn_nade/sequence_examples/eval_pianoroll_tracks.tfrecord --hparams="batch_size=50,rnn_layer_sizes=[512,512,512,512]" --num_training_steps=20000 

my generation command line and resulting error is:
(magenta) root@2605bf7456ed:~# pianoroll_rnn_nade_generate --run_dir=/tmp/pianoroll_rnn_nade/logdir/run1/ --output_dir=/tmp/pianoroll_rnn_nade/generated --num_outputs=10 --hparams="rnn_layer_sizes=[512,512,512,512]" --num_steps=1280
WARNING:tensorflow:From /root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/learn/python/learn/datasets/base.py:198: retry (from tensorflow.contrib.learn.python.learn.datasets.base) is deprecated and will be removed in a future version.
Instructions for updating:
Use the retry module or similar alternatives.
WARNING:tensorflow:No priming sequence specified. Defaulting to empty sequence.
INFO:tensorflow:primer_sequence: ticks_per_quarter: 220
tempos {
  qpm: 60.0
}

INFO:tensorflow:generator_options: generate_sections {
  end_time: 320.0
}
args {
  key: "beam_size"
  value {
    int_value: 1
  }
}
args {
  key: "branch_factor"
  value {
    int_value: 1
  }
}

INFO:tensorflow:hparams = {'rnn_layer_sizes': [512, 512, 512, 512], 'nade_hidden_units': 128, 'learning_rate': 0.001, 'batch_size': 1, 'clip_norm': 5, 'dropout_keep_prob': 0.5}
2018-04-10 09:00:20.921921: I tensorflow/core/platform/cpu_feature_guard.cc:140] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2018-04-10 09:00:21.017748: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-10 09:00:21.018113: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 0 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.86
pciBusID: 0000:01:00.0
totalMemory: 7.92GiB freeMemory: 7.21GiB
2018-04-10 09:00:21.096454: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:898] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2018-04-10 09:00:21.096813: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1344] Found device 1 with properties: 
name: GeForce GTX 1080 major: 6 minor: 1 memoryClockRate(GHz): 1.86
pciBusID: 0000:02:00.0
totalMemory: 7.92GiB freeMemory: 7.80GiB
2018-04-10 09:00:21.097327: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1423] Adding visible gpu devices: 0, 1
2018-04-10 09:00:21.478549: I tensorflow/core/common_runtime/gpu/gpu_device.cc:911] Device interconnect StreamExecutor with strength 1 edge matrix:
2018-04-10 09:00:21.478583: I tensorflow/core/common_runtime/gpu/gpu_device.cc:917]      0 1 
2018-04-10 09:00:21.478590: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 0:   N Y 
2018-04-10 09:00:21.478596: I tensorflow/core/common_runtime/gpu/gpu_device.cc:930] 1:   Y N 
2018-04-10 09:00:21.478907: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 6960 MB memory) -> physical GPU (device: 0, name: GeForce GTX 1080, pci bus id: 0000:01:00.0, compute capability: 6.1)
2018-04-10 09:00:21.566093: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1041] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:1 with 7538 MB memory) -> physical GPU (device: 1, name: GeForce GTX 1080, pci bus id: 0000:02:00.0, compute capability: 6.1)
INFO:tensorflow:Checkpoint used: /tmp/pianoroll_rnn_nade/logdir/run1/train/model.ckpt-18421
INFO:tensorflow:Restoring parameters from /tmp/pianoroll_rnn_nade/logdir/run1/train/model.ckpt-18421
Traceback (most recent call last):
  File "/root/miniconda2/envs/magenta/bin/pianoroll_rnn_nade_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_generate.py", line 251, in console_entry_point
    tf.app.run(main)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 126, in run
    _sys.exit(main(argv))
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_generate.py", line 247, in main
    run_with_flags(generator)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_generate.py", line 210, in run_with_flags
    generated_sequence = generator.generate(primer_sequence, generator_options)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 196, in generate
    return self._generate(input_sequence, generator_options)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_sequence_generator.py", line 103, in _generate
    raise ValueError('No priming pianoroll could be extracted.')
ValueError: No priming pianoroll could be extracted.

to note: I am able to run nvcc -V and nvidia-smi. I've tried just about everything I can think of, and sure would appreciate a little guidance about what/where I missed something.

**Comment by adarob** [comment]
Sorry you're facing this issue!

Looking back at the code, it appears that we are not correctly handling the case when no priming sequence is provided. 

I believe we basically need a conditional to give an empty PianoRoll if the NoteSequence is empty here:
https://github.com/tensorflow/magenta/blob/48a199085e303eeae7c36068f050696209b856bb/magenta/models/pianoroll_rnn_nade/pianoroll_rnn_nade_sequence_generator.py#L88

This should be easy to fix, but I don't have time at the moment. You can either fix it yourself, wait until I can get to it (later this week?), or try giving it a primer sequence.

**Comment by HandsomeDevilv112** [comment]
No need to apologize! I'm just happy to have made it this far. 
ah, I didn't see a step where I should run pianoroll_rnn_nade_sequence_generator.py

The instructions I did catch were:
*building your dataset (convert_dir_to_note_sequences)
*sequence examples (pianoroll_rnn_nade_create_dataset)
*train (pianoroll_rnn_nade_train)
*generate (pianoroll_rnn_nade_generate) 

I'll give that a spin

**Comment by adarob** [comment]
You don't run pianoroll_rnn_nade_sequence_generator.py directly but it gets
called via pianoroll_rnn_nade_generate. The change that would be required
to fix the issue is in pianoroll_rnn_nade_sequence_generator.py, however.

**Comment by HandsomeDevilv112** [comment]
I was just about to edit my comment. I'm a little undercaffinated.

**Comment by adarob** [comment]
Ha no worries.

On Apr 10, 2018 9:35 AM, "HandsomeDevilv112" <notifications@github.com>
wrote:

I was just about to edit my comment. I'm a little undercaffinated.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/tensorflow/magenta/issues/1141#issuecomment-380166458>,
or mute the thread

**Comment by HandsomeDevilv112** [comment]
If I may bother you to hold my hand for another moment, I assume the answer is a little more involved than to plug in 
extracted_seqs, _ = mm.extract_pianoroll_sequences( /tmp/notesequences.tfrecord)
yeah?
