### ISSUE TITLE
Can't restore checkpoint extracted from melody_rnn bundle file

### ISSUE THREAD

**Issue by wanghoppe** [tensorflow/magenta#1186]
error message:
`INFO:tensorflow:Counting records in tmp/dataset/sequence_examples/training_melodies.tfrecord.
INFO:tensorflow:Number of records is at least 100.
INFO:tensorflow:[<tf.Tensor 'random_shuffle_queue_Dequeue:0' shape=(?, 121) dtype=float32>, <tf.Tensor 'random_shuffle_queue_Dequeue:1' shape=(?,) dtype=int64>, <tf.Tensor 'random_shuffle_queue_Dequeue:2' shape=() dtype=int32>]
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Restoring parameters from bundle_test/model.ckpt-1
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1322     try:
-> 1323       return fn(*args)
   1324     except errors.OpError as e:

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run_fn(session, feed_dict, fetch_list, target_list, options, run_metadata)
   1301                                    feed_dict, fetch_list, target_list,
-> 1302                                    status, run_metadata)
   1303 

~/.local/lib/python3.5/site-packages/tensorflow/python/framework/errors_impl.py in __exit__(self, type_arg, value_arg, traceback_arg)
    472             compat.as_text(c_api.TF_Message(self.status.status)),
--> 473             c_api.TF_GetCode(self.status.status))
    474     # Delete the underlying status object from memory otherwise it stays alive

NotFoundError: Tensor name "rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel/Adam_1" not found in checkpoint files bundle_test/model.ckpt-1
	 [[Node: save/RestoreV2_20 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_20/tensor_names, save/RestoreV2_20/shape_and_slices)]]
	 [[Node: save/RestoreV2_10/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_64_save/RestoreV2_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

During handling of the above exception, another exception occurred:

NotFoundError                             Traceback (most recent call last)
<ipython-input-29-bff480ba93d9> in <module>()
      2     build_graph_fn = build_graph_fn,
      3     train_dir = out_checkpoint_dir,
----> 4     num_training_steps=100
      5 )

~/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/magenta/models/shared/events_rnn_train.py in run_training(build_graph_fn, train_dir, num_training_steps, summary_frequency, save_checkpoint_secs, checkpoints_to_keep, master, task, num_ps_tasks)
     77           save_summaries_steps=summary_frequency,
     78           master=master,
---> 79           is_chief=task == 0)
     80       tf.logging.info('Training complete.')
     81 

~/.local/lib/python3.5/site-packages/tensorflow/contrib/training/python/training/training.py in train(train_op, logdir, master, is_chief, scaffold, hooks, chief_only_hooks, save_checkpoint_secs, save_summaries_steps, config)
    533       save_checkpoint_secs=save_checkpoint_secs,
    534       save_summaries_steps=save_summaries_steps,
--> 535       config=config) as session:
    536     loss = None
    537     while not session.should_stop():

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in MonitoredTrainingSession(master, is_chief, checkpoint_dir, scaffold, hooks, chief_only_hooks, save_checkpoint_secs, save_summaries_steps, save_summaries_secs, config, stop_grace_period_secs, log_step_count_steps)
    366     all_hooks.extend(hooks)
    367   return MonitoredSession(session_creator=session_creator, hooks=all_hooks,
--> 368                           stop_grace_period_secs=stop_grace_period_secs)
    369 
    370 

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in __init__(self, session_creator, hooks, stop_grace_period_secs)
    671     super(MonitoredSession, self).__init__(
    672         session_creator, hooks, should_recover=True,
--> 673         stop_grace_period_secs=stop_grace_period_secs)
    674 
    675 

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in __init__(self, session_creator, hooks, should_recover, stop_grace_period_secs)
    491         stop_grace_period_secs=stop_grace_period_secs)
    492     if should_recover:
--> 493       self._sess = _RecoverableSession(self._coordinated_creator)
    494     else:
    495       self._sess = self._coordinated_creator.create_session()

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in __init__(self, sess_creator)
    849     """
    850     self._sess_creator = sess_creator
--> 851     _WrappedSession.__init__(self, self._create_session())
    852 
    853   def _create_session(self):

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in _create_session(self)
    854     while True:
    855       try:
--> 856         return self._sess_creator.create_session()
    857       except _PREEMPTION_ERRORS as e:
    858         logging.info('An error was raised while a session was being created. '

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in create_session(self)
    552       """Creates a coordinated session."""
    553       # Keep the tf_sess for unit testing.
--> 554       self.tf_sess = self._session_creator.create_session()
    555       # We don't want coordinator to suppress any exception.
    556       self.coord = coordinator.Coordinator(clean_stop_exception_types=[])

~/.local/lib/python3.5/site-packages/tensorflow/python/training/monitored_session.py in create_session(self)
    426         init_op=self._scaffold.init_op,
    427         init_feed_dict=self._scaffold.init_feed_dict,
--> 428         init_fn=self._scaffold.init_fn)
    429 
    430 

~/.local/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py in prepare_session(self, master, init_op, saver, checkpoint_dir, checkpoint_filename_with_path, wait_for_checkpoint, max_wait_secs, config, init_feed_dict, init_fn)
    271         wait_for_checkpoint=wait_for_checkpoint,
    272         max_wait_secs=max_wait_secs,
--> 273         config=config)
    274     if not is_loaded_from_checkpoint:
    275       if init_op is None and not init_fn and self._local_init_op is None:

~/.local/lib/python3.5/site-packages/tensorflow/python/training/session_manager.py in _restore_checkpoint(self, master, saver, checkpoint_dir, checkpoint_filename_with_path, wait_for_checkpoint, max_wait_secs, config)
    203 
    204     # Loads the checkpoint.
--> 205     saver.restore(sess, ckpt.model_checkpoint_path)
    206     saver.recover_last_checkpoints(ckpt.all_model_checkpoint_paths)
    207     return sess, True

~/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py in restore(self, sess, save_path)
   1664     if context.in_graph_mode():
   1665       sess.run(self.saver_def.restore_op_name,
-> 1666                {self.saver_def.filename_tensor_name: save_path})
   1667     else:
   1668       self._build_eager(save_path, build_save=False, build_restore=True)

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    887     try:
    888       result = self._run(None, fetches, feed_dict, options_ptr,
--> 889                          run_metadata_ptr)
    890       if run_metadata:
    891         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1118     if final_fetches or final_targets or (handle and feed_dict_tensor):
   1119       results = self._do_run(handle, final_targets, final_fetches,
-> 1120                              feed_dict_tensor, options, run_metadata)
   1121     else:
   1122       results = []

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1315     if handle is None:
   1316       return self._do_call(_run_fn, self._session, feeds, fetches, targets,
-> 1317                            options, run_metadata)
   1318     else:
   1319       return self._do_call(_prun_fn, self._session, handle, feeds, fetches)

~/.local/lib/python3.5/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1334         except KeyError:
   1335           pass
-> 1336       raise type(e)(node_def, op, message)
   1337 
   1338   def _extend_graph(self):

NotFoundError: Tensor name "rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel/Adam_1" not found in checkpoint files bundle_test/model.ckpt-1
	 [[Node: save/RestoreV2_20 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_20/tensor_names, save/RestoreV2_20/shape_and_slices)]]
	 [[Node: save/RestoreV2_10/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_64_save/RestoreV2_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]

Caused by op 'save/RestoreV2_20', defined at:
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel/kernelapp.py", line 486, in start
    self.io_loop.start()
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 233, in dispatch_shell
    handler(stream, idents, msg)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel/ipkernel.py", line 208, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/ipykernel/zmqshell.py", line 537, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2662, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2785, in _run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2909, in run_ast_nodes
    if self.run_code(code, result):
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/IPython/core/interactiveshell.py", line 2963, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-29-bff480ba93d9>", line 4, in <module>
    num_training_steps=100
  File "/home/hoppe/anaconda3/envs/tensorflow_env/lib/python3.5/site-packages/magenta/models/shared/events_rnn_train.py", line 68, in run_training
    saver=tf.train.Saver(max_to_keep=checkpoints_to_keep))
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1218, in __init__
    self.build()
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1227, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 1263, in _build
    build_save=build_save, build_restore=build_restore)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 751, in _build_internal
    restore_sequentially, reshape)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 427, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/training/saver.py", line 267, in restore_op
    [spec.tensor.dtype])[0])
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1021, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 2956, in create_op
    op_def=op_def)
  File "/home/hoppe/.local/lib/python3.5/site-packages/tensorflow/python/framework/ops.py", line 1470, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

NotFoundError (see above for traceback): Tensor name "rnn/multi_rnn_cell/cell_1/basic_lstm_cell/kernel/Adam_1" not found in checkpoint files bundle_test/model.ckpt-1
	 [[Node: save/RestoreV2_20 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2_20/tensor_names, save/RestoreV2_20/shape_and_slices)]]
	 [[Node: save/RestoreV2_10/_19 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device_incarnation=1, tensor_name="edge_64_save/RestoreV2_10", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:GPU:0"]()]]`

**Comment by cghawthorne** [comment]
@adarob were these checkpoints ones that you have or were going to update at some point?
