### ISSUE TITLE
magenta - installation issue

### ISSUE THREAD

**Issue by gopi77** [tensorflow/magenta#1187]
1. Installed tensorflow 1.8 (built from source) using pip install (In the virtual environment ), verified the version & it works fine.
>> python -c 'import tensorflow as tf; print(tf.__version__)'
1.8.0

My environment:
Ubuntu 16.04
Conda 4.4.10
Python 3.6.4 |Anaconda, Inc.| 
GCC 7.2.0
Cuda toolkit 9.2
Cudnn 7.1.4
Tensorflow source (git clone done on May 26th)

2. Installed magenta (built from source) using pip install (In the virtual environment ), verified with version print command but got error.

pip install --ignore-installed --upgrade ~/magenta_pkg/magenta_gpu-0.3.7-py2.py3-none-any.whl
Processing ./magenta_pkg/magenta_gpu-0.3.7-py2.py3-none-any.whl
Collecting bokeh>=0.12.0 (from magenta-gpu==0.3.7)
Collecting matplotlib>=1.5.3 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/49/b8/89dbd27f2fb171ce753bb56220d4d4f6dbc5fe32b95d8edc4415782ef07f/matplotlib-2.2.2-cp36-cp36m-manylinux1_x86_64.whl
Collecting intervaltree>=2.1.0 (from magenta-gpu==0.3.7)
Collecting pandas>=0.18.1 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/69/ec/8ff0800b8594691759b78a42ccd616f81e7099ee47b167eb9bbd502c02b9/pandas-0.23.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting scipy>=0.18.1 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/a8/0b/f163da98d3a01b3e0ef1cab8dd2123c34aee2bafbb1c5bffa354cc8a1730/scipy-1.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting pretty-midi>=0.2.6 (from magenta-gpu==0.3.7)
Collecting python-rtmidi (from magenta-gpu==0.3.7)
Collecting librosa>=0.6.0 (from magenta-gpu==0.3.7)
Collecting tensorflow-gpu>=1.4.0 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/59/41/ba6ac9b63c5bfb90377784e29c4f4c478c74f53e020fa56237c939674f2d/tensorflow_gpu-1.8.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting wheel (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/81/30/e935244ca6165187ae8be876b6316ae201b71485538ffac1d718843025a9/wheel-0.31.1-py2.py3-none-any.whl
Collecting IPython (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/b1/7f/91d50f28af3e3a24342561983a7857e399ce24093876e6970b986a0b6677/ipython-6.4.0-py3-none-any.whl
Collecting mir-eval>=0.4 (from magenta-gpu==0.3.7)
Collecting Pillow>=3.4.2 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/5f/4b/8b54ab9d37b93998c81b364557dff9f61972c0f650efa0ceaf470b392740/Pillow-5.1.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting numpy>=1.11.0 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/71/90/ca61e203e0080a8cef7ac21eca199829fa8d997f7c4da3e985b49d0a107d/numpy-1.14.3-cp36-cp36m-manylinux1_x86_64.whl
Collecting mido==1.2.6 (from magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/10/51/447066f537e05996a4579829b93390a4d85b0e3da90c5fbc34c1e70a37d5/mido-1.2.6-py2.py3-none-any.whl
Collecting PyYAML>=3.10 (from bokeh>=0.12.0->magenta-gpu==0.3.7)
Collecting python-dateutil>=2.1 (from bokeh>=0.12.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/cf/f5/af2b09c957ace60dcfac112b669c45c8c97e32f94aa8b56da4c6d1682825/python_dateutil-2.7.3-py2.py3-none-any.whl
Collecting six>=1.5.2 (from bokeh>=0.12.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/67/4b/141a581104b1f6397bfa78ac9d43d8ad29a7ca43ea90a2d863fe3056e86a/six-1.11.0-py2.py3-none-any.whl
Collecting tornado>=4.3 (from bokeh>=0.12.0->magenta-gpu==0.3.7)
Collecting packaging>=16.8 (from bokeh>=0.12.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/ad/c2/b500ea05d5f9f361a562f089fc91f77ed3b4783e13a08a3daf82069b1224/packaging-17.1-py2.py3-none-any.whl
Collecting Jinja2>=2.7 (from bokeh>=0.12.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/7f/ff/ae64bacdfc95f27a016a7bed8e8686763ba4d277a78ca76f32659220a731/Jinja2-2.10-py2.py3-none-any.whl
Collecting pytz (from matplotlib>=1.5.3->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/dc/83/15f7833b70d3e067ca91467ca245bae0f6fe56ddc7451aa0dc5606b120f2/pytz-2018.4-py2.py3-none-any.whl
Collecting pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 (from matplotlib>=1.5.3->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/6a/8a/718fd7d3458f9fab8e67186b00abdd345b639976bc7fb3ae722e1b026a50/pyparsing-2.2.0-py2.py3-none-any.whl
Collecting kiwisolver>=1.0.1 (from matplotlib>=1.5.3->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/69/a7/88719d132b18300b4369fbffa741841cfd36d1e637e1990f27929945b538/kiwisolver-1.0.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting cycler>=0.10 (from matplotlib>=1.5.3->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/f7/d2/e07d3ebb2bd7af696440ce7e754c59dd546ffe1bbe732c8ab68b9c834e61/cycler-0.10.0-py2.py3-none-any.whl
Collecting sortedcontainers (from intervaltree>=2.1.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/de/20/1403d968975ff68eef437793d11d0f4798709f441870de1a4e240c859c19/sortedcontainers-2.0.2-py2.py3-none-any.whl
Collecting scikit-learn!=0.19.0,>=0.14.0 (from librosa>=0.6.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/3d/2d/9fbc7baa5f44bc9e88ffb7ed32721b879bfa416573e85031e16f52569bc9/scikit_learn-0.19.1-cp36-cp36m-manylinux1_x86_64.whl
Collecting numba>=0.38.0 (from librosa>=0.6.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/00/36/41d894e24e0d00d85e7ed10880deb391f6b6679ae43db25ea6d036476c8c/numba-0.38.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting decorator>=3.0.0 (from librosa>=0.6.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/bc/bb/a24838832ba35baf52f32ab1a49b906b5f82fb7c76b2f6a7e35e140bac30/decorator-4.3.0-py2.py3-none-any.whl
Collecting resampy>=0.2.0 (from librosa>=0.6.0->magenta-gpu==0.3.7)
Collecting joblib>=0.7.0 (from librosa>=0.6.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/4f/51/870b2ec270fc29c5d89f85353da420606a9cb39fba4747127e7c7d7eb25d/joblib-0.11-py2.py3-none-any.whl
Collecting audioread>=2.0.0 (from librosa>=0.6.0->magenta-gpu==0.3.7)
Collecting tensorboard<1.9.0,>=1.8.0 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/59/a6/0ae6092b7542cfedba6b2a1c9b8dceaf278238c39484f3ba03b03f07803c/tensorboard-1.8.0-py3-none-any.whl
Collecting absl-py>=0.1.6 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
Collecting termcolor>=1.1.0 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
Collecting astor>=0.6.0 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/b2/91/cc9805f1ff7b49f620136b3a7ca26f6a1be2ed424606804b0fbcf499f712/astor-0.6.2-py2.py3-none-any.whl
Collecting gast>=0.2.0 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
Collecting grpcio>=1.8.6 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/05/6d/f659683f0dfd3b3bebcd476821f2c598637e4e8948ff898f984867e96bc6/grpcio-1.12.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting protobuf>=3.4.0 (from tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/74/ad/ecd865eb1ba1ff7f6bd6bcb731a89d55bc0450ced8d457ed2d167c7b8d5f/protobuf-3.5.2.post1-cp36-cp36m-manylinux1_x86_64.whl
Collecting pickleshare (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/9f/17/daa142fc9be6b76f26f24eeeb9a138940671490b91cb5587393f297c8317/pickleshare-0.7.4-py2.py3-none-any.whl
Collecting pexpect; sys_platform != "win32" (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/b9/3c/e51a76fe78a877afd9acd95a51e3b7610c0983b19ef5a5dfa11735a619b8/pexpect-4.5.0-py2.py3-none-any.whl
Collecting simplegeneric>0.8 (from IPython->magenta-gpu==0.3.7)
Collecting setuptools>=18.5 (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/7f/e1/820d941153923aac1d49d7fc37e17b6e73bfbd2904959fffbad77900cf92/setuptools-39.2.0-py2.py3-none-any.whl
Collecting backcall (from IPython->magenta-gpu==0.3.7)
Collecting pygments (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/02/ee/b6e02dc6529e82b75bb06823ff7d005b141037cb1416b10c6f00fc419dca/Pygments-2.2.0-py2.py3-none-any.whl
Collecting prompt-toolkit<2.0.0,>=1.0.15 (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/04/d1/c6616dd03701e7e2073f06d5c3b41b012256e42b72561f16a7bd86dd7b43/prompt_toolkit-1.0.15-py3-none-any.whl
Collecting traitlets>=4.2 (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/93/d6/abcb22de61d78e2fc3959c964628a5771e47e7cc60d53e9342e21ed6cc9a/traitlets-4.3.2-py2.py3-none-any.whl
Collecting jedi>=0.10 (from IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/e7/42/074192a165622e645ed4aeade63e76e56b3496a044569b3c6cae3a918352/jedi-0.12.0-py2.py3-none-any.whl
Collecting future (from mir-eval>=0.4->magenta-gpu==0.3.7)
Collecting MarkupSafe>=0.23 (from Jinja2>=2.7->bokeh>=0.12.0->magenta-gpu==0.3.7)
Collecting llvmlite>=0.23.0dev0 (from numba>=0.38.0->librosa>=0.6.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/4c/71/9ac956af0bc8e6624db7ff1653426a4d3f2fcb72bc6707f022158e62b64f/llvmlite-0.23.0-cp36-cp36m-manylinux1_x86_64.whl
Collecting markdown>=2.6.8 (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/6d/7d/488b90f470b96531a3f5788cf12a93332f543dbab13c423a5e7ce96a0493/Markdown-2.6.11-py2.py3-none-any.whl
Collecting bleach==1.5.0 (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/33/70/86c5fec937ea4964184d4d6c4f0b9551564f821e1c3575907639036d9b90/bleach-1.5.0-py2.py3-none-any.whl
Collecting html5lib==0.9999999 (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
Collecting werkzeug>=0.11.10 (from tensorboard<1.9.0,>=1.8.0->tensorflow-gpu>=1.4.0->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/20/c4/12e3e56473e52375aa29c4764e70d1b8f3efa6682bef8d0aae04fe335243/Werkzeug-0.14.1-py2.py3-none-any.whl
Collecting ptyprocess>=0.5 (from pexpect; sys_platform != "win32"->IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/ff/4e/fa4a73ccfefe2b37d7b6898329e7dbcd1ac846ba3a3b26b294a78a3eb997/ptyprocess-0.5.2-py2.py3-none-any.whl
Collecting wcwidth (from prompt-toolkit<2.0.0,>=1.0.15->IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/7e/9f/526a6947247599b084ee5232e4f9190a38f398d7300d866af3ab571a5bfe/wcwidth-0.1.7-py2.py3-none-any.whl
Collecting ipython-genutils (from traitlets>=4.2->IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/fa/bc/9bd3b5c2b4774d5f33b2d544f1460be9df7df2fe42f352135381c347c69a/ipython_genutils-0.2.0-py2.py3-none-any.whl
Collecting parso>=0.2.0 (from jedi>=0.10->IPython->magenta-gpu==0.3.7)
  Using cached https://files.pythonhosted.org/packages/cd/3e/5908f9577dbd1e5df53e64349bfd11e46b726c1e4d8cd676bbe8aa4de316/parso-0.2.1-py2.py3-none-any.whl
Installing collected packages: numpy, PyYAML, six, python-dateutil, tornado, pyparsing, packaging, MarkupSafe, Jinja2, bokeh, pytz, setuptools, kiwisolver, cycler, matplotlib, sortedcontainers, intervaltree, pandas, scipy, mido, pretty-midi, python-rtmidi, scikit-learn, llvmlite, numba, decorator, resampy, joblib, audioread, librosa, markdown, html5lib, bleach, werkzeug, wheel, protobuf, tensorboard, absl-py, termcolor, astor, gast, grpcio, tensorflow-gpu, pickleshare, ptyprocess, pexpect, simplegeneric, backcall, pygments, wcwidth, prompt-toolkit, ipython-genutils, traitlets, parso, jedi, IPython, future, mir-eval, Pillow, magenta-gpu
Successfully installed IPython-6.4.0 Jinja2-2.10 MarkupSafe-1.0 Pillow-5.1.0 PyYAML-3.12 absl-py-0.2.2 astor-0.6.2 audioread-2.1.5 backcall-0.1.0 bleach-1.5.0 bokeh-0.12.16 cycler-0.10.0 decorator-4.3.0 future-0.16.0 gast-0.2.0 grpcio-1.12.0 html5lib-0.9999999 intervaltree-2.1.0 ipython-genutils-0.2.0 jedi-0.12.0 joblib-0.11 kiwisolver-1.0.1 librosa-0.6.1 llvmlite-0.23.0 magenta-gpu-0.3.7 markdown-2.6.11 matplotlib-2.2.2 mido-1.2.6 mir-eval-0.4 numba-0.38.0 numpy-1.14.3 packaging-17.1 pandas-0.23.0 parso-0.2.1 pexpect-4.5.0 pickleshare-0.7.4 pretty-midi-0.2.8 prompt-toolkit-1.0.15 protobuf-3.5.2.post1 ptyprocess-0.5.2 pygments-2.2.0 pyparsing-2.2.0 python-dateutil-2.7.3 python-rtmidi-1.1.0 pytz-2018.4 resampy-0.2.0 scikit-learn-0.19.1 scipy-1.1.0 setuptools-39.2.0 simplegeneric-0.8.1 six-1.11.0 sortedcontainers-2.0.2 tensorboard-1.8.0 tensorflow-gpu-1.8.0 termcolor-1.1.0 tornado-5.0.2 traitlets-4.3.2 wcwidth-0.1.7 werkzeug-0.14.1 wheel-0.31.1

--------------

python -c 'import magenta; print(magenta.__version__)'
Traceback (most recent call last):
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/magenta/__init__.py", line 26, in <module>
    import magenta.common.beam_search
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/magenta/common/__init__.py", line 19, in <module>
    from . import state_util
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/magenta/common/state_util.py", line 20, in <module>
    from tensorflow.python.util import nest as tf_nest
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

-------------------

Then the tensorflow also stopped  working

python -c 'import tensorflow as tf; print(tf.__version__)'
Traceback (most recent call last):
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/imp.py", line 243, in load_module
    return load_dynamic(name, filename, file)
  File "/home/gopi/anaconda3/envs/magenta_gpu_2/lib/python3.6/imp.py", line 343, in load_dynamic
    return _load(spec)
ImportError: libcublas.so.9.0: cannot open shared object file: No such file or directory

-------

>>> Looks like tensorflow-gpu-1.8.0 getting reinstalled with pre-built binary & creates error, how to skip this during magenta installation ? 
(Also the virtual environment got spoiled, need to create another one to make tensorflow work again as per step 1, please help to repair/retain the virtual environment)

**Comment by cghawthorne** [comment]
Closing due to inactivity.
