### ISSUE TITLE
melody_rnn_generate

### ISSUE THREAD

**Issue by Techagogy** [tensorflow/magenta#1213]
When I try to run melody_rnn_generate on a basic_rnn.mag I get the following error.
BUNDLE_PATH=<absolute path of .mag file>
CONFIG=<one of 'basic_rnn', 'lookback_rnn', or 'attention_rnn', matching the bundle>

melody_rnn_generate \
--config=${CONFIG} \
--bundle_file=${BUNDLE_PATH} \
--output_dir=/tmp/melody_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"

The bundle path and config are on the desktop

Traceback (most recent call last):
  File "/home/a/anaconda2/envs/magenta/bin/melody_rnn_generate", line 7, in <module>
    from magenta.models.melody_rnn.melody_rnn_generate import console_entry_point
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/magenta/__init__.py", line 34, in <module>
    import magenta.music.audio_io
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/audio_io.py", line 20, in <module>
    import librosa
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/home/a/anaconda2/envs/magenta/lib/python2.7/site-packages/joblib/memory.py", line 847, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer

**Comment by ashwinreddy** [comment]
I am having a similar issue with the Sketch RNN example. I've added the traceback below when running `sketch_rnn_train`.

```
Traceback (most recent call last):
  File "/home/areddy/anaconda3/envs/magenta/bin/sketch_rnn_train", line 7, in <module>
    from magenta.models.sketch_rnn.sketch_rnn_train import console_entry_point
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/__init__.py", line 34, in <module>
    import magenta.music.audio_io
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/music/audio_io.py", line 20, in <module>
    import librosa
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/librosa/__init__.py", line 12, in <module>
    from . import core
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/librosa/core/__init__.py", line 104, in <module>
    from .time_frequency import *  # pylint: disable=wildcard-import
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/librosa/core/time_frequency.py", line 10, in <module>
    from ..util.exceptions import ParameterError
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/librosa/util/__init__.py", line 67, in <module>
    from .utils import *  # pylint: disable=wildcard-import
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/librosa/util/utils.py", line 111, in <module>
    def valid_audio(y, mono=True):
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/librosa/cache.py", line 49, in wrapper
    if self.cachedir is not None and self.level >= level:
  File "/home/areddy/anaconda3/envs/magenta/lib/python2.7/site-packages/joblib/memory.py", line 847, in cachedir
    DeprecationWarning, stacklevel=2)
TypeError: expected string or buffer
```

**Comment by pwallrich** [comment]
+ 1
