### ISSUE TITLE
MusicVAE - error when training on models with chord conditioning

### ISSUE THREAD

**Issue by timmy0519** [tensorflow/magenta#1241]
Hi, I have tried to train my own models  which implemented with chord conditioning with my own dataset. 
 (--config=cat-mel_2bar_med_chords)

But there are some problems with my training, so I attempt to use another model without chord conditioning.
(--config=cat-mel_2bar_small)
then the error doesn't happen.

Therefore, I think I have missed some settings to apply chord encoding to the model.
Can someone help me to fix it, please 

Anyway, here is my command:

```
python music_vae_train.py 
--config=cat-mel_2bar_med_chords 
--run_dir=/tmp/MusicVAE 
--mode=train 
--examples_path=/tmp/notesequences.tfrecord
```

```
2018-07-30 15:59:46.555253: W tensorflow/core/framework/op_kernel.cc:1318] OP_REQUIRES failed at strided_slice_op.cc:105 : Invalid argument: slice index 512 of dimension 0 out of bounds.
Traceback (most recent call last):
  File "music_vae_train.py", line 334, in <module>
    console_entry_point()
  File "music_vae_train.py", line 330, in console_entry_point
    tf.app.run(main)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "music_vae_train.py", line 325, in main
    run(configs.CONFIG_MAP)
  File "music_vae_train.py", line 307, in run
    task=FLAGS.task)
  File "music_vae_train.py", line 215, in train
    is_chief=is_chief)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py", line 544, in train
    loss = session.run(train_op)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 577, in run
    run_metadata=run_metadata)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1053, in run
    run_metadata=run_metadata)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1144, in run
    raise six.reraise(*original_exc_info)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1129, in run
    return self._sess.run(*args, **kwargs)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 1201, in run
    run_metadata=run_metadata)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 981, in run
    return self._sess.run(*args, **kwargs)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 900, in run
    run_metadata_ptr)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1135, in _run
    feed_dict_tensor, options, run_metadata)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1316, in _do_run
    run_metadata)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1335, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: slice index 11 of dimension 0 out of bounds.
         [[Node: strided_slice_40 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat_3, strided_slice_37/stack_1, strided_slice_40/stack_1, gradients/Mean_1_grad/Reshape/shape)]]
         [[Node: decoder/TrainingHelperInitialize/cond/switch_f/_522 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4023_decoder/TrainingHelperInitialize/cond/switch_f", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

Caused by op u'strided_slice_40', defined at:
  File "music_vae_train.py", line 334, in <module>
    console_entry_point()
  File "music_vae_train.py", line 330, in console_entry_point
    tf.app.run(main)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "music_vae_train.py", line 325, in main
    run(configs.CONFIG_MAP)
  File "music_vae_train.py", line 307, in run
    task=FLAGS.task)
  File "music_vae_train.py", line 168, in train
    optimizer = model.train(**_get_input_tensors(dataset, config))
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/magenta/models/music_vae/base_model.py", line 296, in train
    input_sequence, output_sequence, sequence_length, control_sequence)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/magenta/models/music_vae/base_model.py", line 260, in _compute_model_loss
    x_input, x_target, x_length, z, control_sequence)[0:2]
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/magenta/models/music_vae/lstm_models.py", line 466, in reconstruction_loss
    b, e = cum_x_len[i], cum_x_len[i + 1]
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 523, in _slice_helper
    name=name)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/array_ops.py", line 689, in strided_slice
    shrink_axis_mask=shrink_axis_mask)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/ops/gen_array_ops.py", line 8232, in strided_slice
    name=name)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3414, in create_op
    op_def=op_def)
  File "/home/fy107_summer_intern_4/miniconda2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1740, in __init__
    self._traceback = self._graph._extract_stack()  # pylint: disable=protected-access

InvalidArgumentError (see above for traceback): slice index 11 of dimension 0 out of bounds.
         [[Node: strided_slice_40 = StridedSlice[Index=DT_INT32, T=DT_INT32, begin_mask=0, ellipsis_mask=0, end_mask=0, new_axis_mask=0, shrink_axis_mask=1, _device="/job:localhost/replica:0/task:0/device:GPU:0"](concat_3, strided_slice_37/stack_1, strided_slice_40/stack_1, gradients/Mean_1_grad/Reshape/shape)]]
         [[Node: decoder/TrainingHelperInitialize/cond/switch_f/_522 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/device:CPU:0", send_device="/job:localhost/replica:0/task:0/device:GPU:0", send_device_incarnation=1, tensor_name="edge_4023_decoder/TrainingHelperInitialize/cond/switch_f", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/device:CPU:0"]()]]

```

**Comment by timmy0519** [comment]
Somehow even the models without chord conditioning also occur the same error. I don't really know why.
