### ISSUE TITLE
Errors on Latest version of pip package

### ISSUE THREAD

**Issue by annymao** [tensorflow/magenta#1245]
Hi,
I have upgraded the package to the latest version(0.3.10)
when I train MusicVAE 

`music_vae_train --config=cat-mel_2bar_med_chords --run_dir=/users/student/mr107/annymao/music_vae/ --mode=train --examples_path="/users/student/mr107/annymao/music_vae/mel_train_examples.tfrecord"`

it comes out following error message
`Traceback (most recent call last):
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/bin/music_vae_train", line 7, in <module>
    from magenta.models.music_vae.music_vae_train import console_entry_point
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/__init__.py", line 33, in <module>
    import magenta.music.abc_parser
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/__init__.py", line 20, in <module>
    from magenta.music.chord_inference import ChordInferenceException
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/chord_inference.py", line 30, in <module>
    from magenta.music import sequences_lib
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/sequences_lib.py", line 42, in <module>
    BEAT = music_pb2.NoteSequence.TextAnnotation.BEAT
AttributeError: type object 'TextAnnotation' has no attribute 'BEAT'
`

it seems that "BEAT" is missing in the music_pb2.py
and the "performance_controls.py" and "data_hierachy.py" are also missing

`Traceback (most recent call last):
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/bin/music_vae_train", line 7, in <module>
    from magenta.models.music_vae.music_vae_train import console_entry_point
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/__init__.py", line 33, in <module>
    import magenta.music.abc_parser
  File "/users/student/mr107/annymao/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/__init__.py", line 93, in <module>
    from magenta.music.performance_controls import all_performance_control_signals
ImportError: No module named performance_controls
`

Could you help us fix the bugs?
Thanks!

**Comment by cherily** [comment]
same question

**Comment by InhyukYee** [comment]
same here

**Comment by Jeffzzf** [comment]
Mac OS 10.13.6, python 3.5 same problem

**Comment by lyq123180** [comment]
same here

**Comment by howardlau1999** [comment]
Use bazel to build from the latest source, NO ERRORS.

**Comment by adarob** [comment]
Thanks for reporting. Looking into it now.

**Comment by adarob** [comment]
Please upgrade to 0.3.11.
