### ISSUE TITLE
can't train nsynth

### ISSUE THREAD

**Issue by cherily** [tensorflow/magenta#1247]
1) I try to train the baseline, error comes as below

(tensorflow) chenjiali02@img-cjl-xf9q5:~/02_project/02_magenta/magenta$ bazel run //magenta/models/nsynth/baseline:train -- \
> --train_path=/home/chenjiali02/03_data/The NSynth Dataset/nsynth-train.tfrecord \
> ---logdir=/home/chenjiali02/tmp/baseline/train
WARNING: Output base '/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4' is on NFS. This may lead to surprd undetermined behavior.
INFO: Analysed target //magenta/models/nsynth/baseline:train (0 packages loaded).
INFO: Found 1 target...
Target //magenta/models/nsynth/baseline:train up-to-date:
  bazel-bin/magenta/models/nsynth/baseline/train
INFO: Elapsed time: 0.936s, Critical Path: 0.07s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/magenta/models/nsynth/baseline/train '--train_path=/home/chenjiali02/03_data/The' NSynth Dataset/nsyn
INFO: Build completed successfully, 1 total action
Traceback (most recent call last):
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/baseline/train.runfiles/__main__/magenta/models/nsynth/baseline/train.py", line 100, in <module>
    tf.app.run()
  File "/home/chenjiali02/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/baseline/train.runfiles/__main__/magenta/models/nsynth/baseline/train.py", line 74, in main
    hparams = model.get_hparams(FLAGS.config)
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/baseline/train.runfiles/__main__/magenta/models/nsynth/baseline/models/ae.py", line 69, in get_hparams
    hparams.update(config_hparams)
AttributeError: 'HParams' object has no attribute 'update'
does it have some bugs?

2) I also train the method of wavenet in nsynth, it can't work.

(tensorflow) chenjiali02@img-cjl-xf9q5:~/02_project/02_magenta/magenta$ bazel run //magenta/models/nsynth/wavenet:train -- \
> --train_path=/home/chenjiali02/03_data/The NSynth Dataset/nsynth-train.tfrecord \
> --logdir=/home/chenjiali02/tmp/wavenet/train
WARNING: Output base '/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4' is on NFS. This may lead to surprising failures and undetermined behavior.
INFO: Analysed target //magenta/models/nsynth/wavenet:train (0 packages loaded).
INFO: Found 1 target...
Target //magenta/models/nsynth/wavenet:train up-to-date:
  bazel-bin/magenta/models/nsynth/wavenet/train
INFO: Elapsed time: 0.875s, Critical Path: 0.04s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/magenta/models/nsynth/wavenet/train '--train_path=/home/chenjiali02/03_data/The' NSynth Dataset/nsyn
INFO: Build completed successfully, 1 total action
WARNING:tensorflow:From /home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/wavenet/train.runfiles/__main__/magenta/models/nsynth/wavenet/masked.py:116: UniformUnitScaling.__init__ (from tensorflow.python.ops.init_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.initializers.variance_scaling instead with distribution=uniform to get equivalent behavior.
INFO:tensorflow:Saving to /home/chenjiali02/tmp/wavenet/train
Traceback (most recent call last):
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/wavenet/train.runfiles/__main__/magenta/models/nsynth/wavenet/train.py", line 136, in <module>
    tf.app.run()
  File "/home/chenjiali02/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/wavenet/train.runfiles/__main__/magenta/models/nsynth/wavenet/train.py", line 76, in main
    inputs_dict = config.get_batch(worker_batch_size)
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/wavenet/train.runfiles/__main__/magenta/models/nsynth/wavenet/h512_bo16.py", line 161, in get_batch
    return data_train.get_wavenet_batch(batch_size, length=6144)
  File "/home/chenjiali02/.cache/bazel/_bazel_chenjiali02/0d4c6e497e99c833a56f792a2d3004c4/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/wavenet/train.runfiles/__main__/magenta/models/nsynth/reader.py", line 99, in get_wavenet_batch
    min_after_dequeue=200 * batch_size)
  File "/home/chenjiali02/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 1300, in shuffle_batch
    name=name)
  File "/home/chenjiali02/anaconda3/envs/tensorflow/lib/python3.5/site-packages/tensorflow/python/training/input.py", line 834, in _shuffle_batch
    math_ops.maximum(0, queue.size() - min_after_dequeue)) *
TypeError: unsupported operand type(s) for -: 'Tensor' and 'float'

how can I train these two methods in a right way, Please give me some suggestions, Thanks a lot.

**Comment by sirdr** [comment]
@cherily which version of python are you using ? I was able to solve the second problem by switching to python 2.7 from 3.6 ... I'm assuming it has something to do with differences in the return type of tf.size() when using python 2.7 versus 3.6.
