### ISSUE TITLE
ERROR: Non-zero return code '1' from command

### ISSUE THREAD

**Issue by oatmeal3000** [tensorflow/magenta#125]
$ sh 2extractSample.sh 
WARNING: /home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/external/protobuf/WORKSPACE:1: Workspace name in /home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 1 target...
Target //magenta/models/basic_rnn:basic_rnn_create_dataset up-to-date:
  bazel-bin/magenta/models/basic_rnn/basic_rnn_create_dataset
INFO: Elapsed time: 0.144s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/magenta/models/basic_rnn/basic_rnn_create_dataset '--input=/home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord' '--train_output=/home/oatmeal/HiMusic/Output/train_dance.tfrecord' '--eval_ratio=0.10'
Traceback (most recent call last):
  File "/home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_create_dataset.py", line 41, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_create_dataset.py", line 37, in main
    basic_rnn_encoder_decoder.MelodyEncoderDecoder())
  File "/home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/models/shared/melody_rnn_create_dataset.py", line 121, in run_from_flags
    FLAGS.output_dir)
  File "/home/oatmeal/.cache/bazel/_bazel_oatmeal/c3300a0566708e561674ab71c996c139/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn/basic_rnn_create_dataset.runfiles/__main__/magenta/pipelines/pipeline.py", line 196, in run_pipeline_serial
    if not tf.gfile.Exists(output_dir):
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/gfile.py", line 252, in Exists
    return os.path.exists(path)
  File "/usr/lib/python2.7/genericpath.py", line 18, in exists
    os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
ERROR: Non-zero return code '1' from command: Process exited with status 1.

oatmeal@oatmeal-ThinkPad-X240:~/HiMusic/magenta$ cat 2extractSample.sh 
SEQUENCES_TFRECORD=/home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord
TRAIN_DATA=/home/oatmeal/HiMusic/Output/train_dance.tfrecord
EVAL_RATIO=0.10
     
bazel run //magenta/models/basic_rnn:basic_rnn_create_dataset -- \
--input=$SEQUENCES_TFRECORD \
--train_output=$TRAIN_DATA \
--eval_ratio=$EVAL_RATIO

oatmeal@oatmeal-ThinkPad-X240:~/HiMusic/magenta$ ls -l /home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord
-rw-r--r-- 1 oatmeal oatmeal 891921  8月  1 22:59 /home/oatmeal/HiMusic/Output/Dance_sequences.tfrecord

**Comment by adarob** [comment]
Hi, it looks like you might be using the wrong (maybe old) flags.  The usage example shows:

  $ ./bazel-bin/magenta/models/basic_rnn/basic_rnn_create_dataset \
    --input=/tmp/note_sequences.tfrecord \
    --output_dir=/tmp/basic_rnn \
    --eval_ratio=0.10

Can you try again with output_dir instead of train_output and close this issue if it works? Thanks.

**Comment by oatmeal3000** [comment]
Thanks, it works!
