### ISSUE TITLE
MusicVAE - tensorflow.python.framework.errors_impl.NotFoundError: ; No such file or directory

### ISSUE THREAD

**Issue by Gnefi** [tensorflow/magenta#1278]
Hi everyone!

I run my program (using MusicVAE model) but I had the same problem and I can't fix it.
Can you help please? I don't understand where is the problem: the program cannot find the file in directory (before the command line 16, I run this commands --> )

items = listdir(dir_dataset)
for midi in items:
    if midi.endswith(".mid"):
        proto_convert = midi_io.midi_file_to_sequence_proto(midi)
        notesequence.append(proto_convert)

Thank you for your help! :) 

Traceback (most recent call last):
  File "provamusic.py", line 16, in <module>
    proto_convert = midi_io.midi_file_to_sequence_proto(midi)
  File "/home/sophy0295/.conda/envs/magenta/lib/python2.7/site-packages/magenta/music/midi_io.py", line 308, in midi_file_to_sequence_proto
    midi_as_string = f.read()
  File "/home/sophy0295/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 120, in read
    self._preread_check()
  File "/home/sophy0295/.local/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 80, in _preread_check
    compat.as_bytes(self.__name), 1024 * 512, status)
  File "/home/sophy0295/.local/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 516, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Stereo_Madness-_Geometry_Dash-_Virtuoso_Version_Updated.mid; No such file or directory

**Comment by adarob** [comment]
It looks like listdir doesn't return the full path, only the filename. You'll need to do `os.path.join(dir_dataset, midi)` to get the full path.
