### ISSUE TITLE
Can't extract frames for pix2pix training.

### ISSUE THREAD

**Issue by ailgun** [tensorflow/magenta#1296]
When I run the script file it fails to extract frames and it doesn't actually start the training. 
I simply couldn't solve this problem;
Traceback (most recent call last):
```
  File "./magenta/video/tools/extract_frames.py", line 172, in <module>
    main(0)
  File "./magenta/video/tools/extract_frames.py", line 135, in main
    data = skvideo.io.ffprobe(video_filename)['video']
KeyError: 'video'
```

**To begin the training, I first go to the folder;**
cd /Users/MY_PATH/Desktop/tensorflow/magenta-master

**Then run the script;**
```
bazel run //magenta/video/next_frame_prediction_pix2pix:create_video  \
  /Users/MY_PATH/Desktop/tensorflow/magenta-master/magenta/video/next_frame_prediction_pix2pix/working_folder/  \
  20  \
  500 \
  /Users/MY_PATH/Desktop/tensorflow/magenta-master/magenta/video/next_frame_prediction_pix2pix/output_folder/
```

My 'working_folder' contains the mp4 file as well.

What I might be doing wrong? 

Thanks very much!

**Comment by adarob** [comment]
@dh7

**Comment by ailgun** [comment]
> @dh7

Thanks Adam, it was just that I double checked everything and as far as I see it just should work. 

If perhaps someone who could manage to run this could share the files/folder structure frame_extraction.py creates I can manually create it as well.

Thanks for the fantastic addition to the magenta collection by the way!

**Comment by dh7** [comment]
Hi Ailgun.

Your video need to be named video.mp4. An other name won't work for now.

About file structure, the script is just extracting frames as jpg image, but stretch them so they are square.

**Comment by dh7** [comment]
instead of:

mynames-iMac:magenta-master myname$ bazel run //magenta/video/next_frame_prediction_pix2pix:create_video  \
>   /Users/myname/Desktop/ml/tensorflow/magenta-master/magenta/video/next_frame_prediction_pix2pix/working_folder  \
>   20  \
>   500 \
>   /Users/myname/Desktop/ml/tensorflow/magenta-master/magenta/video/next_frame_prediction_

can you try:
//magenta/video/next_frame_prediction_pix2pix:create_video  \
   /Users/myname/Desktop/my_project/working_folder  \
   20  \
   500 \
  Users/myname/Desktop/my_project/backup_folder

and be sure you have a video.mp4 there:
/Users/myname/Desktop/my_project/working_folder

**Comment by ailgun** [comment]
Thanks very much for the reply Damien, even though this seems very well constructed and easy to execute its seems I'm a bit unlucky about it. It's just that I've been wanting to try this for a long time!

I have tried it as you said, first I went to folder with cd then ran the bazel but still I got the same error.
My video.mp4 is inside the 'working_folder' as well.

```
cd /Users/myname/Desktop/ml/tensorflow/magenta-master

bazel run //magenta/video/next_frame_prediction_pix2pix:create_video  \
  /Users/myname/Desktop/my_project/working_folder  \
  20  \
  500 \
  /Users/myname/Desktop/my_project/backup_folder
```
This is the execution:

```
Last login: Wed Dec  5 22:25:14 on ttys000
cd /Users/myname/Desktop/ml/tensorflow/magenta-master
mynames-iMac:~ myname$ cd /Users/myname/Desktop/ml/tensorflow/magenta-master
mynames-iMac:magenta-master myname$ 
mynames-iMac:magenta-master myname$ bazel run //magenta/video/next_frame_prediction_pix2pix:create_video  \
>   /Users/myname/Desktop/my_project/working_folder  \
>   20  \
>   500 \
>   /Users/myname/Desktop/my_project/backup_folder
INFO: Analysed target //magenta/video/next_frame_prediction_pix2pix:create_video (0 packages loaded).
INFO: Found 1 target...
Target //magenta/video/next_frame_prediction_pix2pix:create_video up-to-date:
  bazel-bin/magenta/video/next_frame_prediction_pix2pix/create_video
INFO: Elapsed time: 0.120s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/magenta/video/next_frame_prediction_pix2pix/create_video /Users/myname/Desktop/my_project/working_folder 20 500 /Users/myname/INFO: Build completed successfully, 1 total action
Train a model and make videos, including steps that generate pre recursive pairs
This script need to be launched from the main tf_toolbox directory, not from the directory witch the script is
!!! This script contains some rm -rf !!! use with care, check arg1 carfully
Train pix2pix to predict the next frame
Do you want to generate the frames from video.mp4? [y/N] y
creating the 'frames' dir
rm: /Users/myname/Desktop/my_project/working_folder/frames/*.jpg: No such file or directory
argument to expand /Users/myname/Desktop/my_project/working_folder/video.mp4
argument expanded ['/Users/myname/Desktop/my_project/working_folder/video.mp4']
start parsing /Users/myname/Desktop/my_project/working_folder/video.mp4
Traceback (most recent call last):
  File "./magenta/video/tools/extract_frames.py", line 173, in <module>
    main(0)
  File "./magenta/video/tools/extract_frames.py", line 136, in main
    data = skvideo.io.ffprobe(video_filename)['video']
KeyError: 'video'
Do you want to reset the first-frame using a frame from the video? [y/N] 

```


Later on, I manually created the 'frames' folder inside the working_directory, with ~100 RGB 1024x1024 .jpg files inside.

Then this is what happened later on, sorry for the extensive script.

```
Train a model and make videos, including steps that generate pre recursive pairs
This script need to be launched from the main tf_toolbox directory, not from the directory witch the script is
!!! This script contains some rm -rf !!! use with care, check arg1 carfully
Train pix2pix to predict the next frame
Do you want to generate the frames from video.mp4? [y/N] n
keeping 'frames' folder
Do you want to reset the first-frame using a frame from the video? [y/N] y
copying the test frame
cp: /Users/myname/Desktop/my_project/working_folder/frames/f0000001.jpg: No such file or directory
Do you want to generate the 'good' directory? just by copying the frame folder [y/N] y
creating the 'good' dir copying the frame folder
Do you want to (re)create 'train' [y/N] y
recreate 'train'
Do you want to remove or recreate the previous logs (to clean tensorboard)? [y/N] y
removing logs
Do you want to remove the previous generated video? [y/N] y
removing video
rm: /Users/myname/Desktop/my_project/backup_folder/video*.mp4: No such file or directory
Do you want to remove the CURENT model? [y/N] y
removing model checkpoint
rm: /Users/myname/Desktop/my_project/working_folder/pix2pix.model*: No such file or directory
rm: /Users/myname/Desktop/my_project/working_folder/checkpoint: No such file or directory
Do you want to (re)create 'test' and 'val'? [y/N] y
recreate 'test'
rm: /Users/myname/Desktop/my_project/working_folder/test/*.jpg: No such file or directory
looking for recursive img in /Users/myname/Desktop/my_project/working_folder/frames/*.jpg
found  100 for left list
looking for frames img in /Users/myname/Desktop/my_project/working_folder/good/*.jpg
found  100 for right list
Traceback (most recent call last):
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 123, in <module>
    main(0)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 99, in main
    match, i = is_match(left, r_list)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 71, in is_match
    frame_number = int(basename.split('.')[0][1:])
ValueError: invalid literal for int() with base 10: ''
recreate 'val'
rm: /Users/myname/Desktop/my_project/working_folder/val/*.jpg: No such file or directory
looking for recursive img in /Users/myname/Desktop/my_project/working_folder/frames/*.jpg
found  100 for left list
looking for frames img in /Users/myname/Desktop/my_project/working_folder/good/*.jpg
found  100 for right list
Traceback (most recent call last):
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 123, in <module>
    main(0)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 99, in main
    match, i = is_match(left, r_list)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 71, in is_match
    frame_number = int(basename.split('.')[0][1:])
ValueError: invalid literal for int() with base 10: ''
#######################################
starting sequence from 1 to 20
making pairs 1/20
looking for recursive img in /Users/myname/Desktop/my_project/working_folder/frames/*.jpg
found  100 for left list
looking for frames img in /Users/myname/Desktop/my_project/working_folder/good/*.jpg
found  100 for right list
Traceback (most recent call last):
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 123, in <module>
    main(0)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 99, in main
    match, i = is_match(left, r_list)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 71, in is_match
    frame_number = int(basename.split('.')[0][1:])
ValueError: invalid literal for int() with base 10: ''
trainning 1/20
2018-12-05 22:26:15.610410: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
 [*] Reading checkpoint...
 [!] Load failed...
looking for trainning data in /Users/myname/Desktop/my_project/working_folder/train/*.jpg
found 0 data
looking for trainning data in /Users/myname/Desktop/my_project/working_folder/train/*.jpg
found 0 data
looking for trainning data in /Users/myname/Desktop/my_project/working_folder/train/*.jpg
found 0 data
looking for trainning data in /Users/myname/Desktop/my_project/working_folder/train/*.jpg
found 0 data
looking for trainning data in /Users/myname/Desktop/my_project/working_folder/train/*.jpg
found 0 data
cleaning logs
backup model 1
cp: /Users/myname/Desktop/my_project/working_folder/checkpoint: No such file or directory
cp: /Users/myname/Desktop/my_project/working_folder/pix2pix.model*: No such file or directory
generate video test 1
2018-12-05 22:26:35.466466: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
WARNING:tensorflow:From /Users/myname/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:118: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
 [*] Reading checkpoint...
 [!] Load failed...
('sampling image for recursion', 1, '/Users/myname/Desktop/my_project/working_folder/img/first.jpg')
Loading one image ...
Traceback (most recent call last):
  File "./external/pix2pix_tensorflow/main.py", line 75, in <module>
    tf.app.run()
  File "/Users/myname/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./external/pix2pix_tensorflow/main.py", line 67, in main
    model.recursion(args)
  File "/private/var/tmp/_bazel_myname/45335007f54935be7f3218e2298a1b20/external/pix2pix_tensorflow/model.py", line 489, in recursion
    sample = [load_data(sample_file, is_test=True, is_one=True) for sample_file in sample_files]
  File "/private/var/tmp/_bazel_myname/45335007f54935be7f3218e2298a1b20/external/pix2pix_tensorflow/utils.py", line 21, in load_data
    img_A, img_B = load_image(image_path, is_one)
  File "/private/var/tmp/_bazel_myname/45335007f54935be7f3218e2298a1b20/external/pix2pix_tensorflow/utils.py", line 32, in load_image
    input_img = imread(image_path)
  File "/private/var/tmp/_bazel_myname/45335007f54935be7f3218e2298a1b20/external/pix2pix_tensorflow/utils.py", line 73, in imread
    return scipy.misc.imread(path).astype(np.float)
  File "/Users/myname/anaconda2/lib/python2.7/site-packages/numpy/lib/utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "/Users/myname/anaconda2/lib/python2.7/site-packages/scipy/misc/pilutil.py", line 164, in imread
    im = Image.open(name)
  File "/Users/myname/anaconda2/lib/python2.7/site-packages/PIL/Image.py", line 2580, in open
    fp = builtins.open(filename, "rb")
IOError: [Errno 2] No such file or directory: '/Users/myname/Desktop/my_project/working_folder/img/first.jpg'
looking for all files in /Users/myname/Desktop/my_project/backup_folder/model_001/*
found  0 files
dyld: Library not loaded: @rpath/libiconv.2.dylib
  Referenced from: /Users/myname/anaconda3/bin/ffmpeg
  Reason: Incompatible library version: ffmpeg requires version 8.0.0 or later, but libiconv.2.dylib provides version 7.0.0
./magenta/video/next_frame_prediction_pix2pix/recursion_640.sh: line 22:  1303 Abort trap: 6           ffmpeg -i $4/%04d.jpg -vcodec libx264 $4.mp4
select some pairs for recursion
looking for all files in /Users/myname/Desktop/my_project/working_folder/good/*
found  100 files
will use limit of 100 files
1 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/46.jpg to /Users/myname/Desktop/my_project/working_folder/recur/46.jpg
2 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/28.jpg to /Users/myname/Desktop/my_project/working_folder/recur/28.jpg
3 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/26.jpg to /Users/myname/Desktop/my_project/working_folder/recur/26.jpg
4 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/72.jpg to /Users/myname/Desktop/my_project/working_folder/recur/72.jpg
5 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/100.jpg to /Users/myname/Desktop/my_project/working_folder/recur/100.jpg
6 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/65.jpg to /Users/myname/Desktop/my_project/working_folder/recur/65.jpg
7 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/67.jpg to /Users/myname/Desktop/my_project/working_folder/recur/67.jpg
8 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/71.jpg to /Users/myname/Desktop/my_project/working_folder/recur/71.jpg
9 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/10.jpg to /Users/myname/Desktop/my_project/working_folder/recur/10.jpg
10 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/4.jpg to /Users/myname/Desktop/my_project/working_folder/recur/4.jpg
11 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/18.jpg to /Users/myname/Desktop/my_project/working_folder/recur/18.jpg
12 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/90.jpg to /Users/myname/Desktop/my_project/working_folder/recur/90.jpg
13 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/82.jpg to /Users/myname/Desktop/my_project/working_folder/recur/82.jpg
14 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/32.jpg to /Users/myname/Desktop/my_project/working_folder/recur/32.jpg
15 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/74.jpg to /Users/myname/Desktop/my_project/working_folder/recur/74.jpg
16 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/48.jpg to /Users/myname/Desktop/my_project/working_folder/recur/48.jpg
17 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/45.jpg to /Users/myname/Desktop/my_project/working_folder/recur/45.jpg
18 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/60.jpg to /Users/myname/Desktop/my_project/working_folder/recur/60.jpg
19 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/58.jpg to /Users/myname/Desktop/my_project/working_folder/recur/58.jpg
20 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/15.jpg to /Users/myname/Desktop/my_project/working_folder/recur/15.jpg
21 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/55.jpg to /Users/myname/Desktop/my_project/working_folder/recur/55.jpg
22 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/87.jpg to /Users/myname/Desktop/my_project/working_folder/recur/87.jpg
23 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/13.jpg to /Users/myname/Desktop/my_project/working_folder/recur/13.jpg
24 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/61.jpg to /Users/myname/Desktop/my_project/working_folder/recur/61.jpg
25 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/47.jpg to /Users/myname/Desktop/my_project/working_folder/recur/47.jpg
26 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/98.jpg to /Users/myname/Desktop/my_project/working_folder/recur/98.jpg
27 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/54.jpg to /Users/myname/Desktop/my_project/working_folder/recur/54.jpg
28 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/16.jpg to /Users/myname/Desktop/my_project/working_folder/recur/16.jpg
29 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/51.jpg to /Users/myname/Desktop/my_project/working_folder/recur/51.jpg
30 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/49.jpg to /Users/myname/Desktop/my_project/working_folder/recur/49.jpg
31 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/19.jpg to /Users/myname/Desktop/my_project/working_folder/recur/19.jpg
32 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/40.jpg to /Users/myname/Desktop/my_project/working_folder/recur/40.jpg
33 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/42.jpg to /Users/myname/Desktop/my_project/working_folder/recur/42.jpg
34 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/70.jpg to /Users/myname/Desktop/my_project/working_folder/recur/70.jpg
35 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/44.jpg to /Users/myname/Desktop/my_project/working_folder/recur/44.jpg
36 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/31.jpg to /Users/myname/Desktop/my_project/working_folder/recur/31.jpg
37 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/68.jpg to /Users/myname/Desktop/my_project/working_folder/recur/68.jpg
38 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/59.jpg to /Users/myname/Desktop/my_project/working_folder/recur/59.jpg
39 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/64.jpg to /Users/myname/Desktop/my_project/working_folder/recur/64.jpg
40 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/95.jpg to /Users/myname/Desktop/my_project/working_folder/recur/95.jpg
41 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/23.jpg to /Users/myname/Desktop/my_project/working_folder/recur/23.jpg
42 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/50.jpg to /Users/myname/Desktop/my_project/working_folder/recur/50.jpg
43 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/41.jpg to /Users/myname/Desktop/my_project/working_folder/recur/41.jpg
44 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/89.jpg to /Users/myname/Desktop/my_project/working_folder/recur/89.jpg
45 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/21.jpg to /Users/myname/Desktop/my_project/working_folder/recur/21.jpg
46 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/11.jpg to /Users/myname/Desktop/my_project/working_folder/recur/11.jpg
47 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/69.jpg to /Users/myname/Desktop/my_project/working_folder/recur/69.jpg
48 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/38.jpg to /Users/myname/Desktop/my_project/working_folder/recur/38.jpg
49 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/5.jpg to /Users/myname/Desktop/my_project/working_folder/recur/5.jpg
50 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/6.jpg to /Users/myname/Desktop/my_project/working_folder/recur/6.jpg
51 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/62.jpg to /Users/myname/Desktop/my_project/working_folder/recur/62.jpg
52 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/2.jpg to /Users/myname/Desktop/my_project/working_folder/recur/2.jpg
53 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/99.jpg to /Users/myname/Desktop/my_project/working_folder/recur/99.jpg
54 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/12.jpg to /Users/myname/Desktop/my_project/working_folder/recur/12.jpg
55 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/92.jpg to /Users/myname/Desktop/my_project/working_folder/recur/92.jpg
56 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/24.jpg to /Users/myname/Desktop/my_project/working_folder/recur/24.jpg
57 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/25.jpg to /Users/myname/Desktop/my_project/working_folder/recur/25.jpg
58 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/96.jpg to /Users/myname/Desktop/my_project/working_folder/recur/96.jpg
59 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/94.jpg to /Users/myname/Desktop/my_project/working_folder/recur/94.jpg
60 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/30.jpg to /Users/myname/Desktop/my_project/working_folder/recur/30.jpg
61 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/83.jpg to /Users/myname/Desktop/my_project/working_folder/recur/83.jpg
62 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/20.jpg to /Users/myname/Desktop/my_project/working_folder/recur/20.jpg
63 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/34.jpg to /Users/myname/Desktop/my_project/working_folder/recur/34.jpg
64 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/81.jpg to /Users/myname/Desktop/my_project/working_folder/recur/81.jpg
65 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/35.jpg to /Users/myname/Desktop/my_project/working_folder/recur/35.jpg
66 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/86.jpg to /Users/myname/Desktop/my_project/working_folder/recur/86.jpg
67 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/91.jpg to /Users/myname/Desktop/my_project/working_folder/recur/91.jpg
68 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/93.jpg to /Users/myname/Desktop/my_project/working_folder/recur/93.jpg
69 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/52.jpg to /Users/myname/Desktop/my_project/working_folder/recur/52.jpg
70 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/56.jpg to /Users/myname/Desktop/my_project/working_folder/recur/56.jpg
71 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/66.jpg to /Users/myname/Desktop/my_project/working_folder/recur/66.jpg
72 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/43.jpg to /Users/myname/Desktop/my_project/working_folder/recur/43.jpg
73 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/1.jpg to /Users/myname/Desktop/my_project/working_folder/recur/1.jpg
74 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/27.jpg to /Users/myname/Desktop/my_project/working_folder/recur/27.jpg
75 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/29.jpg to /Users/myname/Desktop/my_project/working_folder/recur/29.jpg
76 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/85.jpg to /Users/myname/Desktop/my_project/working_folder/recur/85.jpg
77 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/63.jpg to /Users/myname/Desktop/my_project/working_folder/recur/63.jpg
78 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/7.jpg to /Users/myname/Desktop/my_project/working_folder/recur/7.jpg
79 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/9.jpg to /Users/myname/Desktop/my_project/working_folder/recur/9.jpg
80 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/76.jpg to /Users/myname/Desktop/my_project/working_folder/recur/76.jpg
81 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/73.jpg to /Users/myname/Desktop/my_project/working_folder/recur/73.jpg
82 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/37.jpg to /Users/myname/Desktop/my_project/working_folder/recur/37.jpg
83 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/97.jpg to /Users/myname/Desktop/my_project/working_folder/recur/97.jpg
84 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/75.jpg to /Users/myname/Desktop/my_project/working_folder/recur/75.jpg
85 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/3.jpg to /Users/myname/Desktop/my_project/working_folder/recur/3.jpg
86 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/17.jpg to /Users/myname/Desktop/my_project/working_folder/recur/17.jpg
87 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/88.jpg to /Users/myname/Desktop/my_project/working_folder/recur/88.jpg
88 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/57.jpg to /Users/myname/Desktop/my_project/working_folder/recur/57.jpg
89 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/79.jpg to /Users/myname/Desktop/my_project/working_folder/recur/79.jpg
90 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/77.jpg to /Users/myname/Desktop/my_project/working_folder/recur/77.jpg
91 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/8.jpg to /Users/myname/Desktop/my_project/working_folder/recur/8.jpg
92 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/78.jpg to /Users/myname/Desktop/my_project/working_folder/recur/78.jpg
93 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/53.jpg to /Users/myname/Desktop/my_project/working_folder/recur/53.jpg
94 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/33.jpg to /Users/myname/Desktop/my_project/working_folder/recur/33.jpg
95 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/36.jpg to /Users/myname/Desktop/my_project/working_folder/recur/36.jpg
96 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/39.jpg to /Users/myname/Desktop/my_project/working_folder/recur/39.jpg
97 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/84.jpg to /Users/myname/Desktop/my_project/working_folder/recur/84.jpg
98 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/22.jpg to /Users/myname/Desktop/my_project/working_folder/recur/22.jpg
99 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/80.jpg to /Users/myname/Desktop/my_project/working_folder/recur/80.jpg
100 / 100   copying /Users/myname/Desktop/my_project/working_folder/good/14.jpg to /Users/myname/Desktop/my_project/working_folder/recur/14.jpg
use pre-recursion
2018-12-05 22:26:38.979707: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
pre recursion
WARNING:tensorflow:From /Users/myname/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:118: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
 [*] Reading checkpoint...
 [!] Load failed...
look for files in /Users/myname/Desktop/my_project/working_folder/recur/*.jpg
look for files in /Users/myname/Desktop/my_project/working_folder/frames/*.jpg
Traceback (most recent call last):
  File "./external/pix2pix_tensorflow/main.py", line 75, in <module>
    tf.app.run()
  File "/Users/myname/anaconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "./external/pix2pix_tensorflow/main.py", line 70, in main
    model.pre_recursion(args)
  File "/private/var/tmp/_bazel_myname/45335007f54935be7f3218e2298a1b20/external/pix2pix_tensorflow/model.py", line 544, in pre_recursion
    match, frame_number = self.find_frame(filename, args.recursion, frames_files)
  File "/private/var/tmp/_bazel_myname/45335007f54935be7f3218e2298a1b20/external/pix2pix_tensorflow/model.py", line 517, in find_frame
    frame_number = int(basename.split('.')[0][1:])
ValueError: invalid literal for int() with base 10: ''
generate pairs from recursion
looking for recursive img in /Users/myname/Desktop/my_project/working_folder/recur/*.jpg
found  100 for left list
looking for frames img in /Users/myname/Desktop/my_project/working_folder/good/*.jpg
found  100 for right list
Traceback (most recent call last):
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 123, in <module>
    main(0)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 99, in main
    match, i = is_match(left, r_list)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 71, in is_match
    frame_number = int(basename.split('.')[0][1:])
ValueError: invalid literal for int() with base 10: ''
select some pairs for recursion (long)
looking for all files in /Users/myname/Desktop/my_project/working_folder/good/*
found  100 files
will use limit of 2 files
1 / 2   copying /Users/myname/Desktop/my_project/working_folder/good/65.jpg to /Users/myname/Desktop/my_project/working_folder/recur/65.jpg
2 / 2   copying /Users/myname/Desktop/my_project/working_folder/good/19.jpg to /Users/myname/Desktop/my_project/working_folder/recur/19.jpg
use pre-recursion (long)
2018-12-05 22:26:42.492129: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
pre recursion
WARNING:tensorflow:From /Users/myname/anaconda2/lib/python2.7/site-packages/tensorflow/python/util/tf_should_use.py:118: initialize_all_variables (from tensorflow.python.ops.variables) is deprecated and will be removed after 2017-03-02.
Instructions for updating:
Use `tf.global_variables_initializer` instead.
 [*] Reading checkpoint...
 [!] Load failed...
look for files in /Users/myname/Desktop/my_project/working_folder/recur/*.jpg
look for files in /Users/myname/Desktop/my_project/working_folder/frames/*.jpg
generate pairs from recursion (long)
looking for recursive img in /Users/myname/Desktop/my_project/working_folder/recur/*.jpg
found  2 for left list
looking for frames img in /Users/myname/Desktop/my_project/working_folder/good/*.jpg
found  100 for right list
making pairs 2/20
looking for recursive img in /Users/myname/Desktop/my_project/working_folder/frames/*.jpg
found  100 for left list
looking for frames img in /Users/myname/Desktop/my_project/working_folder/good/*.jpg
found  100 for right list
Traceback (most recent call last):
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 123, in <module>
    main(0)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 99, in main
    match, i = is_match(left, r_list)
  File "./magenta/video/next_frame_prediction_pix2pix/join_pairs.py", line 71, in is_match
    frame_number = int(basename.split('.')[0][1:])
ValueError: invalid literal for int() with base 10: ''
trainning 2/20
```
