### ISSUE TITLE
Outdated checkpoint nsynth/wavenet

### ISSUE THREAD

**Issue by dubreuia** [tensorflow/magenta#1315]
I'm trying to generate a sound with nsynth (follwing the doc https://github.com/tensorflow/magenta/tree/master/magenta/models/nsynth) with

```bash
nsynth_generate --checkpoint_path=checkpoints/wavenet-ckpt/wavenet-ckpt/model.ckpt-200000.index --source_path=wav --save_path=output/nsynth/wavenet --batch_size=4
```

But I get the error

```
  File "[...]/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Tensor name "ae_bottleneck/W" not found in checkpoint files [...]/checkpoints/wavenet-ckpt/wavenet-ckpt/model.ckpt-200000.index
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

Is it possible that the checkpoints are outdated? Or am I doing something wrong? Thanks

**Comment by jesseengel** [comment]
Hi, I think you want to use the name `model.ckpt-200000` without the .index as we do in the colab notebook: https://colab.research.google.com/notebooks/magenta/nsynth/nsynth.ipynb

**Comment by ktfth** [comment]
Following the above instruction try to utilize all the path to the file because of the absolute unpresent access to the descriptor.

**Comment by robo360** [comment]
I have the same problem.

**Comment by friendlyvisuals** [comment]
same issue. Any solution?

**Comment by jesseengel** [comment]
This problem was fixed (as in the colab notebook) by using `--checkpoint_path=path/to/model.ckpt-200000` without the `.index`, does that help?

**Comment by abriosi** [comment]
Hi @jesseengel

Where can we obtain the `model.ckpt-200000`?

I used the link http://download.magenta.tensorflow.org/models/nsynth/wavenet-ckpt.tar and these is the content of that .tar:

```
-rw-r----- 1 ubuntu ubuntu 986763532 Apr  3  2017 model.ckpt-200000.data-00000-of-00001
-rw-r----- 1 ubuntu ubuntu     63671 Apr  3  2017 model.ckpt-200000.index
-rw-r----- 1 ubuntu ubuntu   7060787 Apr  3  2017 model.ckpt-200000.meta
``` 

<img width="838" alt="image" src="https://github.com/magenta/magenta/assets/23288462/77e8906c-8718-4fa5-aee5-974d102049a6">

**Comment by abriosi** [comment]
I tried converting it using `tensorflow==1.15.0`and the script:

```
import tensorflow_text
import tensorflow as tf

tf.compat.v1.disable_eager_execution()

# Now the rest of your code
saver = tf.compat.v1.train.import_meta_graph('model.ckpt-200000.meta')

# Restore the weights
saver.restore(sess, 'model.ckpt-200000')
```

I can't go over this error:

```
Traceback (most recent call last):
  File "converter.py", line 9, in <module>
    saver = tf.compat.v1.train.import_meta_graph('model.ckpt-200000.meta')
  File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
    **kwargs)[0]
  File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
    **kwargs))
  File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
    return_elements=return_elements)
  File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
    producer_op_list=producer_op_list)
  File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
    graph._c_graph, serialized, options)  # pylint: disable=protected-access
tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SSTableReader' in binary running on locally. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
```

**Comment by abriosi** [comment]
> Hi @jesseengel
> 
> Where can we obtain the `model.ckpt-200000`?
> 
> I used the link http://download.magenta.tensorflow.org/models/nsynth/wavenet-ckpt.tar and these is the content of that .tar:
> 
> ```
> -rw-r----- 1 ubuntu ubuntu 986763532 Apr  3  2017 model.ckpt-200000.data-00000-of-00001
> -rw-r----- 1 ubuntu ubuntu     63671 Apr  3  2017 model.ckpt-200000.index
> -rw-r----- 1 ubuntu ubuntu   7060787 Apr  3  2017 model.ckpt-200000.meta
> ```
> 
> <img alt="image" width="838" src="https://private-user-images.githubusercontent.com/23288462/306682803-77e8906c-8718-4fa5-aee5-974d102049a6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDg2ODk0MzEsIm5iZiI6MTcwODY4OTEzMSwicGF0aCI6Ii8yMzI4ODQ2Mi8zMDY2ODI4MDMtNzdlODkwNmMtODcxOC00ZmE1LWFlZTUtOTc0ZDEwMjA0OWE2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAyMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMjIzVDExNTIxMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWI5YTY1MzQyNzA5ZDdiNmJjY2EyOWFhNTllNmY4NTFjNWM1NDNkYjM2MzQ4ZTE3MWUxNWMwYjc3NjA2MGZhMGMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.2YQ8nl28x3RN9VfIG99kEcZeS30slfa2GZtJa2oABJI">



> I tried converting it using `tensorflow==1.15.0`and the script:
> 
> ```
> import tensorflow_text
> import tensorflow as tf
> 
> tf.compat.v1.disable_eager_execution()
> 
> # Now the rest of your code
> saver = tf.compat.v1.train.import_meta_graph('model.ckpt-200000.meta')
> 
> # Restore the weights
> saver.restore(sess, 'model.ckpt-200000')
> ```
> 
> I can't go over this error:
> 
> ```
> Traceback (most recent call last):
>   File "converter.py", line 9, in <module>
>     saver = tf.compat.v1.train.import_meta_graph('model.ckpt-200000.meta')
>   File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1453, in import_meta_graph
>     **kwargs)[0]
>   File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/training/saver.py", line 1477, in _import_meta_graph_with_return_elements
>     **kwargs))
>   File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/framework/meta_graph.py", line 809, in import_scoped_meta_graph_with_return_elements
>     return_elements=return_elements)
>   File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/util/deprecation.py", line 507, in new_func
>     return func(*args, **kwargs)
>   File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 405, in import_graph_def
>     producer_op_list=producer_op_list)
>   File "/home/ubuntu/vertate-nsynth/virtual-trans/lib/python3.7/site-packages/tensorflow_core/python/framework/importer.py", line 501, in _import_graph_def_internal
>     graph._c_graph, serialized, options)  # pylint: disable=protected-access
> tensorflow.python.framework.errors_impl.NotFoundError: Op type not registered 'SSTableReader' in binary running on locally. Make sure the Op and Kernel are registered in the binary running in this process. Note that if you are loading a saved graph which used ops from tf.contrib, accessing (e.g.) `tf.contrib.resampler` should be done before importing the graph, as contrib ops are lazily registered when the module is first accessed.
> ```

@cghawthorne @adarob @iansimon Can you give my some pointers on how to get a working checkpoint for `wavenet-ckpt.tar`?
