### ISSUE TITLE
AttributeError: 'module' object has no attribute 'slim'

### ISSUE THREAD

**Issue by nekomehako** [tensorflow/magenta#1317]
I am trying nsynth・training but I get an error
```
＄bazel run //magenta/models/nsynth/baseline:train -- --train_path=//home/nekome/tffile.tfrecords ---logdir=//home/nekome/Logdire
WARNING: Processed legacy workspace file /home/nekome/magenta/tools/bazel.rc. This file will not be processed in the next release of Bazel. Please read https://github.com/bazelbuild/bazel/issues/6319 for further information, including how to upgrade.
INFO: Analysed target //magenta/models/nsynth/baseline:train (0 packages loaded).
INFO: Found 1 target...
Target //magenta/models/nsynth/baseline:train up-to-date:
  bazel-bin/magenta/models/nsynth/baseline/train
INFO: Elapsed time: 0.059s, Critical Path: 0.00s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Running command line: bazel-bin/magenta/models/nsynth/baseline/train '--trINFO: Build completed successfully, 1 total action
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:99] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: 
I tensorflow/stream_executor/cuda/cuda_dnn.cc:1407] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:105] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/home/nekome/.cache/bazel/_bazel_root/8d760b4887a3a97dbc093bfa28201502/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/baseline/train.runfiles/__main__/magenta/models/nsynth/baseline/train.py", line 23, in <module>
    from magenta.models.nsynth import reader
  File "/home/nekome/.cache/bazel/_bazel_root/8d760b4887a3a97dbc093bfa28201502/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/baseline/train.runfiles/__main__/magenta/models/nsynth/reader.py", line 24, in <module>
    from magenta.models.nsynth import utils
  File "/home/nekome/.cache/bazel/_bazel_root/8d760b4887a3a97dbc093bfa28201502/execroot/__main__/bazel-out/k8-opt/bin/magenta/models/nsynth/baseline/train.runfiles/__main__/magenta/models/nsynth/utils.py", line 29, in <module>
    slim = tf.contrib.slim
AttributeError: 'module' object has no attribute 'slim'

```
How can I solve it?
Please give me a suggestion

**Comment by ktfth** [comment]
* Try to compile a version of tensorflow on your machine to accompain those kind of changes of API access.
* Freeze a version with that method present on the contrib module

**Comment by ktfth** [comment]
https://github.com/tensorflow/tensorflow/blob/master/RELEASE.md
