### ISSUE TITLE
magenta-gpu  gives  No module named linalg.python.ops on music_vae_train

### ISSUE THREAD

**Issue by AndreyShagal** [tensorflow/magenta#1350]
Trying to run music_vae_train  on google cloud, Debian + python 2.7 with installed magenta-gpu
but got the following. Could you please help? 

root@tensorflow-1-vm:/home/andrey_shagal# music_vae_train --config=hier-multiperf_vel_1bar_med  --run_dir=/home/a
ndrey_shagal/train/  --num_steps=500 --checkpoints_to_keep=2 --hparams=batch_size=32,learning_rate=0.0005 --mode=
train --examples_path=notesequences_BM_Midi.tfrecord
Traceback (most recent call last):
  File "/usr/local/bin/music_vae_train", line 7, in <module>
    from magenta.models.music_vae.music_vae_train import console_entry_point
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/music_vae/__init__.py", line 20, in <module>
    from .base_model import BaseDecoder
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/music_vae/base_model.py", line 23, in <module>
    import tensorflow_probability as tfp
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/__init__.py", line 21, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/distributions/__init__.py", line 77,
 in <module>
    from tensorflow_probability.python.distributions.vector_diffeomixture import quadrature_scheme_softmaxnormal_
gauss_hermite
  File "/usr/local/lib/python2.7/dist-packages/tensorflow_probability/python/distributions/vector_diffeomixture.p
y", line 28, in <module>
    from tensorflow.contrib.linalg.python.ops import linear_operator_addition as linop_add_lib
ImportError: No module named linalg.python.ops
root@tensorflow-1-vm:/home/andrey_shagal#

**Comment by AndreyShagal** [comment]
Could be fixed with:
https://github.com/tensorflow/probability/issues/215

So,
from tensorflow.contrib.linalg.python.ops import linear_operator_addition as linop_add_lib
in /tensorflow_probability/python/distributions/vector_diffeomixture.py
should be changed to
from tensorflow.python.ops.linalg import linear_operator_addition as linop_add_lib

**Comment by adarob** [comment]
@AndreyShagal I bumped the tf and tfp versions in 0.3.15. Please give it a try and reopen if there is still an issue. Thanks!

**Comment by osfa** [comment]
running 0.3.18 and I still get this error when running melody_rnn_train

**Comment by osfa** [comment]
can be resolved by pip install tensorflow-probability-gpu==0.5.0rc0

**Comment by adarob** [comment]
This should now be fixed in 0.3.19. Sorry about the trouble!
