### ISSUE TITLE
MusicVAE: DataLossError - could not load checkpoint

### ISSUE THREAD

**Issue by JoeThanks67** [tensorflow/magenta#1376]
I trained the _hierdec-trio_16bar_ model for testing purposes. My parameters are accordingly not suitable for productive operation.

_/magenta/models/music_vae/configs.py:_

```
HParams(
  batch_size=1,
  max_seq_len=256,
  z_size=64,
  enc_rnn_size=[256, 256],
  dec_rnn_size=[128, 128],
  free_bits=256,
  max_beta=0.2,
)
```

```
music_vae_train 
--config=hierdec-trio_16bar 
--num_steps=200 
--run_dir=/magenta-data/tmp 
--mode=train 
--examples_path=/magenta-data/note-sequences/rock-2-notesequences.tfrecord

INFO:tensorflow:Reading examples from:
/magenta-data/note-sequences/rock-2-notesequences.tfrecord
2018-12-07 09:40:35.998483: I tensorflow/core/platform/cpu_feature_guard.cc:141] 
Your CPU supports instructions that this TensorFlow binary was not compiled to use:
AVX2 FMA
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, 
HierarchicalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 64, 'free_bits': 256, 'max_seq_len': 256, 
'residual_encoder': False, 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 
'conditional': True, 'use_cudnn': False, 'min_learning_rate': 1e-05, 
'sampling_schedule': 'constant', 'dec_rnn_size': [128, 128], 'residual_decoder': False, 
'decay_rate': 0.9999, 'beta_rate': 0.0, 'sampling_rate': 0.0, 'enc_rnn_size': [256, 256], 
'batch_size': 1, 'max_beta': 0.2, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [256, 256]

INFO:tensorflow:
Hierarchical Decoder:
  input length: 256
  level output lengths: [16, 16]

INFO:tensorflow:
Decoder Cells:
  units: [128, 128]

INFO:tensorflow:
Decoder Cells:
  units: [128, 128]

INFO:tensorflow:
Decoder Cells:
  units: [128, 128]

WARNING:tensorflow:From /root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/lstm_models.py:549: softmax_cross_entropy_with_logits 
(from tensorflow.python.ops.nn_ops) is deprecated and will be removed in a future version.
Instructions for updating:

Future major versions of TensorFlow will allow gradients to flow
into the labels input on backprop by default.

See `tf.nn.softmax_cross_entropy_with_logits_v2`.

INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Graph was finalized.
INFO:tensorflow:Running local_init_op.
INFO:tensorflow:Done running local_init_op.
INFO:tensorflow:Saving checkpoints for 0 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:global_step = 1, loss = 3900.9385
INFO:tensorflow:Saving checkpoints for 2 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 25 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 46 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 66 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 85 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:global_step/sec: 0.298032
INFO:tensorflow:global_step = 101, loss = 1583.1455 (335.541 sec)
INFO:tensorflow:Saving checkpoints for 105 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 125 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 144 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 160 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 174 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 189 into /magenta-data/tmp/train/model.ckpt.
INFO:tensorflow:Saving checkpoints for 200 into /magenta-data/tmp/train/model.ckpt.
```

Data and index are used as e.g. at the ready-made checkpoint trio_16bar_hierdec.ckpt.tar packed in a tar:

`tar -cf /magenta-data/tmp/train/rock-2.tar /magenta-data/tmp/train/model.ckpt-200.data-00000-of-00001 /magenta-data/tmp/train/model.ckpt-200.index`

But the checkpoint can not be loaded:

```
music_vae_generate 
--config=hierdec-trio_16bar 
--checkpoint_file=/magenta-data/tmp/train/rock-2.tar
--mode=sample 
--num_outputs=5 
--output_dir=/magenta-data/generated

INFO:tensorflow:Loading model...
INFO:tensorflow:Building MusicVAE model with BidirectionalLstmEncoder, HierarchicalLstmDecoder, and hparams:
{'grad_clip': 1.0, 'z_size': 64, 'decay_rate': 0.9999, 'dec_rnn_size': [128, 128], 'free_bits': 256, 'use_cudnn': False, 'residual_encoder': False, 'grad_norm_clip_to_zero': 10000, 'learning_rate': 0.001, 'conditional': True, 'batch_size': 5, 'min_learning_rate': 1e-05, 'sampling_schedule': 'constant', 'max_seq_len': 256, 'residual_decoder': False, 'beta_rate': 0.0, 'enc_rnn_size': [256, 256], 'sampling_rate': 0.0, 'max_beta': 0.2, 'dropout_keep_prob': 1.0, 'clip_mode': 'global_norm'}
INFO:tensorflow:
Encoder Cells (bidirectional):
  units: [256, 256]

INFO:tensorflow:
Hierarchical Decoder:
  input length: 256
  level output lengths: [16, 16]

INFO:tensorflow:
Decoder Cells:
  units: [128, 128]

INFO:tensorflow:
Decoder Cells:
  units: [128, 128]

INFO:tensorflow:
Decoder Cells:
  units: [128, 128]

2018-12-07 10:04:50.992086: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
INFO:tensorflow:Unbundling checkpoint.
INFO:tensorflow:Restoring parameters from /magenta-data/tmp/train/rock-2.tar
2018-12-07 10:04:51.691894: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /magenta-data/tmp/train/rock-2.tar: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2018-12-07 10:04:51.699053: W tensorflow/core/util/tensor_slice_reader.cc:95] Could not open /magenta-data/tmp/train/rock-2.tar: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
2018-12-07 10:04:51.700032: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_tensor.cc:172 : Data loss: Unable to open table file /magenta-data/tmp/train/rock-2.tar: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
Traceback (most recent call last):
  File "/root/miniconda2/envs/magenta/bin/music_vae_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_generate.py", line 190, in console_entry_point
    tf.app.run(main)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_generate.py", line 186, in main
    run(configs.CONFIG_MAP)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_generate.py", line 155, in run
    checkpoint_dir_or_path=checkpoint_dir_or_path)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/trained_model.py", line 128, in __init__
    saver.restore(self._sess, checkpoint_path)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1538, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 887, in run
    run_metadata_ptr)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1110, in _run
    feed_dict_tensor, options, run_metadata)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1286, in _do_run
    run_metadata)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1308, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.DataLossError: Unable to open table file /magenta-data/tmp/train/rock-2.tar: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op u'save/RestoreV2', defined at:
  File "/root/miniconda2/envs/magenta/bin/music_vae_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_generate.py", line 190, in console_entry_point
    tf.app.run(main)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_generate.py", line 186, in main
    run(configs.CONFIG_MAP)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/music_vae_generate.py", line 155, in run
    checkpoint_dir_or_path=checkpoint_dir_or_path)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/music_vae/trained_model.py", line 117, in __init__
    saver = tf.train.Saver(var_map)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1094, in __init__
    self.build()
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1106, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1143, in _build
    build_save=build_save, build_restore=build_restore)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 787, in _build_internal
    restore_sequentially, reshape)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 854, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 3272, in create_op
    op_def=op_def)
  File "/root/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1768, in __init__
    self._traceback = tf_stack.extract_stack()

DataLossError (see above for traceback): Unable to open table file /magenta-data/tmp/train/rock-2.tar: Data loss: not an sstable (bad magic number): perhaps your file is in a different file format and you need to use a different restore operator?
	 [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

**Comment by adarob** [comment]
@JoeThanks67 you shouldn't actually need to tar your checkpoint. You can either leave `--checkpoint_file` blank and set `--run_dir=/magenta-data/tmp` to use the latest checkpoint or set `--checkoint_file=/magenta-data/tmp/train/model.ckpt-200`. Please reopen if you still have issues.

**Comment by JoeThanks67** [comment]
OK. `--run_dir=/magenta-data/tmp` works if i rename the file _model.ckpt-200.data-00000-of-00001_ to _model.ckpt-200_. Thanks!
