### ISSUE TITLE
Error on initial test. 

### ISSUE THREAD

**Issue by kunimi00** [tensorflow/magenta#140]
Hi,
I'm having a problem running the initial test. 
(python 2.7.12 / tensorflow 0.9.0 / OSX 10.11.6)

Executing the following code from the instruction, 
bazel test //magenta/...

I get these error messages. : 

```
WARNING: /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 45 targets and 10 test targets...
FAIL: //magenta/lib:note_sequence_io_test (see /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log).
FAIL: //magenta/pipelines:pipeline_test (see /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipeline_test/test.log).
FAIL: //magenta/scripts:convert_midi_dir_to_note_sequences_test (see /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log).
INFO: Elapsed time: 1.181s, Critical Path: 0.76s
//magenta/lib:melodies_lib_test                                 (cached) PASSED in 1.1s
//magenta/lib:midi_io_test                                      (cached) PASSED in 2.1s
//magenta/lib:sequences_lib_test                                (cached) PASSED in 1.0s
//magenta/models/shared:melody_rnn_create_dataset_test          (cached) PASSED in 1.0s
//magenta/pipelines:dag_pipeline_test                           (cached) PASSED in 1.0s
//magenta/pipelines:pipelines_common_test                       (cached) PASSED in 1.0s
//magenta/pipelines:statistics_test                             (cached) PASSED in 1.0s
//magenta/lib:note_sequence_io_test                                      FAILED in 0.6s
  /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log
//magenta/pipelines:pipeline_test                                        FAILED in 0.7s
  /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipeline_test/test.log
//magenta/scripts:convert_midi_dir_to_note_sequences_test                FAILED in 0.8s
  /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log

Executed 3 out of 10 tests: 7 tests pass and 3 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

With the suggested option(--test_verbose_timeout_warnings), here are the error messages. 

bazel test //magenta/... --test_verbose_timeout_warnings

```
WARNING: /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/external/protobuf/WORKSPACE:1: Workspace name in /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/external/protobuf/WORKSPACE (@__main__) does not match the name given in the repository's definition (@protobuf); this will cause a build error in future versions.
INFO: Found 45 targets and 10 test targets...
FAIL: //magenta/lib:note_sequence_io_test (see /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log).
FAIL: //magenta/pipelines:pipeline_test (see /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipeline_test/test.log).
FAIL: //magenta/scripts:convert_midi_dir_to_note_sequences_test (see /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log).
INFO: Elapsed time: 1.193s, Critical Path: 0.74s
//magenta/lib:melodies_lib_test                                 (cached) PASSED in 1.1s
  WARNING: //magenta/lib:melodies_lib_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/lib:midi_io_test                                      (cached) PASSED in 2.1s
  WARNING: //magenta/lib:midi_io_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/lib:sequences_lib_test                                (cached) PASSED in 1.0s
  WARNING: //magenta/lib:sequences_lib_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/models/shared:melody_rnn_create_dataset_test          (cached) PASSED in 1.0s
  WARNING: //magenta/models/shared:melody_rnn_create_dataset_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/pipelines:dag_pipeline_test                           (cached) PASSED in 1.0s
  WARNING: //magenta/pipelines:dag_pipeline_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/pipelines:pipelines_common_test                       (cached) PASSED in 1.0s
  WARNING: //magenta/pipelines:pipelines_common_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/pipelines:statistics_test                             (cached) PASSED in 1.0s
  WARNING: //magenta/pipelines:statistics_test: Test execution time (0.0s excluding execution overhead) outside of range for MODERATE tests. Consider setting timeout="short" or size="small".
//magenta/lib:note_sequence_io_test                                      FAILED in 0.6s
  /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log
//magenta/pipelines:pipeline_test                                        FAILED in 0.7s
  /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipeline_test/test.log
//magenta/scripts:convert_midi_dir_to_note_sequences_test                FAILED in 0.7s
  /private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log

Executed 3 out of 10 tests: 7 tests pass and 3 fail locally.
```
And here are the 3 test.log files. 

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
.E.
======================================================================
ERROR: testNoteSequenceRecordWriterAndIterator (__main__.NoteSequenceIoTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/bin/magenta/lib/note_sequence_io_test.runfiles/__main__/magenta/lib/note_sequence_io_test.py", line 52, in testNoteSequenceRecordWriterAndIterator
    writer.write(sequence)
AttributeError: 'NoneType' object has no attribute 'write'

----------------------------------------------------------------------
Ran 3 tests in 0.010s

FAILED (errors=1)
```

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/__main__/magenta/scripts/convert_midi_dir_to_note_sequences_test.py", line 23, in <module>
    from magenta.scripts import convert_midi_dir_to_note_sequences
  File "/private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/__main__/magenta/scripts/convert_midi_dir_to_note_sequences.py", line 40, in <module>
    tf.app.flags.DEFINE_bool('recursive', False,
AttributeError: 'module' object has no attribute 'DEFINE_bool'
```

```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
EE.........
======================================================================
ERROR: testFileIteratorNotRecursive (__main__.PipelineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/bin/magenta/pipelines/pipeline_test.runfiles/__main__/magenta/pipelines/pipeline_test.py", line 89, in testFileIteratorNotRecursive
    tf.gfile.MakeDirs(os.path.dirname(abs_path))
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_gfile.py", line 294, in MakeDirs
    os.makedirs(path, mode)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/var/folders/ft/pglvm7vd2z314vmrkkrqgsc40000gn/T/pipeline_test/tmpXijx5Y'

======================================================================
ERROR: testFileIteratorRecursive (__main__.PipelineTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_kaka/d3542784be43f5a4052aba9655d0cf38/magenta/bazel-out/local-opt/bin/magenta/pipelines/pipeline_test.runfiles/__main__/magenta/pipelines/pipeline_test.py", line 65, in testFileIteratorRecursive
    tf.gfile.MakeDirs(os.path.dirname(abs_path))
  File "/Library/Python/2.7/site-packages/tensorflow/python/platform/default/_gfile.py", line 294, in MakeDirs
    os.makedirs(path, mode)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 17] File exists: '/var/folders/ft/pglvm7vd2z314vmrkkrqgsc40000gn/T/pipeline_test/tmpviHWZd'

----------------------------------------------------------------------
Ran 11 tests in 0.042s

FAILED (errors=2)
```

Could anyone give me an advice?

**Comment by kunimi00** [comment]
I also tried different settings from scratch using virtualenv. 
They all come up with the same error.
I've been googling a lot, but haven't been quite successful.. 
(If this is a too primitive problem and is due to my lack of knowledge in general CS, please let me know what part I should study more to get clues on it. )

**Comment by kunimi00** [comment]
I guess the problem was due to bazel installation and environment setting. I reinstalled every environment on a clean ubuntu from scratch, and got it all working. 
I'll close this thread.
