### ISSUE TITLE
setup.py test failing with syntaxerror

### ISSUE THREAD

**Issue by vitorarrais** [tensorflow/magenta#1420]
Error:
```
Traceback (most recent call last):
  File "setup.py", line 154, in <module>
    tests_require=['pytest', 'pylint'],

  (...)

  File "/Users/vitorarrais/magenta/.eggs/pytest_pylint-0.14.0-py2.7.egg/pytest_pylint.py", line 13, in <module>
    from pylint import lint
  File "/Users/vitorarrais/magenta/.eggs/pylint-2.3.0.dev1-py2.7.egg/pylint/lint.py", line 218
    def _cpu_count() -> int:
                     ^
SyntaxError: invalid syntax
```

Occurred when running `python setup.py test` in Python 2.7 environment

Any thoughts?

**Comment by cghawthorne** [comment]
@adarob I think you mentioned that pytest only works in python 3. Should we modify setup.py to behave differently for py2 or something?
