### ISSUE TITLE
score2perf; AttributeError: 'module' object has no attribute 'ModalityType'

### ISSUE THREAD

**Issue by Kangmo** [tensorflow/magenta#1435]
While running t2t_trainer, got the following error. Tried tensor2tensor version 1.10.0, 1.11.0, 1.12.0 but had the same issue.

Magenta-gpu version 1.0.2

> Traceback (most recent call last):
>   File "/data/ai/magenta/magenta/tensor2tensor/t2t_trainer.py", line 38, in <module>
>     console_entry_point()
>   File "/data/ai/magenta/magenta/tensor2tensor/t2t_trainer.py", line 34, in console_entry_point
>     tf.app.run(main)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
>     _sys.exit(main(argv))
>   File "/data/ai/magenta/magenta/tensor2tensor/t2t_trainer.py", line 29, in main
>     t2t_trainer.main(argv)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/bin/t2t_trainer.py", line 390, in main
>     exp = exp_fn(create_run_config(hparams), hparams)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/utils/trainer_lib.py", line 806, in experiment_fn
>     return create_experiment(run_config, hparams, *args, **kwargs)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/utils/trainer_lib.py", line 696, in create_experiment
>     add_problem_hparams(hparams, problem_name)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/utils/trainer_lib.py", line 817, in add_problem_hparams
>     p_hparams = problem.get_hparams(hparams)
>   File "/home/kangmo/.conda/envs/gcp-p27/lib/python2.7/site-packages/tensor2tensor-1.12.0-py2.7.egg/tensor2tensor/data_generators/problem.py", line 499, in get_hparams
>     ret = self.hparams(hp, model_hparams)
>   File "/data/ai/magenta/magenta/models/score2perf/score2perf.py", line 165, in hparams
>     defaults.modality = {'targets': t2t_modalities.ModalityType.SYMBOL}
> AttributeError: 'module' object has no attribute 'ModalityType'

**Comment by Kangmo** [comment]
Here is my code to repro the issue.

> DATA_DIR=`pwd`/datagen
> HPARAMS_SET=transformer_base
> MODEL=transformer
> PROBLEM=score2perf_maestro_language_uncropped_aug
> TRAIN_DIR=`pwd`/train_dir
> 
> HPARAMS=\
> "label_smoothing=0.0,"\
> "max_length=0,"\
> "max_target_seq_length=2048"
> 
> python $SCRIPT_HOME/tensor2tensor/t2t_trainer.py \
>   --data_dir="${DATA_DIR}" \
>   --hparams=${HPARAMS} \
>   --hparams_set=${HPARAMS_SET} \
>   --model=${MODEL} \
>   --output_dir=${TRAIN_DIR} \
>   --problem=${PROBLEM} \
>   --train_steps=1000000

**Comment by Kangmo** [comment]
Wondering if this commit is causing this issue. 

https://github.com/tensorflow/magenta/commit/89f9c29b59bb309af4dbe86328e2788448dc6621

**Comment by Kangmo** [comment]
In my environment, reverting the above commit from v1.0.2 fixes the issue.
Not sure if the above commit was the root cause though.

**Comment by cghawthorne** [comment]
@dustinvtran do you know what's going on here?

**Comment by aletote** [comment]
Got the same error, I'm gonna try reverting to that commit.

**Comment by dustinvtran** [comment]
Seems like a dependency issue. Latest T2T release (v.1.12.0) doesn't have ModalityType. @afrozenator

**Comment by afrozenator** [comment]
We'll have to do a t2t release soon

**Comment by robinmeier** [comment]
I'm getting the same error. how did you fix it? how do i revert to a previous commit?

**Comment by robinmeier** [comment]
using this command:

DATA_DIR=/Users/xxxxxx/transformer-model/tfrecord/
HPARAMS_SET=transformer_base
MODEL=transformer
PROBLEM=score2perf_maestro_language_uncropped_aug
TRAIN_DIR=/Users/xxxxxx/transformer-model/training/

HPARAMS=\
"label_smoothing=0.0,"\
"max_length=0,"\
"max_target_seq_length=2048"

t2t_trainer \
  --data_dir="${DATA_DIR}" \
  --hparams=${HPARAMS} \
  --hparams_set=${HPARAMS_SET} \
  --model=${MODEL} \
  --output_dir=${TRAIN_DIR} \
  --problem=${PROBLEM} \
  --train_steps=1000000


i get the following error:

Traceback (most recent call last):
  File "/anaconda3/envs/magenta/bin/t2t_trainer", line 10, in <module>
    sys.exit(console_entry_point())
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/tensor2tensor/t2t_trainer.py", line 34, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/tensor2tensor/t2t_trainer.py", line 29, in main
    t2t_trainer.main(argv)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensor2tensor/bin/t2t_trainer.py", line 390, in main
    exp = exp_fn(create_run_config(hparams), hparams)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 806, in experiment_fn
    return create_experiment(run_config, hparams, *args, **kwargs)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 696, in create_experiment
    add_problem_hparams(hparams, problem_name)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensor2tensor/utils/trainer_lib.py", line 817, in add_problem_hparams
    p_hparams = problem.get_hparams(hparams)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensor2tensor/data_generators/problem.py", line 499, in get_hparams
    ret = self.hparams(hp, model_hparams)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/magenta/models/score2perf/score2perf.py", line 162, in hparams
    defaults.modality = {'targets': t2t_modalities.ModalityType.SYMBOL}
AttributeError: 'module' object has no attribute 'ModalityType'

**Comment by aletote** [comment]
Clicked on the commit link that Kangmo posted and then I manually deleted the code in red and pasted the code in green in it's place and then saved the file. Now I don't get that error anymore.

**Comment by robinmeier** [comment]
oh weird, I had to do the opposite -> replace the "green" with the "red" and now it's training. i must have an old version in my environment?

**Comment by aletote** [comment]
Yeah, my bad. It's the opposite way.
