### ISSUE TITLE
ImportError: Entry point ('console_scripts', 't2t_datagen') not found

### ISSUE THREAD

**Issue by robinmeier** [tensorflow/magenta#1447]
trying to run t2t_datagen as noted in the readme with:

PROBLEM=score2perf_maestro_language_uncropped_aug
BUCKET=gymno
PROJECT=gymno-232115

PIPELINE_OPTIONS=\
"--runner=DataflowRunner,"\
"--project=${PROJECT},"\
"--temp_location=gs://${BUCKET}/tmp,"\
"--setup_file=/Users/meier/miniconda2/envs/magenta/magenta/setup.py"

t2t_datagen \
  --data_dir=gs://${BUCKET}/datagen \
  --problem=${PROBLEM} \
  --pipeline_options="${PIPELINE_OPTIONS}" \
  --alsologtostderr

getting following error:

upgraded tensorflow, manually upgraded absl-py - I now get a new error when launching same command:

Traceback (most recent call last):
File "/Users/meier/miniconda2/envs/magenta/bin/t2t_datagen", line 11, in 
load_entry_point('magenta', 'console_scripts', 't2t_datagen')()
File "/Users/meier/miniconda2/envs/magenta/lib/python2.7/site-packages/pkg_resources/**init**.py", line 480, in load_entry_point
return get_distribution(dist).load_entry_point(group, name)
File "/Users/meier/miniconda2/envs/magenta/lib/python2.7/site-packages/pkg_resources/**init**.py", line 2690, in load_entry_point
raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 't2t_datagen') not found

using Python 2.7.15 :: Anaconda, Inc. on os x 10.12.6

tensor2tensor                      1.12.0                
tensorboard                        1.12.2                
tensorflow                         1.12.0                
magenta                            0.3.12                /Users/meier/miniconda2/envs/magenta/lib/python2.7/site-packages

**Comment by robinmeier** [comment]
upgraded tensorflow, manually upgraded absl-py - I now get a new error when launching same command:

Traceback (most recent call last):
  File "/Users/meier/miniconda2/envs/magenta/bin/t2t_datagen", line 11, in <module>
    load_entry_point('magenta', 'console_scripts', 't2t_datagen')()
  File "/Users/meier/miniconda2/envs/magenta/lib/python2.7/site-packages/pkg_resources/__init__.py", line 480, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/meier/miniconda2/envs/magenta/lib/python2.7/site-packages/pkg_resources/__init__.py", line 2690, in load_entry_point
    raise ImportError("Entry point %r not found" % ((group, name),))
ImportError: Entry point ('console_scripts', 't2t_datagen') not found

**Comment by robinmeier** [comment]
reinstalling magenta from scratch solved this
