### ISSUE TITLE
Coconet: Add harmony to melody

### ISSUE THREAD

**Issue by magnus-gross** [tensorflow/magenta#1481]
I would like to use Coconet like it used in todays Google Doodle to add 3 voices to a melody line: https://www.google.com/doodles/celebrating-johann-sebastian-bach

I am in the `magenta/models/coconet` subdirectory and I can use `sh sample_bazel.sh /tmp/coconet_checkpoint/coconet-64layers-128filters/` to generate a new piece.

How can I use coconet to add harmony to a midi melody line instead of generating a complete new piece?

I tried using the `prime_midi_melody_fpath` argument in the `coconet_sample.py` file, but to no avail, and it is not clear for me how to use it correctly.

Are there any instructions on how to accomplish this?

**Comment by ak9250** [comment]
not sure about this but how did you get the sh sample_bazel.sh /tmp/coconet_checkpoint/coconet-64layers-128filters/ to work i am using !sh sample_bazel.sh /content/magenta/magenta/models/coconet/coconet_checkpoint/coconet-64layers-128filters/ and getting a value error

2019-03-21 18:25:34.953467: W tensorflow/core/common_runtime/gpu/gpu_bfc_allocator.cc:42] Overriding allow_growth setting because the TF_FORCE_GPU_ALLOW_GROWTH environment variable is set. Original config value was 0.
2019-03-21 18:25:34.953527: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1115] Created TensorFlow device (/job:localhost/replica:0/task:0/device:GPU:0 with 10754 MB memory) -> physical GPU (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0, compute capability: 3.7)
ERROR:tensorflow:Couldn't match files for checkpoint /content/magenta/magenta/models/coconet/coconet_checkpoint/coconet-64layers-128filters/model.ckpt
Traceback (most recent call last):
  File "coconet_sample.py", line 692, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "coconet_sample.py", line 66, in main
    gen_batch_size=FLAGS.gen_batch_size, piece_length=FLAGS.piece_length)
  File "coconet_sample.py", line 272, in run_generation
    temperature=temperature)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/coconet/lib_tfsampling.py", line 249, in run
    self.instantiate_sess_and_restore_checkpoint()
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/coconet/lib_tfsampling.py", line 197, in instantiate_sess_and_restore_checkpoint
    saver.restore(sess, chkpt_fpath)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1264, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by magnus-gross** [comment]
@ak9250 See #1292 

You have to replace the content of the `checkpoint` file with:

```bash
model_checkpoint_path: "best_model.ckpt"
```

**Comment by ak9250** [comment]
@magnus-gross thanks do you also know how to start training it? I am getting this when trying to train 
INFO:tensorflow:Saving checkpoint to path /content/magenta/magenta/models/coconet/logging/dilated-10-64_bs=1,corrupt=0.5,len=32,lr=0.0625,mm=orderless,nreg_conv=2,num_i=4,n_pch=128,mask_only=False,quant=0.125,rescale=True,depth_mul=1,sep=True,res=True,sconv=True,soft=True/model.ckpt
Traceback (most recent call last):
  File "coconet_train.py", line 378, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "coconet_train.py", line 285, in main
    epoch_count)
  File "coconet_train.py", line 178, in run_epoch
    fetches, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 7, 46, 4) for Tensor u'Placeholder_1:0', which has shape '(?, ?, 128, 4)'

**Comment by Riuchando** [comment]
from reading the code, if you want to use the npz file provided, you need to rename it from TestData.npz to Jsb16thSeparated.npz, however the TestData.npz doesn't provide enough data, to train anything meaningful. I wrote something on my branch to generate midi -> the npz format that they use, but I can't be for sure that my data is right/ accurate.

**Comment by czhuang** [comment]
You can find the JSB Chorale dataset here: https://github.com/czhuang/JSB-Chorales-dataset

There's a Jsb16thSeparated.npz there and the READ.md includes some description of the format.

**Comment by AI-Guru** [comment]
Trying to add harmonies myself. Got the feeling that I am almost there. 

```
python coconet_sample.py \
--checkpoint="$checkpoint" \
--generation_output_dir=samples \
--prime_midi_melody_fpath=$midipath \
--strategy="harmonize_midi_melody"
```

--strategy seems to be the crucial part. 

Any successes?

**Comment by scheng123** [comment]
I gave up on trying to harmonize a midi file. I looked at `coconet_sample.py` and the entire `HarmonizeMidiMelodyStrategy` class is by itself. With no other attachment of this class to the generator class, I don't have any idea on how to make this work.

**Comment by adarob** [comment]
@czhuang any guidance? You can also try using http://coconet.glitch.me/
