### ISSUE TITLE
gansynth  KeyError: 'velocities'

### ISSUE THREAD

**Issue by babyhanhan** [tensorflow/magenta#1482]
When generating with a specified MIDI file .
...
Generating 148 samples...
generate_samples: generated 148 samples in 59.005136013s
Traceback (most recent call last):
  File "/home/ustc/limenghan/magenta/magenta/models/gansynth/gansynth_generate.py", line 112, in <module>
    console_entry_point()
  File "/home/ustc/limenghan/magenta/magenta/models/gansynth/gansynth_generate.py", line 108, in console_entry_point
    tf.app.run(main)
  File "/home/ustc/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/home/ustc/limenghan/magenta/magenta/models/gansynth/gansynth_generate.py", line 93, in main
    notes['velocities'])
KeyError: 'velocities'

**Comment by jesseengel** [comment]
Sorry this was an error due to the pypi version not being updated (which it now is). This should now be resolved.
