### ISSUE TITLE
Multitrack MusicVAE: Not found: Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint

### ISSUE THREAD

**Issue by EinsteinsErbe** [tensorflow/magenta#1496]
I want to continue training a multitrack vae model. I am using the unconditioned model "model_fb256.ckpt" found on 
https://colab.research.google.com/notebooks/magenta/music_vae/multitrack.ipynb
When I execute the training script I get following error:
```
INFO:tensorflow:Restoring parameters from ./MT1ModelPretrained/run01/train/model_fb256.ckpt
2019-04-09 11:50:02.897895: W tensorflow/core/framework/op_kernel.cc:1273] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1334, in _do_call
    return fn(*args)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1319, in _run_fn
    options, feed_dict, fetch_list, target_list, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1407, in _call_tf_sessionrun
    run_metadata)
tensorflow.python.framework.errors_impl.NotFoundError: Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
         [[{{node save/RestoreV2}} = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1546, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1152, in _run
    feed_dict_tensor, options, run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1328, in _do_run
    run_metadata)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/client/session.py", line 1348, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
         [[node save/RestoreV2 (defined at /usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py:202)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/local/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 302, in run
    task=FLAGS.task)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 202, in train
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 862, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
         [[node save/RestoreV2 (defined at /usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py:202)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1556, in restore
    names_to_keys = object_graph_key_mapping(save_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1830, in object_graph_key_mapping
    checkpointable.OBJECT_GRAPH_PROTO_KEY)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 371, in get_tensor
    status)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/errors_impl.py", line 528, in __exit__
    c_api.TF_GetCode(self.status.status))
tensorflow.python.framework.errors_impl.NotFoundError: Key _CHECKPOINTABLE_OBJECT_GRAPH not found in checkpoint

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 302, in run
    task=FLAGS.task)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 210, in train
    is_chief=is_chief)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/contrib/training/python/training/training.py", line 543, in train
    max_wait_secs=max_wait_secs) as session:
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 504, in MonitoredTrainingSession
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 921, in __init__
    stop_grace_period_secs=stop_grace_period_secs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 643, in __init__
    self._sess = _RecoverableSession(self._coordinated_creator)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1107, in __init__
    _WrappedSession.__init__(self, self._create_session())
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 1112, in _create_session
    return self._sess_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 800, in create_session
    self.tf_sess = self._session_creator.create_session()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/monitored_session.py", line 566, in create_session
    init_fn=self._scaffold.init_fn)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/session_manager.py", line 288, in prepare_session
    config=config)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/session_manager.py", line 218, in _restore_checkpoint
    saver.restore(sess, ckpt.model_checkpoint_path)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1562, in restore
    err, "a Variable name or other graph key that is missing")
tensorflow.python.framework.errors_impl.NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
         [[node save/RestoreV2 (defined at /usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py:202)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]

Caused by op 'save/RestoreV2', defined at:
  File "/usr/local/bin/music_vae_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 324, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 320, in main
    run(configs.CONFIG_MAP)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 302, in run
    task=FLAGS.task)
  File "/usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py", line 202, in train
    keep_checkpoint_every_n_hours=keep_checkpoint_every_n_hours))
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1102, in __init__
    self.build()
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1114, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 1151, in _build
    build_save=build_save, build_restore=build_restore)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 795, in _build_internal
    restore_sequentially, reshape)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 406, in _AddRestoreOps
    restore_sequentially)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/training/saver.py", line 862, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 1466, in restore_v2
    shape_and_slices=shape_and_slices, dtypes=dtypes, name=name)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/op_def_library.py", line 787, in _apply_op_helper
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/util/deprecation.py", line 488, in new_func
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 3274, in create_op
    op_def=op_def)
  File "/usr/local/lib/python3.5/dist-packages/tensorflow/python/framework/ops.py", line 1770, in __init__
    self._traceback = tf_stack.extract_stack()

NotFoundError (see above for traceback): Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint. Please ensure that you have not altered the graph expected based on the checkpoint. Original error:

Key core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias/Adam not found in checkpoint
         [[node save/RestoreV2 (defined at /usr/local/lib/python3.5/dist-packages/magenta/models/music_vae/music_vae_train.py:202)  = RestoreV2[dtypes=[DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, ..., DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_FLOAT, DT_INT64], _device="/job:localhost/replica:0/task:0/device:CPU:0"](_arg_save/Const_0_0, save/RestoreV2/tensor_names, save/RestoreV2/shape_and_slices)]]
```

using the inspect_checkpoint tool on the checkpoint shows that all `core_decoder/decoder/multi_rnn_cell/cell_X/lstm_cell/bias/adam`
`core_decoder/decoder/multi_rnn_cell/cell_X/lstm_cell/bias/adam_1`
are missing:
```
beta1_power (DT_FLOAT) []
beta2_power (DT_FLOAT) []
core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/bias (DT_FLOAT) [2048]
core_decoder/decoder/multi_rnn_cell/cell_0/lstm_cell/kernel (DT_FLOAT) [1514,2048]
core_decoder/decoder/multi_rnn_cell/cell_1/lstm_cell/bias (DT_FLOAT) [2048]
core_decoder/decoder/multi_rnn_cell/cell_1/lstm_cell/kernel (DT_FLOAT) [1024,2048]
core_decoder/decoder/multi_rnn_cell/cell_2/lstm_cell/bias (DT_FLOAT) [2048]
core_decoder/decoder/multi_rnn_cell/cell_2/lstm_cell/kernel (DT_FLOAT) [1024,2048]
core_decoder/decoder/opaque_kernel (DT_FLOAT) [7307264]
core_decoder/decoder/opaque_kernel/Adam (DT_FLOAT) [7307264]
core_decoder/decoder/opaque_kernel/Adam_1 (DT_FLOAT) [7307264]
core_decoder/decoder/output_projection/bias (DT_FLOAT) [490]
core_decoder/decoder/output_projection/bias/Adam (DT_FLOAT) [490]
core_decoder/decoder/output_projection/bias/Adam_1 (DT_FLOAT) [490]
core_decoder/decoder/output_projection/kernel (DT_FLOAT) [512,490]
core_decoder/decoder/output_projection/kernel/Adam (DT_FLOAT) [512,490]
core_decoder/decoder/output_projection/kernel/Adam_1 (DT_FLOAT) [512,490]
core_decoder/decoder/z_to_initial_state/bias (DT_FLOAT) [3072]
core_decoder/decoder/z_to_initial_state/bias/Adam (DT_FLOAT) [3072]
core_decoder/decoder/z_to_initial_state/bias/Adam_1 (DT_FLOAT) [3072]
core_decoder/decoder/z_to_initial_state/kernel (DT_FLOAT) [512,3072]
core_decoder/decoder/z_to_initial_state/kernel/Adam (DT_FLOAT) [512,3072]
core_decoder/decoder/z_to_initial_state/kernel/Adam_1 (DT_FLOAT) [512,3072]
decoder/hierarchical_level_0/cell_0/lstm_cell/bias (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_0/lstm_cell/bias/Adam (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_0/lstm_cell/bias/Adam_1 (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_0/lstm_cell/kernel (DT_FLOAT) [513,2048]
decoder/hierarchical_level_0/cell_0/lstm_cell/kernel/Adam (DT_FLOAT) [513,2048]
decoder/hierarchical_level_0/cell_0/lstm_cell/kernel/Adam_1 (DT_FLOAT) [513,2048]
decoder/hierarchical_level_0/cell_1/lstm_cell/bias (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_1/lstm_cell/bias/Adam (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_1/lstm_cell/bias/Adam_1 (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_1/lstm_cell/kernel (DT_FLOAT) [1024,2048]
decoder/hierarchical_level_0/cell_1/lstm_cell/kernel/Adam (DT_FLOAT) [1024,2048]
decoder/hierarchical_level_0/cell_1/lstm_cell/kernel/Adam_1 (DT_FLOAT) [1024,2048]
decoder/hierarchical_level_0/cell_2/lstm_cell/bias (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_2/lstm_cell/bias/Adam (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_2/lstm_cell/bias/Adam_1 (DT_FLOAT) [2048]
decoder/hierarchical_level_0/cell_2/lstm_cell/kernel (DT_FLOAT) [1024,2048]
decoder/hierarchical_level_0/cell_2/lstm_cell/kernel/Adam (DT_FLOAT) [1024,2048]
decoder/hierarchical_level_0/cell_2/lstm_cell/kernel/Adam_1 (DT_FLOAT) [1024,2048]
decoder/hierarchical_level_0/initial_state/bias (DT_FLOAT) [3072]
decoder/hierarchical_level_0/initial_state/bias/Adam (DT_FLOAT) [3072]
decoder/hierarchical_level_0/initial_state/bias/Adam_1 (DT_FLOAT) [3072]
decoder/hierarchical_level_0/initial_state/kernel (DT_FLOAT) [512,3072]
decoder/hierarchical_level_0/initial_state/kernel/Adam (DT_FLOAT) [512,3072]
decoder/hierarchical_level_0/initial_state/kernel/Adam_1 (DT_FLOAT) [512,3072]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/bias (DT_FLOAT) [4096]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/kernel (DT_FLOAT) [1514,4096]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/bw/opaque_kernel (DT_FLOAT) [6209536]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/bw/opaque_kernel/Adam (DT_FLOAT) [6209536]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/bw/opaque_kernel/Adam_1 (DT_FLOAT) [6209536]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/bias (DT_FLOAT) [4096]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/kernel (DT_FLOAT) [1514,4096]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/fw/opaque_kernel (DT_FLOAT) [6209536]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/fw/opaque_kernel/Adam (DT_FLOAT) [6209536]
encoder/hierarchical_level_0/cell_0/bidirectional_rnn/fw/opaque_kernel/Adam_1 (DT_FLOAT) [6209536]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/bias (DT_FLOAT) [4096]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/bw/multi_rnn_cell/cell_0/lstm_cell/kernel (DT_FLOAT) [3072,4096]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/bw/opaque_kernel (DT_FLOAT) [12591104]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/bw/opaque_kernel/Adam (DT_FLOAT) [12591104]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/bw/opaque_kernel/Adam_1 (DT_FLOAT) [12591104]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/bias (DT_FLOAT) [4096]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/fw/multi_rnn_cell/cell_0/lstm_cell/kernel (DT_FLOAT) [3072,4096]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/fw/opaque_kernel (DT_FLOAT) [12591104]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/fw/opaque_kernel/Adam (DT_FLOAT) [12591104]
encoder/hierarchical_level_1/cell_0/bidirectional_rnn/fw/opaque_kernel/Adam_1 (DT_FLOAT) [12591104]
encoder/mu/bias (DT_FLOAT) [512]
encoder/mu/bias/Adam (DT_FLOAT) [512]
encoder/mu/bias/Adam_1 (DT_FLOAT) [512]
encoder/mu/kernel (DT_FLOAT) [2048,512]
encoder/mu/kernel/Adam (DT_FLOAT) [2048,512]
encoder/mu/kernel/Adam_1 (DT_FLOAT) [2048,512]
encoder/sigma/bias (DT_FLOAT) [512]
encoder/sigma/bias/Adam (DT_FLOAT) [512]
encoder/sigma/bias/Adam_1 (DT_FLOAT) [512]
encoder/sigma/kernel (DT_FLOAT) [2048,512]
encoder/sigma/kernel/Adam (DT_FLOAT) [2048,512]
encoder/sigma/kernel/Adam_1 (DT_FLOAT) [2048,512]
global_step (DT_INT64) []
```

**Comment by adarob** [comment]
@iansimon do you have the multitrack checkpoints without the training-specific weights removed?

**Comment by iansimon** [comment]
The checkpoint does have Adam-related weights in it, but it looks like they're "Adam" with an uppercase A instead of lowercase.  Did something change in the names expected by Tensorflow?
