### ISSUE TITLE
Error in join_pairs while running next frame prediction

### ISSUE THREAD

**Issue by heaversm** [tensorflow/magenta#1503]
In executing the `create_video.sh` script within the next_frame_prediction_pix2pix folder, I answer yes to all questions, and successfully generate content within the `frames` and `good` directories (`test` and `train` are empty), and get this error:

```
looking for frames img in ./working_folder//good/*.jpg
found  249 for right list
load left ./working_folder//frames/f0000044.jpg  and right ./working_folder//good/f0000045.jpg
Traceback (most recent call last):
  File "join_pairs.py", line 125, in <module>
    main(0)
  File "join_pairs.py", line 121, in main
    pair.save(file_out, 'JPEG')
  File "/Users/heavers/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 1966, in save
    fp = builtins.open(filename, "w+b")
FileNotFoundError: [Errno 2] No such file or directory: './working_folder//val/p0000044.jpg'
```
There is no `val` directory created up to this point.

**Comment by heaversm** [comment]
Noticed that I get a step further if I manually create the directory `val` before running the script. I then hit another error:

```
training 1/20
  File "pix2pix-tensorflow-0.1/main.py", line 69
    print "pre recursion"
                        ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("pre recursion")?
```

There are subsequent errors, but I will file a different issue for that.

**Comment by adarob** [comment]
That appears to be an incompatibility issue with python3. You can try using python2 or update the file for compatibility.

**Comment by heaversm** [comment]
👍
