### ISSUE TITLE
sh train_bazel.sh return ValueError: Cannot feed value of shape (1, 7, 46, 4) for Tensor u'Placeholder_1:0', which has shape '(?, ?, 128, 4)'

### ISSUE THREAD

**Issue by TatianaZobnina** [tensorflow/magenta#1521]
Trying to run "sh train_bazel.sh" get this: 

INFO:tensorflow:Saving checkpoint to path /Users/.../logs/dilated-10-64_bs=1,corrupt=0.5,len=32,lr=0.0625,mm=orderless,nreg_conv=2,num_i=4,n_pch=128,mask_only=False,quant=0.125,rescale=True,depth_mul=1,sep=True,res=True,sconv=True,soft=True/model.ckpt
INFO:tensorflow:Starting queue runners.
Traceback (most recent call last):
  File "coconet_train.py", line 378, in <module>
    tf.app.run()
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 125, in run
    _sys.exit(main(argv))
  File "coconet_train.py", line 285, in main
    epoch_count)
  File "coconet_train.py", line 178, in run_epoch
    fetches, feed_dict=feed_dict)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 929, in run
    run_metadata_ptr)
  File "/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1128, in _run
    str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 7, 46, 4) for Tensor u'Placeholder_1:0', which has shape '(?, ?, 128, 4)'

trying to guess what is wrong?

**Comment by TatianaZobnina** [comment]
Probably I found the answer for this question. The problem is the in the class TestData(Dataset) in lib_data.py. The reason of the error that in this class the max_pitch = 127 and in fact in TestData.npz is 46. Therefor to solve this error we need to switch to some another dataset or make another class.
