### ISSUE TITLE
pip install issue on Raspbian Stretch (Python 3.5/3.6) - llvmlite dependency

### ISSUE THREAD

**Issue by vlasov01** [tensorflow/magenta#1522]
Hi,
I've tried to install magenta on Raspbian Stretch. And it fails with Python 3.5 and 3.6 at the same place:
  Running setup.py install for llvmlite ... error
    ERROR: Complete output from command /home/pi/testpip/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-0fbiv6l7/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ocicz40i/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/testpip/include/site/python3.5/llvmlite:
    ERROR: running install
    running build
    got version from file /tmp/pip-install-0fbiv6l7/llvmlite/llvmlite/_version.py {'full': '685b7b6941617f616f3f0b609e381af52da26782', 'version': '0.28.0'}
    running build_ext
    /home/pi/testpip/bin/python3 /tmp/pip-install-0fbiv6l7/llvmlite/ffi/build.py
    LLVM version... Traceback (most recent call last):
      File "/tmp/pip-install-0fbiv6l7/llvmlite/ffi/build.py", line 105, in main_posix
        out = subprocess.check_output([llvm_config, '--version'])
      File "/usr/lib/python3.5/subprocess.py", line 316, in check_output
        **kwargs).stdout
      File "/usr/lib/python3.5/subprocess.py", line 383, in run
        with Popen(*popenargs, **kwargs) as process:
      File "/usr/lib/python3.5/subprocess.py", line 676, in __init__
        restore_signals, start_new_session)
      File "/usr/lib/python3.5/subprocess.py", line 1282, in _execute_child
        raise child_exception_type(errno_num, err_msg)
    FileNotFoundError: [Errno 2] No such file or directory: 'llvm-config'

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "/tmp/pip-install-0fbiv6l7/llvmlite/ffi/build.py", line 167, in <module>
        main()
      File "/tmp/pip-install-0fbiv6l7/llvmlite/ffi/build.py", line 157, in main
        main_posix('linux', '.so')
      File "/tmp/pip-install-0fbiv6l7/llvmlite/ffi/build.py", line 108, in main_posix
        "to the path for llvm-config" % (llvm_config,))
    RuntimeError: llvm-config failed executing, please point LLVM_CONFIG to the path for llvm-config
    error: command '/home/pi/testpip/bin/python3' failed with exit status 1
    ----------------------------------------
ERROR: Command "/home/pi/testpip/bin/python3 -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-0fbiv6l7/llvmlite/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-ocicz40i/install-record.txt --single-version-externally-managed --compile --install-headers /home/pi/testpip/include/site/python3.5/llvmlite" failed with error code 1 in /tmp/pip-install-0fbiv6l7/llvmlite/

**Comment by cghawthorne** [comment]
@iansimon I think you figured out how to do this at one point?

**Comment by iansimon** [comment]
It was painful, and I think I only got it working for Python 2.  I had to install a bunch of dependencies manually.

**Comment by vlasov01** [comment]
@iansimon Thank you for the response! 

When I've installed llvm 3.x than I've got an error that llvmlite requires llvm 7.
