### ISSUE TITLE
AttributeError: module 'tensorflow.python.ops.linalg.linear_operator_util' has no attribute 'matmul_with_broadcast'

### ISSUE THREAD

**Issue by Dragos2811** [tensorflow/magenta#1548]
I can`t run any magenta commands.
Here is an example  for melody_rnn_generate --config=attention_rnn --bundle_file=attention_rnn.mag --out_dir = ./out/attention --num_outputs=10 --num_steps = 256 --primer_melodi="[60]"
OUTPUT: 
WARNING: Logging before flag parsing goes to stderr.
W0619 22:20:26.601500 15344 lazy_loader.py:50]
The TensorFlow contrib module will not be included in TensorFlow 2.0.
For more information, please see:
  * https://github.com/tensorflow/community/blob/master/rfcs/20180907-contrib-sunset.md
  * https://github.com/tensorflow/addons
  * https://github.com/tensorflow/io (for I/O related ops)
If you depend on functionality not listed there, please file an issue.

Traceback (most recent call last):
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\Dragos\AppData\Local\Programs\Python\Python36\Scripts\melody_rnn_generate.exe\__main__.py", line 5, in <module>
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\magenta\__init__.py", line 26, in <module>
    import magenta.common.beam_search
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\magenta\common\__init__.py", line 20, in <module>
    from .nade import Nade
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\magenta\common\nade.py", line 24, in <module>
    import tensorflow_probability as tfp
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\tensorflow_probability\__init__.py", line 78, in <module>
    from tensorflow_probability.python import *  # pylint: disable=wildcard-import
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\tensorflow_probability\python\__init__.py", line 22, in <module>
    from tensorflow_probability.python import distributions
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\tensorflow_probability\python\distributions\__init__.py", line 61, in <module>
    from tensorflow_probability.python.distributions.linear_gaussian_ssm import LinearGaussianStateSpaceModel
  File "c:\users\dragos\appdata\local\programs\python\python36\lib\site-packages\tensorflow_probability\python\distributions\linear_gaussian_ssm.py", line 41, in <module>
    _matmul = linear_operator_util.matmul_with_broadcast
AttributeError: module 'tensorflow.python.ops.linalg.linear_operator_util' has no attribute 'matmul_with_broadcast'

**Comment by LucaAngioloni** [comment]
`matmul_with_broadcast` is not available in TensorFlow 1.14. Use a TensorFlow version between 1.13 and 1.14 excluded.
