### ISSUE TITLE
Error:Follow with readme, can't build dataset

### ISSUE THREAD

**Issue by DjangoPeng** [tensorflow/magenta#156]
I'm using my mac pro with OS X EI Capitan version 10.11.4 and following with the tutorial in readme. My tensorflow is version 0.10
But when I want to build the dataset, it always fails with log info below:
```
INFO: Found 1 target...
Target //magenta/scripts:convert_midi_dir_to_note_sequences up-to-date:
  bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences
INFO: Elapsed time: 0.324s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/magenta/scripts/convert_midi_dir_to_note_sequences '--midi_dir=/Users/Patient/tensorflow/magenta/midi' '--output_file=/tmp/notesequences.tfrecord' --recursive
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_Patient/672c0c4b53120b3038ed587d17172b35/magenta/bazel-out/local_darwin-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences.runfiles/magenta/scripts/convert_midi_dir_to_note_sequences.py", line 30, in <module>
    from magenta.lib import midi_io
  File "/private/var/tmp/_bazel_Patient/672c0c4b53120b3038ed587d17172b35/magenta/bazel-out/local_darwin-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences.runfiles/magenta/lib/midi_io.py", line 29, in <module>
    import pretty_midi
  File "/private/var/tmp/_bazel_Patient/672c0c4b53120b3038ed587d17172b35/magenta/bazel-out/local_darwin-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences.runfiles/external/pretty_midi/pretty_midi.py", line 12, in <module>
    from .instrument import Instrument
ValueError: Attempted relative import in non-package
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```
What's more, I run the tests which fails as well:
```
//magenta/lib:melodies_lib_test                                 (cached) PASSED in 4.5s
//magenta/lib:note_sequence_io_test                             (cached) PASSED in 4.1s
//magenta/lib:sequences_lib_test                                (cached) PASSED in 3.6s
//magenta/models/shared:melody_rnn_create_dataset_test          (cached) PASSED in 2.1s
//magenta/pipelines:dag_pipeline_test                           (cached) PASSED in 3.3s
//magenta/pipelines:pipeline_test                               (cached) PASSED in 3.2s
//magenta/pipelines:pipelines_common_test                       (cached) PASSED in 3.2s
//magenta/pipelines:statistics_test                             (cached) PASSED in 3.2s
//magenta/lib:midi_io_test                                               FAILED in 0.6s
  /private/var/tmp/_bazel_Patient/672c0c4b53120b3038ed587d17172b35/magenta/bazel-out/local_darwin-opt/testlogs/magenta/lib/midi_io_test/test.log
//magenta/scripts:convert_midi_dir_to_note_sequences_test                FAILED in 3.4s
  /private/var/tmp/_bazel_Patient/672c0c4b53120b3038ed587d17172b35/magenta/bazel-out/local_darwin-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log

Executed 2 out of 10 tests: 8 tests pass and 2 fail locally.
```

**Comment by DjangoPeng** [comment]
I find my bazel is 0.2.0-homebrew. When I `brew upgrade bazel` and the upgrade bazel to 0.3.1-homebrew.  It works~
