### ISSUE TITLE
Score2Perf t2t_datagen is broken with dependency(score2perf_maestro_language_uncropped_aug)

### ISSUE THREAD

**Issue by yhg0112** [tensorflow/magenta#1564]
i'm using 
tensorflow-gpu 1.14.0,
tensor2tensor 1.10.0,
and magenta-gpu 1.0.1.

i was trying to run some examples with Score2Perf, magenta-gpu version 1.0.1.
(and never have used google cloud platform before).

PROBLEM=score2perf_maestro_language_uncropped_aug

PIPELINE_OPTIONS=
"--runner=DataflowRunner,"
"--project=${PROJECT},"
"--temp_location=gs://${BUCKET}/tmp,"
"--setup_file=/my/path/to/magenta/setup.py"

t2t_datagen 
--data_dir=gs://${BUCKET}/datagen 
--problem=${PROBLEM} 
--pipeline_options="${PIPELINE_OPTIONS}" 
--alsologtostderr

Firstly i got the dependency issue with tfp and tensorflow version on gcp, 
so i have to change "setup.py"; tensorflow-gpu >= 1.14.0 and tensorflow >= 1.14.0 each in line 67 and line 69.

Then on gcp i got an error and traceback like this:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/batchworker.py", line 649, in do_work
    work_executor.execute()
  File "/usr/local/lib/python2.7/dist-packages/dataflow_worker/executor.py", line 176, in execute
    op.start()
  File "apache_beam/runners/worker/operations.py", line 577, in apache_beam.runners.worker.operations.DoOperation.start
    def start(self):
  File "apache_beam/runners/worker/operations.py", line 578, in apache_beam.runners.worker.operations.DoOperation.start
    with self.scoped_start_state:
  File "apache_beam/runners/worker/operations.py", line 579, in apache_beam.runners.worker.operations.DoOperation.start
    super(DoOperation, self).start()
  File "apache_beam/runners/worker/operations.py", line 217, in apache_beam.runners.worker.operations.Operation.start
    def start(self):
  File "apache_beam/runners/worker/operations.py", line 221, in apache_beam.runners.worker.operations.Operation.start
    self.setup()
  File "apache_beam/runners/worker/operations.py", line 526, in apache_beam.runners.worker.operations.DoOperation.setup
    with self.scoped_start_state:
  File "apache_beam/runners/worker/operations.py", line 531, in apache_beam.runners.worker.operations.DoOperation.setup
    pickler.loads(self.spec.serialized_fn))
  File "/usr/local/lib/python2.7/dist-packages/apache_beam/internal/pickler.py", line 258, in loads
    return dill.loads(s)
  File "/usr/local/lib/python2.7/dist-packages/dill/_dill.py", line 317, in loads
    return load(file, ignore)
  File "/usr/local/lib/python2.7/dist-packages/dill/_dill.py", line 305, in load
    obj = pik.load()
  File "/usr/lib/python2.7/pickle.py", line 864, in load
    dispatch[key](self)
  File "/usr/lib/python2.7/pickle.py", line 1139, in load_reduce
    value = func(*args)
  File "/usr/local/lib/python2.7/dist-packages/dill/_dill.py", line 828, in _import_module
    return getattr(__import__(module, None, None, [obj]), obj)
  File "/usr/local/lib/python2.7/dist-packages/magenta/__init__.py", line 34, in <module>
    import magenta.music.audio_io
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/audio_io.py", line 23, in <module>
    import librosa
  File "/usr/local/lib/python2.7/dist-packages/librosa/__init__.py", line 13, in <module>
    from . import core
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/__init__.py", line 115, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "/usr/local/lib/python2.7/dist-packages/librosa/core/audio.py", line 8, in <module>
    import soundfile as sf
  File "/usr/local/lib/python2.7/dist-packages/soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

do you have any solution for this? it seems that i have to install 'librosa' dependencies on apache-beam pipeline but i couldn't figure how.

**Comment by chaonan99** [comment]
From [SoundFile](https://pypi.org/project/SoundFile/) you need to install libsndfile by `sudo apt-get install libsndfile1`. You can change your `setup.py` to install non-python dependencies as suggested [here](https://beam.apache.org/documentation/sdks/python-pipeline-dependencies/). And you can find an example [here](https://github.com/apache/beam/blob/master/sdks/python/apache_beam/examples/complete/juliaset/setup.py).
