### ISSUE TITLE
Error when trying to run any script with GPU on Windows

### ISSUE THREAD

**Issue by AlexandreJup** [tensorflow/magenta#1565]
Hi ! 
I have been having problems when trying to run scripts using the GPU version of magenta. I checked that tensorflow-gpu is installed and uses GPU so no problem on that side.
I am using python 3.6.x and running on Windows 10.

The only script I've managed to run is `convert_dir_to_note_sequences`. Probably because it doesn't need tensorflow to create the tf record file.

When trying to run any other script, like this one :  
`melody_rnn_train --config=attention_rnn --run_dir=melody_rnn\logdir\training_run --sequence_example_file=note_sequences\1107_piano.tfrecord --num_training_steps=100`

I always get the same error : 

Traceback (most recent call last):
  File "c:\users\alexa\appdata\local\programs\python\python36\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\alexa\appdata\local\programs\python\python36\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\alexa\AppData\Local\Programs\Python\Python36\Scripts\melody_rnn_train.exe\__main__.py", line 5, in <module>

  File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\magenta\models\melody_rnn\__init__.py", line 21, in <module>
    from .melody_rnn_model import MelodyRnnModel
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\magenta\models\melody_rnn\melody_rnn_model.py", line 20, in <module>
    from magenta.models.shared import events_rnn_model
  
File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\magenta\models\shared\events_rnn_model.py", line 23, in <module>
    from magenta.models.shared import events_rnn_graph
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\magenta\models\shared\events_rnn_graph.py", line 33, in <module>
    base_cell=tf.contrib.rnn.BasicLSTMCell,
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 62, in __getattr__
    module = self._load()
  
File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\util\lazy_loader.py", line 45, in _load
    module = importlib.import_module(self.__name__)
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\__init__.py", line 33, in <module>
    from tensorflow.contrib import compiler
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\compiler\__init__.py", line 22, in <module>
    from tensorflow.contrib.compiler import xla
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow\contrib\compiler\xla.py", line 22, in <module>
    from tensorflow.python.estimator import model_fn as model_fn_lib

  File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow\python\estimator\__init__.py", line 26, in <module>
    from tensorflow_estimator.python import estimator
 
File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\python\estimator\__init__.py", line 25, in <module>
    import tensorflow_estimator.python.estimator.estimator_lib
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\python\estimator\estimator_lib.py", line 69, in <module>
    from tensorflow_estimator.python.estimator.tpu.tpu_estimator import TPUEstimator

  File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\python\estimator\tpu\tpu_estimator.py", line 83, in <module>
    from tensorflow_estimator.python.estimator import estimator as estimator_lib
 
File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1 import estimator

  File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\_api\v1\estimator\__init__.py", line 11, in <module>
    from tensorflow_estimator._api.v1.estimator import tpu

  File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\_api\v1\estimator\tpu\__init__.py", line 8, in <module>
    from tensorflow_estimator._api.v1.estimator.tpu import experimental
 
 File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\_api\v1\estimator\tpu\experimental\__init__.py", line 8, in <module>
    from tensorflow_estimator.python.estimator.tpu._tpu_estimator_embedding import EmbeddingConfigSpec

  File "c:\users\alexa\appdata\local\programs\python\python36\lib\site-packages\tensorflow_estimator\python\estimator\tpu\_tpu_estimator_embedding.py", line 32, in <module>
    from tensorflow.python.tpu import feature_column_v2 as tpu_fc_v2
ImportError: cannot import name 'feature_column_v2'

Any ideas?

**Comment by cghawthorne** [comment]
It looks like your Tensorflow installation is corrupt. I'd try uninstalling tensorflow, magenta, tensorflow-gpu, magenta-gpu, and then installing from scratch.

**Comment by AlexandreJup** [comment]
@cghawthorne I will try re installing properly, I will let you know. Thanks
