### ISSUE TITLE
free variable 'do_return_5' referenced before assignment in enclosing scope

### ISSUE THREAD

**Issue by SamNPowers** [tensorflow/magenta#1622]
I followed the following steps, on a Windows 10 machine:
1. clone the repository
2. create a new python 3.6 virtual env
3. pip install -e .
4. ran: music_vae_train.py --config=cat-mel_2bar_big --run_dir=tmp/music_vae/cat-mel_2bar_big --mode=train --examples_path=<path_to_midi_tfrecord>\lakh_midi_subset.tfrecord

It seems to set everything up correctly, but during the actual session.run it gives the following error. The issue seems fairly deep into standard tensorflow methods. I didn't modify the code at all before running it, also.

Anyone have any ideas? Thanks

`2019-11-12 12:48:46.296901: W tensorflow/core/framework/op_kernel.cc:1639] Unknown: NameError: free variable 'do_return_5' referenced before assignment in enclosing scope
Traceback (most recent call last):

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 233, in __call__
    return func(device, token, args)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\ops\script_ops.py", line 122, in __call__
    ret = self._func(*args)

  File "C:\Users\spowers\AppData\Local\Temp\tmpoetxtp4q.py", line 40, in _convert_and_pad
    tensors = ag__.converted_call(self.to_tensors, _convert_and_pad_scope.callopts, (item,), None, _convert_and_pad_scope)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 541, in converted_call
    result = converted_f(*effective_args)

  File "C:\Users\spowers\AppData\Local\Temp\tmpis5qwgjv.py", line 29, in tf__to_tensors
    ag__.for_stmt(note_sequences, None, loop_body, get_state, set_state, (), (), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 339, in for_stmt
    return _py_for_stmt(iter_, extra_test, body, get_state, set_state, init_vars)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 350, in _py_for_stmt
    state = body(target, *state)

  File "C:\Users\spowers\AppData\Local\Temp\tmpis5qwgjv.py", line 27, in loop_body
    ag__.converted_call(results.append, to_tensors_scope.callopts, (ag__.converted_call(ag__.converted_call(super, to_tensors_scope.callopts, (BaseNoteSequenceConverter, self), None, to_tensors_scope).to_tensors, to_tensors_scope.callopts, (ns,), None, to_tensors_scope),), None, to_tensors_scope)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 541, in converted_call
    result = converted_f(*effective_args)

  File "C:\Users\spowers\AppData\Local\Temp\tmp014xlnqu.py", line 15, in tf__to_tensors
    tensors = ag__.converted_call(self._to_tensors, to_tensors_scope.callopts, (item,), None, to_tensors_scope)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 541, in converted_call
    result = converted_f(*effective_args)

  File "C:\Users\spowers\AppData\Local\Temp\tmpul5sc0_r.py", line 45, in tf___to_tensors
    retval_ = _to_tensors_scope.mark_return_value(ag__.converted_call(ag__.converted_call(super, _to_tensors_scope.callopts, (OneHotMelodyConverter, self), None, _to_tensors_scope)._to_tensors, _to_tensors_scope.callopts, (note_sequence,), None, _to_tensors_scope))

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\impl\api.py", line 541, in converted_call
    result = converted_f(*effective_args)

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 351, in tf___to_tensors
    retval_, do_return = ag__.if_stmt(cond_15, if_true_15, if_false_15, get_state_20, set_state_20, ('retval_', 'do_return'), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 895, in if_stmt
    return _py_if_stmt(cond, body, orelse)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 1004, in _py_if_stmt
    return body() if cond else orelse()

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 345, in if_true_15
    retval__8, do_return_8 = ag__.if_stmt(cond_14, if_true_14, if_false_14, get_state_19, set_state_19, ('retval_', 'do_return'), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 895, in if_stmt
    return _py_if_stmt(cond, body, orelse)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 1004, in _py_if_stmt
    return body() if cond else orelse()

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 339, in if_true_14
    retval__7, do_return_7 = ag__.if_stmt(cond_13, if_true_13, if_false_13, get_state_18, set_state_18, ('retval_', 'do_return'), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 895, in if_stmt
    return _py_if_stmt(cond, body, orelse)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 1004, in _py_if_stmt
    return body() if cond else orelse()

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 333, in if_true_13
    retval__6, do_return_6 = ag__.if_stmt(cond_12, if_true_12, if_false_12, get_state_17, set_state_17, ('retval_', 'do_return'), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 895, in if_stmt
    return _py_if_stmt(cond, body, orelse)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 1004, in _py_if_stmt
    return body() if cond else orelse()

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 330, in if_false_12
    retval__5, do_return_5 = ag__.if_stmt(cond_11, if_true_11, if_false_11, get_state_16, set_state_16, ('retval_', 'do_return'), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 895, in if_stmt
    return _py_if_stmt(cond, body, orelse)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 1004, in _py_if_stmt
    return body() if cond else orelse()

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 322, in if_true_11
    ag__.for_stmt(unique_event_tuples_2, extra_test_1, loop_body_4, get_state_15, set_state_15, (), (), ())

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 339, in for_stmt
    return _py_for_stmt(iter_, extra_test, body, get_state, set_state, init_vars)

  File "C:\Users\<my_path>\lib\site-packages\tensorflow_core\python\autograph\operators\control_flow.py", line 348, in _py_for_stmt
    if extra_test is not None and not extra_test(*state):

  File "C:\Users\spowers\AppData\Local\Temp\tmpko31xktz.py", line 321, in extra_test_1
    return ag__.not_(do_return_5)

NameError: free variable 'do_return_5' referenced before assignment in enclosing scope
`

**Comment by adarob** [comment]
Which version of TF are you using?

**Comment by SamNPowers** [comment]
I tried on a few; my current build is using 1.15.0. I also tried rc3, hoping this was a strange tensorflow edge-case that got fixed, but to no avail.

**Comment by notwaldorf** [comment]
There seems to be a proThe problem is inside the TensorFlow autograph -- I have a workaround which we'll merge soon.

**Comment by laurens-in** [comment]
Any updates on that? Having the same problem with magenta-gpu.

**Comment by Elvenson** [comment]
I am using the latest magenta version (1.3.0) and still get the same problem. Is there any updates?

**Comment by willfenton** [comment]
Also having this error, tensorflow v1.15.2 and magenta v1.3.0

**Comment by willfenton** [comment]
I don't think that commit fixed the issue. I'm getting the same error with a fresh clone of the repo, tensorflow v1.15.2 and magenta v1.3.0. @adarob
