### ISSUE TITLE
OSError: sndfile library not found

### ISSUE THREAD

**Issue by momo1986** [tensorflow/magenta#1633]
Hello,

This problem happens in Windows10.

I tried to install the magenta without any error.

Looks like it will be OK.

Then I launch the magenta with 
`import magenta`

I got error:
```
2019-11-27 18:43:47.490983: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_100.dll
Traceback (most recent call last):
  File "E:\Users\admin\Anaconda3\envs\AI_Python3.7\lib\site-packages\soundfile.py", line 142, in <module>
    raise OSError('sndfile library not found')
OSError: sndfile library not found

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "e:\program files\magenta\magenta\__init__.py", line 34, in <module>
    import magenta.music.audio_io
  File "e:\program files\magenta\magenta\music\audio_io.py", line 23, in <module>
    import librosa
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\librosa\__init__.py", line 12, in <module>
    from . import core
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\librosa\core\__init__.py", line 124, in <module>
    from .audio import *  # pylint: disable=wildcard-import
  File "C:\Users\admin\AppData\Roaming\Python\Python37\site-packages\librosa\core\audio.py", line 10, in <module>
    import soundfile as sf
  File "E:\Users\admin\Anaconda3\envs\AI_Python3.7\lib\site-packages\soundfile.py", line 163, in <module>
    _path, '_soundfile_data', _libname))
OSError: cannot load library 'E:\Users\admin\Anaconda3\envs\AI_Python3.7\lib\site-packages\_soundfile_data\libsndfile64bit.dll': error 0x7e
```

I install libsndffile via Visual Studio Installation Package:

`.\vcpkg.exe install libsndfile:x86-windows-static`

Error still exists.

Thus, I want to discuss so that I can find the solution to resolve the problem.
Thanks & Regards!
Jun Yan

**Comment by momo1986** [comment]
This issue only happens on Windows, not on Linux.

I have not found a suitable workaround currently.

Is there any suitable comment?

Thanks & regards!
Jun Yan

**Comment by JuanuMusic** [comment]
Momo, the right way to make it work on windows 10, is by using the linux shell.
Install the ubuntu shell on your windows 10 (https://itsfoss.com/install-bash-on-windows/)

After that, follow the steps on setting up the magenta environment using conda or manual installation (https://github.com/tensorflow/magenta/blob/master/README.md), from the linux shell.

Hope it helps!
