### ISSUE TITLE
AttributeError: module 'magenta.music' has no attribute 'read_bundle_file'

### ISSUE THREAD

**Issue by dubreuia** [tensorflow/magenta#1638]
When using any of the RNN model (Drums RNN, Melody RNN, etc.) generate command, like:

```bash
drums_rnn_generate --config="drum_kit" --bundle_file="bundle.mag"
```

I get a stack:

```
Traceback (most recent call last):
  File "/home/alex/miniconda3/envs/magenta/bin/drums_rnn_generate", line 8, in <module>
    sys.exit(console_entry_point())
  File "/home/alex/miniconda3/envs/magenta/lib/python3.6/site-packages/magenta/models/drums_rnn/drums_rnn_generate.py", line 258, in console_entry_point
    tf.app.run(main)
  File "/home/alex/miniconda3/envs/magenta/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/alex/miniconda3/envs/magenta/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/alex/miniconda3/envs/magenta/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/alex/miniconda3/envs/magenta/lib/python3.6/site-packages/magenta/models/drums_rnn/drums_rnn_generate.py", line 228, in main
    bundle = get_bundle()
  File "/home/alex/miniconda3/envs/magenta/lib/python3.6/site-packages/magenta/models/drums_rnn/drums_rnn_generate.py", line 128, in get_bundle
    return magenta.music.read_bundle_file(bundle_file)
AttributeError: module 'magenta.music' has no attribute 'read_bundle_file'
```

Which is a new problem (I'm on Magenta 1.2.0) that was not in 1.1.7. I didn't bisect to find the exact commit that added the regression, but I think the merge "Merge pull request #1570 from cifkao:magenta-music Copybara-Service 20/11/2019 07:01" and commit 3ae5635e4ea2c2359145bddf70fd53528a955fd6 are at fault.

I'm working on a PR I'll send it soon, but you guys might want to check all the imports in the project for the magenta.music package.

**Comment by adarob** [comment]
Sorry for the issues, and thanks for the fixes!

**Comment by dubreuia** [comment]
No problem, thank you for making Magenta, amazing project by the way.

**Comment by AndrewRahman** [comment]
Hi! I'm still experiencing this issue with Magenta 1.2.0. Just updated from 0.5.0.

`(magenta) Andrews-MacBook-Air:~ andrewrahman$ BUNDLE_PATH=/Users/andrewrahman/Documents/Soulside/Magenta/Magenta/MagFiles/MelodyRNN/basic_rnn.mag
(magenta) Andrews-MacBook-Air:~ andrewrahman$ CONFIG='basic_rnn'
(magenta) Andrews-MacBook-Air:~ andrewrahman$ 
(magenta) Andrews-MacBook-Air:~ andrewrahman$ melody_rnn_generate \
> --config=${CONFIG} \
> --bundle_file=${BUNDLE_PATH} \
> --output_dir=/Users/andrewrahman/Desktop/Testing/Excited/Melody01/Temp1 \
> --num_outputs=10 \
> --num_steps=512 \
> --temperature=1 \
> --primer_midi=/Users/andrewrahman/Desktop/ExcitedPrimers/Melody01.mid
WARNING:tensorflow:From /anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py:250: The name tf.app.run is deprecated. Please use tf.compat.v1.app.run instead.

WARNING:tensorflow:From /anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py:221: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

W1210 17:03:00.819072 4592190912 module_wrapper.py:139] From /anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py:221: The name tf.logging.set_verbosity is deprecated. Please use tf.compat.v1.logging.set_verbosity instead.

Traceback (most recent call last):
  File "/anaconda3/envs/magenta/bin/melody_rnn_generate", line 8, in <module>
    sys.exit(console_entry_point())
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 250, in console_entry_point
    tf.app.run(main)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 223, in main
    bundle = get_bundle()
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 125, in get_bundle
    return magenta.music.read_bundle_file(bundle_file)
AttributeError: module 'magenta.music' has no attribute 'read_bundle_file'
(magenta) Andrews-MacBook-Air:~ andrewrahman$ 
`

**Comment by AndrewRahman** [comment]
I have added @dubreuia 's fixes but now I am getting this error:

ModuleNotFoundError: No module named 'magenta.protobuf'

Which I do not see an existing error for:

```
(magenta) Andrews-MacBook-Air:~ andrewrahman$ BUNDLE_PATH=/Users/andrewrahman/Documents/Soulside/Magenta/Magenta/MagFiles/MelodyRNN/basic_rnn.mag
(magenta) Andrews-MacBook-Air:~ andrewrahman$ CONFIG='basic_rnn'
(magenta) Andrews-MacBook-Air:~ andrewrahman$ 
(magenta) Andrews-MacBook-Air:~ andrewrahman$ melody_rnn_generate \
> --config=${CONFIG} \
> --bundle_file=${BUNDLE_PATH} \
> --output_dir=/Users/andrewrahman/Desktop/Testing/Excited/Melody01/Temp1 \
> --num_outputs=10 \
> --num_steps=512 \
> --temperature=1 \
> --primer_midi=/Users/andrewrahman/Desktop/ExcitedPrimers/Melody01.mid
Traceback (most recent call last):
  File "/anaconda3/envs/magenta/bin/melody_rnn_generate", line 5, in <module>
    from magenta.models.melody_rnn.melody_rnn_generate import console_entry_point
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 26, in <module>
    from magenta.models.shared import sequence_generator_bundle
  File "/anaconda3/envs/magenta/lib/python3.7/site-packages/magenta/models/shared/sequence_generator_bundle.py", line 17, in <module>
    from magenta.protobuf import generator_pb2
ModuleNotFoundError: No module named 'magenta.protobuf'
```

**Comment by AndrewRahman** [comment]
I fixed this by pulling directly from GitHub and replacing the 'magenta' folder in my Mac Air⁩ ▸ ⁨anaconda3⁩ ▸ ⁨envs⁩ ▸ ⁨magenta⁩ ▸ ⁨lib⁩ ▸ ⁨python3.7⁩⁩ ▸ site-packages with the GitHub 'magenta' folder. 
I don't think this an ideal fix as I tried to install using Anaconda (with many errors) and then was successfully able to install using command line without Anaconda, but it's working for now.

**Comment by adarob** [comment]
I'll update the pip package today.

**Comment by adarob** [comment]
Please try v1.2.1
