### ISSUE TITLE
cannot run shell script, error:"__init__() got an unexpected keyword argument 'state_is_tuple'"

### ISSUE THREAD

**Issue by jeffehobbs** [tensorflow/magenta#164]
Tested on two different Ubuntu 16.04 machines, same error. I run through the directions exactly and get this error:

`jeff@elephantbird:~/magenta/magenta/models/basic_rnn$ ./run_basic_rnn_train.sh $EXPERIMENT_DIR $HYPERPARAMETER_STRING $NUM_TRAINING_STEPS $TRAIN_DATA [$EVAL_DATA]
INFO: Found 1 target...
Target //magenta/models/basic_rnn:basic_rnn_train up-to-date:
  bazel-bin/magenta/models/basic_rnn/basic_rnn_train
INFO: Elapsed time: 0.326s, Critical Path: 0.00s
INFO:tensorflow:hparams = {'rnn_layer_sizes': [50], 'decay_rate': 0.85, 'dropout_keep_prob': 0.5, 'batch_size': 128, 'decay_steps': 1000, 'clip_norm': 5, 'initial_learning_rate': 0.01, 'skip_first_n_losses': 0}
INFO:tensorflow:hparams = {'rnn_layer_sizes': [50], 'decay_rate': 0.85, 'dropout_keep_prob': 0.5, 'batch_size': 128, 'decay_steps': 1000, 'clip_norm': 5, 'initial_learning_rate': 0.01, 'skip_first_n_losses': 0}
Traceback (most recent call last):
  File "/home/jeff/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 49, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/jeff/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 45, in main
    Starting TensorBoard 16 on port 6006
(You can navigate to http://0.0.0.0:6006)
Traceback (most recent call last):
  File "/home/jeff/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 49, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/jeff/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 45, in main
    melody_rnn_train.run(melody_encoder_decoder, basic_rnn_graph.build_graph)
  File "/home/jeff/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/shared/melody_rnn_train.py", line 206, in run
melody_rnn_train.run(melody_encoder_decoder, basic_rnn_graph.build_graph)
  File "/home/jeff/magenta/bazel-bin/magenta/models/basic_rnn/basic_rnn_train.runfiles/__main__/magenta/models/shared/melody_rnn_train.py", line 206, in run
    FLAGS.sequence_example_file)
  File "/home/jeff/magenta/magenta/models/basic_rnn/basic_rnn_graph.py", line 88, in build_graph
    FLAGS.sequence_example_file)
  File "/home/jeff/magenta/magenta/models/basic_rnn/basic_rnn_graph.py", line 88, in build_graph
    num_units, state_is_tuple=state_is_tuple)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'
    num_units, state_is_tuple=state_is_tuple)
TypeError: __init__() got an unexpected keyword argument 'state_is_tuple'
`

Any clues? Thanks.

**Comment by cghawthorne** [comment]
Hi @jeffehobbs. What version of tensorflow do you have installed when you see this error?

**Comment by jeffehobbs** [comment]
Good call. Updating to the latest version (r0.10) seems to have ditched the error. Thanks!
