### ISSUE TITLE
AttributeError: module 'magenta.music' has no attribute 'BaseSequenceGenerator'

### ISSUE THREAD

**Issue by Yogurt928** [tensorflow/magenta#1643]
Hi everyone,

I try to follow this step:[ https://github.com/tensorflow/magenta-demos/tree/master/ai-jam-js]( https://github.com/tensorflow/magenta-demos/tree/master/ai-jam-js)
when run the RUN_DEMO.sh, I got this error:

Traceback (most recent call last):
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yujx\AppData\Local\Continuum\anaconda3\Scripts\midi_clock.exe\__main__.py", line 9, in <module>
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\interfaces\midi\midi_clock.py", line 77, in console_entry_point
    tf.app.run(main)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\absl\app.py", line 300, in run
    _run_main(main, args)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\absl\app.py", line 251, in _run_main
    sys.exit(main(argv))
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\interfaces\midi\midi_clock.py", line 55, in main
    None, FLAGS.output_ports.split(','), midi_hub.TextureType.MONOPHONIC)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\interfaces\midi\midi_hub.py", line 933, in __init__
    outports.append(mido.open_output(port, virtual=virtual))
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\mido\backends\backend.py", line 111, in open_output
    return self.module.Output(name, **self._add_api(kwargs))
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\mido\ports.py", line 269, in __init__
    BasePort.__init__(self, name, **kwargs)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\mido\ports.py", line 88, in __init__
    self._open(**kwargs)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\mido\backends\rtmidi.py", line 233, in _open
    virtual=virtual, api=self.api)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\mido\backends\rtmidi.py", line 120, in _open_port
    rt.open_virtual_port(name)
  File "src\_rtmidi.pyx", line 472, in rtmidi._rtmidi.MidiBase.open_virtual_port
NotImplementedError: Virtual ports are not supported by the Windows MultiMedia API.
Traceback (most recent call last):
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yujx\AppData\Local\Continuum\anaconda3\Scripts\magenta_midi.exe\__main__.py", line 5, in <module>
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\interfaces\midi\magenta_midi.py", line 35, in <module>
    from magenta.models.pianoroll_rnn_nade import pianoroll_rnn_nade_sequence_generator
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\models\pianoroll_rnn_nade\pianoroll_rnn_nade_sequence_generator.py", line 24, in <module>
    class PianorollRnnNadeSequenceGenerator(mm.BaseSequenceGenerator):
AttributeError: module 'magenta.music' has no attribute 'BaseSequenceGenerator'
Traceback (most recent call last):
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\yujx\AppData\Local\Continuum\anaconda3\Scripts\magenta_midi.exe\__main__.py", line 5, in <module>
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\interfaces\midi\magenta_midi.py", line 35, in <module>
    from magenta.models.pianoroll_rnn_nade import pianoroll_rnn_nade_sequence_generator
  File "c:\users\yujx\appdata\local\continuum\anaconda3\lib\site-packages\magenta\models\pianoroll_rnn_nade\pianoroll_rnn_nade_sequence_generator.py", line 24, in <module>
    class PianorollRnnNadeSequenceGenerator(mm.BaseSequenceGenerator):
AttributeError: module 'magenta.music' has no attribute 'BaseSequenceGenerator'

So I search the file **__init__.py** under magenta\music:
[https://github.com/tensorflow/magenta/blob/master/magenta/music/__init__.py](https://github.com/tensorflow/magenta/blob/master/magenta/music/__init__.py)
it does not contain this attribute: 'BaseSequenceGenerator'

Is any step wrong?

**Comment by adarob** [comment]
Please try v1.2.1.
