### ISSUE TITLE
Whenever i am trying to restore weights from checkpoint, it gives this  error "NotFoundError: Restoring from checkpoint failed. This is most likely due to a Variable name or other graph key that is missing from the checkpoint  "

### ISSUE THREAD

**Issue by maliktalha370** [tensorflow/magenta#1647]

**Comment by SarthakSG** [comment]
This issue can be fixed by renaming the variables in the checkpoint :
"fully_connected/weights" to "rnn_model/fully_connected/weights"
"fully_connected/biases" to "rnn_model/fully_connected/bias "

**Comment by attardi** [comment]
I have a similar problem running

    t2t_trainer --hparams=label_smoothing=0.0,max_length=0,max_target_seq_length=2048 --hparams_set=score2perf_transformer_base --model=transformer --problem=score2perf_maestro_language_uncropped_aug

    I0721 21:07:22.561720 140600872367936 saver.py:1293] Restoring parameters from maestro/training/model.ckpt-1000
    2020-07-21 21:07:22.727872: W tensorflow/core/framework/op_kernel.cc:1753] OP_REQUIRES failed at save_restore_v2_ops.cc:184 : Not found: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1365, in _do_call
    return fn(*args)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1350, in _run_fn
    target_list, run_metadata)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1443, in _call_tf_sessionrun
    run_metadata)
    tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
      (0) Not found: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
    	 [[{{node save/RestoreV2_1}}]]
    	 [[save/RestoreV2_1/_101]]
      (1) Not found: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
	 [[{{node save/RestoreV2_1}}]]
    0 successful operations.
    0 derived errors ignored.

    During handling of the above exception, another exception occurred:
    Traceback (most recent call last):
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/training/saver.py", line 1299, in restore
    {self.saver_def.filename_tensor_name: save_path})
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 958, in run
    run_metadata_ptr)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1181, in _run
    feed_dict_tensor, options, run_metadata)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1359, in _do_run
    run_metadata)
      File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/client/session.py", line 1384, in _do_call
    raise type(e)(node_def, op, message)
    tensorflow.python.framework.errors_impl.NotFoundError: 2 root error(s) found.
      (0) Not found: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
	 [[node save/RestoreV2_1 (defined at usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1643) ]]
	 [[save/RestoreV2_1/_101]]
      (1) Not found: Key transformer/parallel_0_3/transformer/transformer/body/decoder/layer_0/self_attention/multihead_attention/k/kernel not found in checkpoint
	 [[node save/RestoreV2_1 (defined at usr/local/lib/python3.6/dist-packages/tensorflow_estimator/python/estimator/estimator.py:1643) ]]
    0 successful operations.
    0 derived errors ignored.

Strangely enough, if I repeat the command, it is able to complete the checkpoint:

    I0721 19:57:16.328476 139716674180928 basic_session_run_hooks.py:613] Saving checkpoints for 1000 into maestro/training/model.ckpt.
    2020-07-21 19:57:19.531857: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcublas.so.10
    I0721 19:57:22.036410 139716674180928 basic_session_run_hooks.py:262] loss = 4.03043, step = 1000
    I0721 19:57:43.517246 139716674180928 basic_session_run_hooks.py:700] global_step/sec: 4.65139
    I0721 19:57:43.518301 139716674180928 basic_session_run_hooks.py:260] loss = 3.5795429, step = 1100 (21.482 sec)
    I0721 19:57:59.702682 139716674180928 basic_session_run_hooks.py:700] global_step/sec: 6.17837

but it fails again at the next checkpoint after each 1000 steps.

Any help appreciated.

**Comment by adarob** [comment]
@attardi can you try installing tensorflow 1.15 and see if it works? You can do this with `pip install "tensorflow==1.15.*"`
