### ISSUE TITLE
Improv RNN says AssertionError  when give qpm lower than equal 69

### ISSUE THREAD

**Issue by ayapi** [tensorflow/magenta#1679]
Hello,

```
improv_rnn_generate ^
        --config=basic_improv ^
        --bundle_file=C:\Users\username\Documents\Magenta\PreTrained\chord_pitches_improv.mag ^
        --output_dir=C:\Users\username\generated ^
        --num_outputs=1 ^
        --backing_chords="Am Dm Am E9" ^
        --qpm=69
```

```
Traceback (most recent call last):
  File "c:\users\username\.conda\envs\magenta\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "c:\users\username\.conda\envs\magenta\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\username\.conda\envs\magenta\Scripts\improv_rnn_generate.exe\__main__.py", line 7, in <module>
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\magenta\models\improv_rnn\improv_rnn_generate.py", line 280, in console_entry_point
    tf.app.run(main)
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\tensorflow_core\python\platform\app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\absl\app.py", line 299, in run
    _run_main(main, args)
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\absl\app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\magenta\models\improv_rnn\improv_rnn_generate.py", line 276, in main
    run_with_flags(generator)
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\magenta\models\improv_rnn\improv_rnn_generate.py", line 232, in run_with_flags
    generated_sequence = generator.generate(input_sequence, generator_options)
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\magenta\music\sequence_generator.py", line 194, in generate
    return self._generate(input_sequence, generator_options)
  File "c:\users\username\.conda\envs\magenta\lib\site-packages\magenta\models\improv_rnn\improv_rnn_sequence_generator.py", line 136, in _generate
    assert chords.end_step == end_step
AssertionError
```

No problem when i give `qpm=70`.
The same error occures when I give `qpm=68`.

**Comment by ayapi** [comment]
0 = success
1 = failed

| qpm | result |
| --- | ---- |
|50|0|
|51|0|
|52|0|
|53|1|
|54|0|
|55|1|
|56|0|
|57|1|
|58|0|
|59|1|
|60|0|
|61|1|
|62|0|
|63|0|
|64|0|
|65|0|
|66|0|
|67|0|
|68|1|
|69|1|
|70|0|
|71|0|
|72|0|
|73|1|
|74|0|
|75|0|
|76|0|
|77|0|
|78|0|
|79|0|
|80|0|
|81|0|
|82|0|
|83|0|
|84|0|
|85|0|
|86|0|
|87|0|
|88|1|
|89|0|
|90|0|
|91|1|
|92|0|
|93|0|
|94|0|
|95|1|
|96|0|
|97|0|
|98|0|
|99|0|
|100|0|
|101|0|
|102|0|
|103|1|
|104|0|
|105|0|
|106|1|
|107|0|
|108|0|
|109|0|
|110|1|
|111|0|
|112|0|
|113|0|
|114|1|
|115|0|
|116|0|
|117|1|
|118|1|
|119|0|
|120|0|
|121|0|
|122|1|
|123|1|
|124|0|
|125|0|
|126|0|
|127|0|
|128|0|
|129|0|
|130|0|
|131|1|
|132|0|
|133|0|
|134|0|
|135|0|
|136|1|
|137|0|
|138|1|
|139|0|
|140|0|
|141|0|
|142|0|
|143|0|
|144|0|
|145|1|
|146|1|
|147|0|
|148|0|
|149|0|
|150|0|

**Comment by iansimon** [comment]
It seems to be a quantization issue.  I'll look into it if I get a chance but for now I recommend picking a tempo that works (it won't have any effect on the model) and changing to the tempo you want afterwards.
