### ISSUE TITLE
 Error when train Onsets and Frames

### ISSUE THREAD

**Issue by ThorPham** [tensorflow/magenta#1689]
I download pre-generated copy of the TFRecord  onsets_frames_dataset_maestro_v1.0.0.zip and want to train model :
systax :  **onsets_frames_transcription_train --example_path=onsets_frames_dataset_maestro_v1.0.0/ --model_dir=train_check_point --mode='train'**
but has error : 
INFO:tensorflow:Writing summary for examples_path: None
I0330 00:26:05.717337 139996419872576 train_util.py:54] Writing summary for examples_path: None
Traceback (most recent call last):
  File "/home/thorpham/anaconda3/envs/piano/bin/onsets_frames_transcription_train", line 8, in <module>
    sys.exit(console_entry_point())
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 123, in console_entry_point
    tf.app.run(main)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/tensorflow_core/python/platform/app.py", line 40, in run
    _run(main=main, argv=argv, flags_parser=_parse_flags_tolerate_undef)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 119, in main
    additional_trial_info=additional_trial_info)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/magenta/models/onsets_frames_transcription/onsets_frames_transcription_train.py", line 96, in run
    num_steps=FLAGS.num_steps)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/magenta/models/onsets_frames_transcription/train_util.py", line 140, in train
    additional_trial_info=additional_trial_info)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/magenta/models/onsets_frames_transcription/train_util.py", line 56, in _trial_summary
    tf.summary.text(name, tf.constant(summary, name=name),
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 161, in constant_v1
    allow_broadcast=False)
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/tensorflow_core/python/framework/constant_op.py", line 265, in _constant_impl
    allow_broadcast=allow_broadcast))
  File "/home/thorpham/anaconda3/envs/piano/lib/python3.6/site-packages/tensorflow_core/python/framework/tensor_util.py", line 438, in make_tensor_proto
    raise ValueError("None values not supported.")
ValueError: None values not supported.

I don't know why examples_path  is None
Anyone help me fix error. Thank so much

**Comment by cghawthorne** [comment]
I think you misspelled `--examples_path` in your command line (forgot the 's' on examples).
