### ISSUE TITLE
Errors when running bazel tests

### ISSUE THREAD

**Issue by jsawruk** [tensorflow/magenta#169]
When I run the bazel tests, I get the following errors:

```
INFO: Found 45 targets and 10 test targets...
FAIL: //magenta/lib:midi_io_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/midi_io_test/test.log).
FAIL: //magenta/lib:melodies_lib_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/melodies_lib_test/test.log).
FAIL: //magenta/pipelines:pipelines_common_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipelines_common_test/test.log).
FAIL: //magenta/scripts:convert_midi_dir_to_note_sequences_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log).
FAIL: //magenta/pipelines:dag_pipeline_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/dag_pipeline_test/test.log).
FAIL: //magenta/pipelines:pipeline_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipeline_test/test.log).
FAIL: //magenta/lib:note_sequence_io_test (see /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log).
INFO: Elapsed time: 4.452s, Critical Path: 4.28s
//magenta/lib:sequences_lib_test                                (cached) PASSED in 2.0s
//magenta/models/shared:melody_rnn_create_dataset_test          (cached) PASSED in 2.6s
//magenta/pipelines:statistics_test                             (cached) PASSED in 3.3s
//magenta/lib:melodies_lib_test                                          FAILED in 2.3s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/melodies_lib_test/test.log
//magenta/lib:midi_io_test                                               FAILED in 0.1s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/midi_io_test/test.log
//magenta/lib:note_sequence_io_test                                      FAILED in 2.0s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/lib/note_sequence_io_test/test.log
//magenta/pipelines:dag_pipeline_test                                    FAILED in 2.5s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/dag_pipeline_test/test.log
//magenta/pipelines:pipeline_test                                        FAILED in 2.6s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipeline_test/test.log
//magenta/pipelines:pipelines_common_test                                FAILED in 2.3s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/pipelines/pipelines_common_test/test.log
//magenta/scripts:convert_midi_dir_to_note_sequences_test                FAILED in 2.4s
  /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log

Executed 7 out of 10 tests: 3 tests pass and 7 fail locally.
There were tests whose specified size is too big. Use the --test_verbose_timeout_warnings command line option to see which ones these are.
```

I am on OS X 10.11.6, Python 3.5.2, and installed bazel with brew and TensorFlow with pip3.

**Comment by cghawthorne** [comment]
Can you post the contents of one of those failed test logs?

Also, what do you see when you run 'bazel version'?

**Comment by jsawruk** [comment]
Bazel version:
```
bazel version
Build label: 0.3.1-homebrew
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Aug 4 09:58:27 2016 (1470304707)
Build timestamp: 1470304707
Build timestamp as int: 1470304707
```

Output of one of the failed test logs:
```
cat /private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/testlogs/magenta/scripts/convert_midi_dir_to_note_sequences_test/test.log
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
-----------------------------------------------------------------------------
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/__main__/magenta/scripts/convert_midi_dir_to_note_sequences_test.py", line 23, in <module>
    from magenta.scripts import convert_midi_dir_to_note_sequences
  File "/private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/__main__/magenta/scripts/convert_midi_dir_to_note_sequences.py", line 30, in <module>
    from magenta.lib import midi_io
  File "/private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/__main__/magenta/lib/midi_io.py", line 29, in <module>
    import pretty_midi
  File "/private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/pretty_midi/__init__.py", line 1, in <module>
    from .pretty_midi import *
  File "/private/var/tmp/_bazel_jsawruk/e6e065222e08ffdd42d29a3881482d1d/execroot/magenta/bazel-out/local-opt/bin/magenta/scripts/convert_midi_dir_to_note_sequences_test.runfiles/pretty_midi/pretty_midi.py", line 938
    'Set Tempo': lambda(e): (1 * 256 * 256),
                       ^
SyntaxError: invalid syntax
```

**Comment by cghawthorne** [comment]
Oh, sorry, I didn't notice in your first post that you're using Python 3. Unfortunately, we currently only support Python 2. I'll update our docs to reflect that.

**Comment by jsawruk** [comment]
Ok thanks. Since Tensorflow is on both Python 2 and Python 3, I installed Tensorflow using Python 3 and just assumed Magenta would work on that. I didn't realize Magenta only worked on Python 2.

**Comment by jsawruk** [comment]
I'm still getting these errors even in Python 2.7. I set up an Anaconda environment following these instructions: https://www.tensorflow.org/versions/r0.10/get_started/os_setup.html#anaconda-installation

I then did `bazel clean` before re-running the tests. I get the exact same errors as before, including the error in the log file.

My python version is: Python 2.7.12 :: Continuum Analytics, Inc.

**Comment by cghawthorne** [comment]
Can you paste the errors you're getting now? Is it the same syntax error? If so, that would indicate that Python 3 is still being used.

Bazel clears some environment variables before running tests to attempt to get a hermetic build/test environment. It's possible that's messing up your anaconda installation. Would it be possible to install Python 2.7 as your system default Python?

**Comment by jsawruk** [comment]
Yes, I think there was a problem with my Anaconda configuration. I just tested it again right now and it is working. Thanks.
