### ISSUE TITLE
Error with attention_rnn_generate (unreferenced attribute)

### ISSUE THREAD

**Issue by Conchylicultor** [tensorflow/magenta#180]
It seems there is an error in the `MelodyEncoderDecoder.class_index_to_melody_event()` method: the variable `self.num_model_events` is used (on `attention_rnn_encoder_decoder.py`, line 222) without being declared elsewhere. It may be a legacy variable.

Command run:
```
bazel run //magenta/models/attention_rnn:attention_rnn_generate -- \
--run_dir=/tmp/attention_rnn/logdir/run1 \
--hparams="{'batch_size':64,'rnn_layer_sizes':[64,64]}" \
--output_dir=/tmp/attention_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"
```

Traceback:
```
Traceback (most recent call last):
  File "/home/pot/.cache/bazel/_bazel_pot/5fc7cd7a555a3767114962921a1b913d/execroot/magenta/bazel-out/local-opt/bin/magenta/models/attention_rnn/attention_rnn_generate.runfiles/__main__/magenta/models/attention_rnn/attention_rnn_generate.py", line 45, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/pot/.cache/bazel/_bazel_pot/5fc7cd7a555a3767114962921a1b913d/execroot/magenta/bazel-out/local-opt/bin/magenta/models/attention_rnn/attention_rnn_generate.runfiles/__main__/magenta/models/attention_rnn/attention_rnn_generate.py", line 41, in main
    melody_rnn_generate.run_with_flags(generator)
  File "/home/pot/.cache/bazel/_bazel_pot/5fc7cd7a555a3767114962921a1b913d/execroot/magenta/bazel-out/local-opt/bin/magenta/models/attention_rnn/attention_rnn_generate.runfiles/__main__/magenta/models/shared/melody_rnn_generate.py", line 192, in run_with_flags
    generate_request)
  File "/home/pot/.cache/bazel/_bazel_pot/5fc7cd7a555a3767114962921a1b913d/execroot/magenta/bazel-out/local-opt/bin/magenta/models/attention_rnn/attention_rnn_generate.runfiles/__main__/magenta/lib/sequence_generator.py", line 136, in generate
    return self._generate(generate_sequence_request)
  File "/home/pot/.cache/bazel/_bazel_pot/5fc7cd7a555a3767114962921a1b913d/execroot/magenta/bazel-out/local-opt/bin/magenta/models/attention_rnn/attention_rnn_generate.runfiles/__main__/magenta/models/shared/melody_rnn_sequence_generator.py", line 165, in _generate
    self._melody_encoder_decoder.extend_melodies([melody], softmax_)
  File "/home/pot/.cache/bazel/_bazel_pot/5fc7cd7a555a3767114962921a1b913d/execroot/magenta/bazel-out/local-opt/bin/magenta/models/attention_rnn/attention_rnn_generate.runfiles/__main__/magenta/lib/melodies_lib.py", line 954, in extend_melodies
    melody_event = self.class_index_to_melody_event(chosen_class, melodies[i])
  File "/home/pot/__A__/Development/AI/magenta/magenta/models/attention_rnn/attention_rnn_encoder_decoder.py", line 222, in class_index_to_melody_event
    if class_index == self.num_model_events + i:
AttributeError: 'MelodyEncoderDecoder' object has no attribute 'num_model_events'
```

The only other place the variable is referenced is on `lookback_rnn_encoder_decoder.py `

Edit: The error seems to came from this commit: https://github.com/tensorflow/magenta/commit/eb4e71acb3b93c9983cf69b4b2428e06924e0cc7#diff-05b7ae22d66de3b23021d1007bc70af1R222

**Comment by adarob** [comment]
Fixed in https://github.com/tensorflow/magenta/pull/179. Thanks!
