### ISSUE TITLE
All tests fail

### ISSUE THREAD

**Issue by neale** [tensorflow/magenta#229]
Hi everyone, I'm running magenta and trying to simply install it. All the tests fail locally with bazel. 
* virtualenv tensorflow 0.10, 
* bazel 0.3.1, 
* python 2.7
* OS X 10.11 - GPU
* CUDNN v5, and CUDA 7.5

Tensorflow imports and runs fine on the GPU. 
When I try to run the magenta tests I get a total failure. 
The logs all look like this
```
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_EnRatz/ff3e5bd3f6602e5c161954fd8b97e695/execroot/magenta/bazel-out/local-opt/bin/magenta/models/shared/melody_rnn_graph_test.runfiles/__main__/magenta/models/shared/melody_rnn_graph_test.py", line 17, in <module>
    import tensorflow as tf
  File "/Users/EnRatz/repos/tensorflow/lib/python2.7/site-packages/tensorflow/__init__.py", line 23, in <module>
    from tensorflow.python import *
  File "/Users/EnRatz/repos/tensorflow/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 48, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/EnRatz/repos/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 28, in <module>
    _pywrap_tensorflow = swig_import_helper()
  File "/Users/EnRatz/repos/tensorflow/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow', fp, pathname, description)
ImportError: dlopen(/Users/EnRatz/repos/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so, 10): Library not loaded: @rpath/libcudart.7.5.dylib
  Referenced from: /Users/EnRatz/repos/tensorflow/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow.so
  Reason: image not found
```
So libcudart is not found, but I've linked it correctly here per Tensorflow's directions
```
echo $DYLD_LIBRARY_PATH
/Developer/NVIDIA/CUDA-7.5/lib:/usr/local/cuda/lib:/usr/local/cuda/lib:/Users/EnRatz/torch/install/lib:

echo $CUDA_HOME                  
/usr/local/cuda

 ls /usr/local/cuda/lib | grep libcudart 
libcudart.7.5.dylib
libcudart.dylib
```

I've heard that bazel might strip some environment variables, so I tried running a single test
``` bazel test //magenta/music:events_lib_test ``` and it returns the same test.log

I tried running a  CPU version, and that works just fine with the same software installed. 
I've also tried bazel 0.2.3, and it returned the same results. 

I'd appreciate some help, I've been at this for a while

**Comment by neale** [comment]
I'll close this. After 5 consecutive cleans and rebuilds, all the tests passed. There is no sane reason for this, and I am certain no definitive solution exists to deal with Bazel.
