### ISSUE TITLE
Is it expected for --primer_midi to fail with polyphonic file?

### ISSUE THREAD

**Issue by brannondorsey** [tensorflow/magenta#296]
Hi, I am experiencing an error when I try to run `melody_rnn_generate` and passing a polyphonic midi file to `--primer_midi`:

```
Traceback (most recent call last):
  File "/home/brannondorsey/miniconda2/envs/magenta/bin/melody_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/brannondorsey/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 235, in console_entry_point
    tf.app.run(main)
  File "/home/brannondorsey/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/brannondorsey/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 231, in main
    run_with_flags(generator)
  File "/home/brannondorsey/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 208, in run_with_flags
    generated_sequence = generator.generate(input_sequence, generator_options)
  File "/home/brannondorsey/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 226, in generate
    return self._generate(input_sequence, generator_options)
  File "/home/brannondorsey/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_sequence_generator.py", line 126, in _generate
    assert len(extracted_melodies) <= 1
AssertionError
```

Can anyone confirm if this is indeed because the file has more than one instrument and therefore melody and so `melody_rnn_generate` simply refuses to process the file? If this is in fact the case a friendly error message might be helpful to new users. Or at least some documentation in the `--primer_midi` flag description that specifies that the file must be monophonic. I am happy to take a stab at adding this but I wanted to make sure that this is indeed the case before doing so.

More about magenta + polyphonic [here](https://github.com/tensorflow/magenta/issues/123).

Cheers,
Brannon

**Comment by cghawthorne** [comment]
Hi Brannon,

The file doesn't need to be monophonic, but it does need to have at least 1 track that is monophonic so our melody extractor can find something that looks like a melody. There's a bit more information about how this works here: https://github.com/tensorflow/magenta/blob/master/magenta/music/melodies_lib.py#L522

We'd be happy to accept a pull request with better docs or improved error messages!

**Comment by brannondorsey** [comment]
Ah, ok great, thanks! I'll see if I can devote a bit of time in the coming days to dig in and perhaps submit a PR.

**Comment by brannondorsey** [comment]
Hi @cghawthorne ,

I've spent a few hours this afternoon getting a the Magenta dev environment setup and poking around the code base. It seems to me that the assertion error [here](https://github.com/tensorflow/magenta/blob/e1a4eebbac6cbce8a58beefc5152030a4af7a05a/magenta/models/melody_rnn/melody_rnn_sequence_generator.py#L95) (mentioned above) is not actually "because at least one track needs to be monophonic", __but rather__ there cannot be more than one track that has an extractable monophonic melody. 

I've tested this theory by running `melody_rnn_generate` on a MIDI file that I have constructed with two monophonic tracks. When I do this I get the above assertion error: `assert len(extracted_melodies) <= 1`. However, if I remove one of these two tracks (thus setting the length of `evaluated_melodies` to 1 instead of 2), I get no error and a midi file is generated correctly. I've tested this with multiple midi files and it consistently fails whenever there is more than one track with a monophonic melody (which does seem to be what the assert is testing for) present in the file. 

I've made what appear to be the necessary changes to 1) provide an error message to the user as to why their `melody_rnn_generate` command is failing if they are trying to prime from a midi file with more than one track, and 2) updates the melody_rnn/README to notify users of this current limitation. You can preview these changes in [this commit](https://github.com/brannondorsey/magenta/commit/2181af5238714bb92d6e1996fb952ea1fd01c965).

I have yet to submit a PR because I want to confirm that my observations are correct, especially as they contradict your description of the error.

If this seems good let me know and I will submit the PR from [this branch](https://github.com/brannondorsey/magenta/tree/issue-296), otherwise maybe you could provide some further insight?

Thanks!

**Comment by cghawthorne** [comment]
Thanks for digging into this! Your understanding seems correct to me. @danabo (who originally wrote the melody extractor), can you take a look at this too and see if this is correct?

Also adding @adarob and @elliotwaite who have worked on this code before.

Also, do any of you have thoughts on whether we should change this logic? Or just improve the error message?

**Comment by danabo** [comment]
melody extractor will accept polyphonic tracks in its default mode. it looks like the problem here is that the generator is asserting that there is no more than 1 melody extracted. "assert len(extracted_melodies) <= 1"

An easy fix would be to remove the assertion and just pick the first melody to generate from. Maybe also display a warning that there are other melodies which will not be used.

**Comment by brannondorsey** [comment]
How about a flag (e.g. '--primer_midi_track 1') to specify which track to extract melodies from and use the first track if this track is not specified?

**Comment by cghawthorne** [comment]
That sounds good to me!

**Comment by brannondorsey** [comment]
Great, I'm a bit swamped this week but should be able to get on this and hopefully make a PR by early next week.

**Comment by jellysquider** [comment]
Hello,

I just spend the whole night installing and re-installing environments and finally I found this issue and realized that it is the bug of the 0.1.6 version since a couple of days ago 0.1.4 worked for me perfectly. 

Anyhow, when trying to generate magenta using pre-trained model:

```
(magenta) Gabrielas-Mac-Pro:~ govi$ melody_rnn_generate \
> --config=basic_rnn \
> --bundle_file=//miniconda/envs/magenta/models/melody_rnn/basic_rnn.mag \
> --output_dir=//miniconda/generated \
> --num_outputs=10 \
> --num_steps=128 \
> --primer_melody="[60]"
```
I get the following:
> 
> Traceback (most recent call last):
>   File "/Users/govi/miniconda2/envs/magenta/bin/melody_rnn_generate", line 11, in <module>
>     sys.exit(console_entry_point())
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 256, in console_entry_point
>     tf.app.run(main)
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
>     sys.exit(main(sys.argv[:1] + flags_passthrough))
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 245, in main
>     bundle=get_bundle())
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 129, in get_bundle
>     return magenta.music.read_bundle_file(bundle_file)
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/sequence_generator_bundle.py", line 34, in read_bundle_file
>     bundle.ParseFromString(f.read())
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 101, in read
>     compat.as_bytes(self.__name), status)
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/contextlib.py", line 24, in __exit__
>     self.gen.next()
>   File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/errors.py", line 463, in raise_exception_on_not_ok_status
>     pywrap_tensorflow.TF_GetCode(status))
> tensorflow.python.framework.errors.NotFoundError: //miniconda/envs/magenta/models/melody_rnn/basic_rnn.mag

At first I thought that the Development Environment I established earlier was interfering with it since I got the same problem after the bazel test and when building pip package from magenta, but after de-installing everything and installing everything from scratch, it didn't work either. I even tried to download 0.1.4 version of magenta, but when I do `pip install magenta` obviously it generates new file `melody_rnn_generate.py` which I think might cause the problem.

**Comment by cghawthorne** [comment]
@jellysquider From the error message, it looks like the bundle file doesn't exist at the path you supplied (`/miniconda/envs/magenta/models/melody_rnn/basic_rnn.mag`). Can you check where that file is saved and try again?

Also, if you continue to have this problem, can you open a new issue? I'd like to keep this issue dedicated to discussing @brannondorsey's ideas around priming sequences.

**Comment by jellysquider** [comment]
okay, I entered the absolute path and it worked.
Thanks and sorry about that.

**Comment by yell0w4x** [comment]
Looks like things are at the same point since I get  `assert len(extracted_melodies) <= 1`?
