### ISSUE TITLE
Image_stylization error :IndexError: index 1 is out of bounds for axis 0 with size 1

### ISSUE THREAD

**Issue by rupeshs** [tensorflow/magenta#384]
I tried on Ubuntu 14 (64bit)
(magenta) rupesh@rupesh-VirtualBox:~/miniconda2/bin$ sudo python image_stylization_transform.py --numstyles=10 --checkpoint=multistyle-pastiche-generator-monet.ckpt --input_image=dk.jpg --which_styles="{0:0.1,1:0.1,2:0.1,3:0.1,4:0.1,5:0.1,6:0.1,7:0.1,8:0.1,9:0.1}" --output_dir=/home/rupesh/miniconda2/bin/out --output_basename="all_monet_styles"
OpenBLAS : Your OS does not support AVX instructions. OpenBLAS is using Nehalem kernels as a fallback, which may give poorer performance.
Traceback (most recent call last):
  File "image_stylization_transform.py", line 148, in <module>
    console_entry_point()
  File "image_stylization_transform.py", line 144, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "image_stylization_transform.py", line 137, in main
    _multiple_styles(image, which_styles, output_dir)
  File "image_stylization_transform.py", line 106, in _multiple_styles
    mixture = _style_mixture(which_styles, FLAGS.num_styles)
  File "image_stylization_transform.py", line 80, in _style_mixture
    mixture[index] = which_styles[index]
IndexError: index 1 is out of bounds for axis 0 with size 1

**Comment by jveres** [comment]
Try with `--num_styles` instead of `--numstyles`. It should work.

**Comment by rupeshs** [comment]
@jveres  thanks it just worked :+1:
