### ISSUE TITLE
bazel run ERROR: Non-zero return code '1'

### ISSUE THREAD

**Issue by jellysquider** [tensorflow/magenta#386]
Hello again,

When I tried to run:

`(magenta) Gabrielas-Mac-Pro:magenta govi$ bazel run //magenta/models/melody_rnn:melody_rnn_generate -- --config=lookback_rnn
`

I've got:
```
INFO: Found 1 target...
Target //magenta/models/melody_rnn:melody_rnn_generate up-to-date:
  bazel-bin/magenta/models/melody_rnn/melody_rnn_generate
INFO: Elapsed time: 1.248s, Critical Path: 0.01s

INFO: Running command line: bazel-bin/magenta/models/melody_rnn/melody_rnn_generate '--config=lookback_rnn'
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_govi/1b0a93acf20f8815b4aabd701350aefe/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 260, in <module>
    console_entry_point()
  File "/private/var/tmp/_bazel_govi/1b0a93acf20f8815b4aabd701350aefe/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 256, in console_entry_point
    tf.app.run(main)
  File "/Users/govi/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/private/var/tmp/_bazel_govi/1b0a93acf20f8815b4aabd701350aefe/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 245, in main
    bundle=get_bundle())
  File "/private/var/tmp/_bazel_govi/1b0a93acf20f8815b4aabd701350aefe/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_sequence_generator.py", line 42, in __init__
    model, details, checkpoint, bundle)
  File "/private/var/tmp/_bazel_govi/1b0a93acf20f8815b4aabd701350aefe/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/music/sequence_generator.py", line 62, in __init__
    'Either checkpoint or bundle must be set')
magenta.music.sequence_generator.SequenceGeneratorException: Either checkpoint or bundle must be set
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

My specs:

Mac OS: 10.11.6
magenta: 0.1.6
python: 2.7.12
tensorflow: 0.11.0rc2
bazel: 0.3.1 (since 0.4.0 has [#1997 ](https://github.com/bazelbuild/bazel/issues/1997) issue.

Any suggestions would be greatly appreciated!
I really want to get going. Magenta is addicting 😆 

Thank you in advance.

**Comment by cghawthorne** [comment]
You'll need to add a checkpoint or bundle file path to your command. You can find links to pre-trained bundle files and an example command using the `--bundle_file` flag here: https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn#pre-trained

**Comment by jellysquider** [comment]
Thanks!

Is it like this? 
```

BUNDLE_PATH=//miniconda2/envs/magenta/magenta/models/melody_rnn/lookback_rnn.mag

CONFIG=‘lookback_rnn’

bazel run //magenta/models/melody_rnn:melody_rnn_generate -- --bundle_file=${BUNDLE_PATH}  --config=${CONFIG}
```

**Comment by cghawthorne** [comment]
Yes, very similar to that. You should also add the other flags in that example command:

```
BUNDLE_PATH=//miniconda2/envs/magenta/magenta/models/melody_rnn/lookback_rnn.mag

CONFIG=‘lookback_rnn’

bazel run //magenta/models/melody_rnn:melody_rnn_generate --
--config=${CONFIG} \
--bundle_file=${BUNDLE_PATH} \
--output_dir=/tmp/melody_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"
```

**Comment by jellysquider** [comment]
hey, thanks a lot for writing it. I think it should be written like this on the[ main page](https://github.com/tensorflow/magenta) too.

I got issue described in #350 :(
