### ISSUE TITLE
Error on Image stylization with Docker image on examples

### ISSUE THREAD

**Issue by CihanSari** [tensorflow/magenta#438]
I am using Docker 1.12.3 (8488) on Windows 10. My launch script is: "docker run -it -p 6006:6006 -v d:/projects/data/magenta:/magenta-data -v d:/data/:/bigdata tensorflow/magenta".

I have followed the steps in https://github.com/tensorflow/magenta/blob/master/README.md#docker and got 

```
/magenta-data# melody_rnn_generate \
   --config=lookback_rnn \
   --bundle_file=/magenta-models/lookback_rnn.mag \
   --output_dir=/magenta-data/lookback_rnn/generated \
   --num_outputs=10 \
   --num_steps=128 \
   --primer_melody="[60]"
INFO:tensorflow:Beam search yields melody with log-likelihood: -105.642350
INFO:tensorflow:Beam search yields melody with log-likelihood: -175.272188
INFO:tensorflow:Beam search yields melody with log-likelihood: -140.538503
INFO:tensorflow:Beam search yields melody with log-likelihood: -182.784687
INFO:tensorflow:Beam search yields melody with log-likelihood: -80.120105
INFO:tensorflow:Beam search yields melody with log-likelihood: -207.462564
INFO:tensorflow:Beam search yields melody with log-likelihood: -138.664485
INFO:tensorflow:Beam search yields melody with log-likelihood: -167.801560
INFO:tensorflow:Beam search yields melody with log-likelihood: -36.049449
INFO:tensorflow:Beam search yields melody with log-likelihood: -135.496597
INFO:tensorflow:Wrote 10 MIDI files to /magenta-data/lookback_rnn/generated
```

I want to use image_stylization and trying to run the examples on https://github.com/tensorflow/magenta/tree/master/magenta/models/image_stylization#training-a-model.

I am receiving errors. I want to use image_stylization to:
1- Use a model with varying weights
2- Fine-tune my own model with my paintings

1- I am running a very slightly modified version of the example given in https://github.com/tensorflow/magenta/tree/master/magenta/models/image_stylization#stylizing-an-image. Modification is limited to paths of the files only (so output is in shared folder).

image_stylization_transform \
      --num_styles=10 \
      --checkpoint=/magenta-data/multistyle-pastiche-generator-monet.ckpt \
      --input_image=/magenta-data/photo.jpg \
      --which_styles="{0:0.1,1:0.1,2:0.1,3:0.1,4:0.1,5:0.1,6:0.1,7:0.1,8:0.1,9:0.1}" \
      --output_dir=/magenta-data/output \
      --output_basename="all_monet_styles"

Console output:

```
/magenta-data# image_stylization_transform \
       --num_styles=10 \
       --checkpoint=/magenta-data/multistyle-pastiche-generator-monet.ckpt \
       --input_image=/magenta-data/photo.jpg \
       --which_styles="{0:0.1,1:0.1,2:0.1,3:0.1,4:0.1,5:0.1,6:0.1,7:0.1,8:0.1,9:0.1}" \
       --output_dir=/magenta-data/output \
       --output_basename="all_monet_styles"
Traceback (most recent call last):
  File "/usr/local/bin/image_stylization_transform", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_transform.py", line 77, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_transform.py", line 54, in main
    'labels': tf.constant(which_styles),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/constant_op.py", line 163, in constant
    tensor_util.make_tensor_proto(value, dtype=dtype, shape=shape))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/tensor_util.py", line 422, in make_tensor_proto
    tensor_proto.string_val.extend([compat.as_bytes(x) for x in proto_values])
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 64, in as_bytes
    (bytes_or_text,))
TypeError: Expected binary or unicode string, got {0: 0.1, 1: 0.1, 2: 0.1, 3: 0.1, 4: 0.1, 5: 0.1, 6: 0.1, 7: 0.1, 8: 0.1, 9: 0.1}
```

I can, however, run it without any weights. Below command generates a modified version of my input image.

image_stylization_transform \
      --num_styles=10 \
      --checkpoint=/magenta-data/multistyle-pastiche-generator-monet.ckpt \
      --input_image=/magenta-data/photo.jpg \
      --output_dir=/magenta-data/output \
      --output_basename="all_monet_styles"

	  
	  
How can I use the different weights ?

2- I am following the guide here: https://github.com/tensorflow/magenta/tree/master/magenta/models/image_stylization#training-a-model

Below command generates a 33 MB file as output from 7 images (1.26 MB total size). 

image_stylization_create_dataset \
      --vgg_checkpoint=/magenta-data/train/vgg_16.ckpt \
      --style_files=/magenta-data/train/style/images/*.jpg \
      --output_file=/magenta-data/train/style_images.tfrecord

  
However, fine-tuning step returns an error on the model:

```
/magenta-data/train# image_stylization_finetune --checkpoint=/magenta-data/train/vgg_16.ckpt --train_dir=/magenta-data/train/traindir --style_dataset_file=/magenta-data/train/style_images.tfrecord --num_styles=7 --vgg_checkpoint=/magenta-data/train/vgg_16.ckpt --imagenet_data_dir=/bigdata/output
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
Traceback (most recent call last):
  File "/usr/local/bin/image_stylization_finetune", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 166, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 162, in main
    save_interval_secs=FLAGS.save_interval_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 753, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 969, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 797, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 958, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 715, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 235, in prepare_session
    init_fn(sess)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 145, in init_fn
    init_fn_n_styles(session)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 141, in init_fn_n_styles
    saver_n_styles.restore(session, os.path.expanduser(FLAGS.checkpoint))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1345, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 717, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 915, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 965, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 985, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors.NotFoundError: Tensor name "transformer/residual/residual5/conv2/weights" not found in checkpoint files /magenta-data/train/vgg_16.ckpt
         [[Node: save_1/restore_slice_15 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_15/tensor_name, save_1/restore_slice_15/shape_and_slice)]]


Caused by op u'save_1/restore_slice_15', defined at:
  File "/usr/local/bin/image_stylization_finetune", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 166, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 139, in main
    saver_n_styles = tf.train.Saver(other_vars)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 986, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1015, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 620, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 357, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 270, in restore_op
    preferred_shard=preferred_shard))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/io_ops.py", line 204, in _restore_slice
    preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_io_ops.py", line 359, in _restore_slice
    preferred_shard=preferred_shard, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 749, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2380, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1298, in __init__
    self._traceback = _extract_stack()


NotFoundError (see above for traceback): Tensor name "transformer/residual/residual5/conv2/weights" not found in checkpoint files /magenta-data/train/vgg_16.ckpt
         [[Node: save_1/restore_slice_15 = RestoreSlice[dt=DT_FLOAT, preferred_shard=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/restore_slice_15/tensor_name, save_1/restore_slice_15/shape_and_slice)]]
```

**Comment by CihanSari** [comment]
I have long since switched to VMWare and ran full version of Ubuntu 16.10. I will reinstall and test with the latest version of docker for windows and magenta image and let you know.

**Comment by CihanSari** [comment]
@iansimon  I did pull the latest and it solved the initial problem with the string.

Although it starts, training my own network still fails soon after with no obvious error. Below is the console output, almost entirely with warnings.

Maybe some kind of time-out functionality I am not aware of ?

WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_utils.py:136 in imagenet_inputs.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py:344 in __init__.: __init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.

Killed

**Comment by iansimon** [comment]
It looks like you're running image_stylization_finetune, but passing the VGG checkpoint as the stylization checkpoint.  If you want to finetune you'll want to pass one of our pretrained model checkpoints (http://download.magenta.tensorflow.org/models/multistyle-pastiche-generator-monet.ckpt) or (http://download.magenta.tensorflow.org/models/multistyle-pastiche-generator-varied.ckpt).

If you want to train a model from scratch, use image_stylization_train instead of image_stylization_finetune.

**Comment by CihanSari** [comment]
I want to finetune..

This is what I am using:

```
image_stylization_finetune \
      --checkpoint=/magenta-data/multistyle-pastiche-generator-monet.ckpt \
      --train_dir=/magenta-data/train/style/images_4 \
      --style_dataset_file=/magenta-data/train/style/style_images_4.tfrecord \
      --num_styles=4 \
      --vgg_checkpoint=/magenta-data/train/vgg_16.ckpt \
      --imagenet_data_dir=/imagenet_data
```

This is the example on readme.md:

```
image_stylization_finetune \
      --checkpoint=/path/to/model.ckpt \
      --train_dir=/tmp/image_stylization/run2/train
      --style_dataset_file=/tmp/image_stylization/style_images.tfrecord \
      --num_styles=<NUMBER_OF_STYLES> \
      --vgg_checkpoint=/path/to/vgg_16.ckpt \
      --imagenet_data_dir=/path/to/imagenet-2012-tfrecord
```

Can I finetune without imagenet / vgg_checkpoint? No imagenet parameter returns an error. No vgg execution started, I am not sure if it will work out in the end or not.

Could you also explain why I need imagenet data as a whole when I am just finetuning ? Maybe then I have a better understanding of the process..

**Comment by CihanSari** [comment]
```
root@92a258e36b5c:/magenta-data# image_stylization_finetune \
>       --checkpoint=/magenta-data/multistyle-pastiche-generator-monet.ckpt \
>       --train_dir=/magenta-data/train/style/images_4 \
>       --style_dataset_file=/magenta-data/train/style/style_images_4.tfrecord \
>       --num_styles=4 \
>       --imagenet_data_dir=/imagenet_data
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_utils.py:136 in imagenet_inputs.: image_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.image. Note that tf.summary.histogram uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, the max_images argument was renamed to max_outputs.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py:122 in main.: scalar_summary (from tensorflow.python.ops.logging_ops) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.scalar. Note that tf.summary.scalar uses the node name instead of the tag. This means that TensorFlow will automatically de-duplicate summary names based on the scope they are created in. Also, passing a tensor or list of tags to a scalar summary op is no longer supported.
WARNING:tensorflow:From /usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py:344 in __init__.: __init__ (from tensorflow.python.training.summary_io) is deprecated and will be removed after 2016-11-30.
Instructions for updating:
Please switch to tf.summary.FileWriter. The interface and behavior is the same; this is just a rename.
Traceback (most recent call last):
  File "/usr/local/bin/image_stylization_finetune", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 166, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 162, in main
    save_interval_secs=FLAGS.save_interval_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/contrib/slim/python/slim/learning.py", line 766, in train
    master, start_standard_services=False, config=session_config) as sess:
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 974, in managed_session
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 802, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 386, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 963, in managed_session
    start_standard_services=start_standard_services)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 720, in prepare_or_wait_for_session
    init_feed_dict=self._init_feed_dict, init_fn=self._init_fn)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/session_manager.py", line 235, in prepare_session
    init_fn(sess)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 144, in init_fn
    init_fn_vgg(session)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/image_stylization_finetune.py", line 134, in init_fn_vgg
    saver_vgg.restore(session, vgg.checkpoint_file())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/image_stylization/vgg.py", line 38, in checkpoint_file
    return os.path.expanduser(FLAGS.vgg_checkpoint)
  File "/usr/lib/python2.7/posixpath.py", line 261, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```
@iansimon Could you take a look ?

**Comment by iansimon** [comment]
It looks like your most recent error is from not passing the VGG checkpoint.

Finetuning is very much like training, but instead of starting from scratch it starts with the weights of a pretrained model.  It still needs to use imagenet images as training data.

**Comment by CihanSari** [comment]
> It looks like your most recent error is from not passing the VGG checkpoint.

When I pass VGG and everything, I got the initial error. Currently I cannot finetune (with or without passing vgg checkpoint) on docker image.
