### ISSUE TITLE
Failure on image_stylization_train

### ISSUE THREAD

**Issue by anordell** [tensorflow/magenta#443]
We are trying to train a new style and are getting the following error. A similar one appears running from manual install or using the docker image. We have tried reinstalling from a fresh instance, code is running on ubuntu16.04 on a GCE instance.

As the error message is similar to :  https://github.com/fchollet/keras/issues/3887  we attempted using different TF versions. Failure occured using 0.09.0, 0.10.0, 0.10.0rc0, 0.11.0 and 0.12.0

Did one of the needed docker dependency images change?

------------------------------------------------------------------

image_stylization_train --train_dir=/style_train/train_dir/ --style_dataset_file=/style_train/candy_style_images.tfrecord --num_styles=2 --vgg_checkpoint=/style_train/vgg_16.ckpt       --imagenet_data_dir=style_train/imagenet-2012-tfrecord

WARNING:tensorflow:tf.op_scope(values, name, default_name) is deprecated, use tf.name_scope(name, default_name, values)
Traceback (most recent call last):
File "/home/seb/miniconda2/envs/magenta/bin/image_stylization_train", line 11, in <module>
    sys.exit(console_entry_point())
File "/home/seb/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_stylization_train.py", line 144, in console_entry_point
    tf.app.run(main)
File "/home/seb/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
File "/home/seb/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_stylization_train.py", line 75, in main
    FLAGS.image_size)
File "/home/seb/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_utils.py", line 121, in imagenet_inputs
    image = _central_crop([image], image_size, image_size)[0]
File "/home/seb/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_utils.py", line 441, in _central_crop
    crop_height, crop_width))

File "/home/seb/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_utils.py", line 400, in _crop
    cropped_shape = tf.control_flow_ops.with_dependencies(
AttributeError: 'module' object has no attribute 'control_flow_ops'

**Comment by ouyanghao** [comment]
I modified the code in image_utils.py like this: 
add `from tensorflow.python.ops import control_flow_ops as control_flow_ops` at the beginning 
and replace `tf.control_flow_ops` with  `control_flow_ops`. It works for me.

**Comment by iansimon** [comment]
Should be fixed in #444

**Comment by anordell** [comment]
Cheers!

**Comment by sebpaquet** [comment]
It seems the Docker image at https://hub.docker.com/r/tensorflow/magenta/tags/ is not refreshed with each new pull. Correct?

**Comment by cghawthorne** [comment]
When you pull the Docker image, it's only refreshed to our latest Magenta release. We haven't yet cut a new release that includes the fix, so you won't see it in the Docker image.

The fastest way to test out the fix would be to use a development environment and use the Magenta source at HEAD.

Otherwise, you can wait until we cut our next release, which should be soon.
