### ISSUE TITLE
image_stylization_transform throws error

### ISSUE THREAD

**Issue by predict-r** [tensorflow/magenta#459]
When I run the following command: 

```
image_stylization_transform \
      --num_styles=32 \
      --checkpoint=/home/sashag/Downloads/multistyle-pastiche-generator-varied.ckpt \
      --input_image=/home/sashag/Downloads/most-beautiful-horses-most-beautiful-horses-in-the-world-1_feature.jpg \
      --which_styles="[0,1,2,5,14]" \
      --output_dir=/home/sashag/Downloads/image_stylization/ \
      --output_basename="stylized"
```

I get the following error in the output: 

```
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcudnn.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
I tensorflow/core/common_runtime/gpu/gpu_device.cc:885] Found device 0 with properties: 
name: TITAN X (Pascal)
major: 6 minor: 1 memoryClockRate (GHz) 1.531
pciBusID 0000:06:00.0
Total memory: 11.90GiB
Free memory: 11.52GiB
I tensorflow/core/common_runtime/gpu/gpu_device.cc:906] DMA: 0 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:916] 0:   Y 
I tensorflow/core/common_runtime/gpu/gpu_device.cc:975] Creating TensorFlow device (/gpu:0) -> (device: 0, name: TITAN X (Pascal), pci bus id: 0000:06:00.0)
Traceback (most recent call last):
  File "/home/sashag/miniconda2/envs/magenta/bin/image_stylization_transform", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_stylization_transform.py", line 143, in console_entry_point
    tf.app.run(main)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_stylization_transform.py", line 134, in main
    _multiple_images(image, which_styles, output_dir)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/image_stylization_transform.py", line 93, in _multiple_images
    'scale': True})
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/model.py", line 54, in transform
    h = _conv2d(input_, 9, 1, 32, 'conv1')
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/model.py", line 102, in _conv2d
    scope=scope)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/layers/python/layers/layers.py", line 849, in convolution
    outputs = normalizer_fn(outputs, **normalizer_params)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/ops.py", line 109, in conditional_instance_norm
    'gamma', tf.ones_initializer, labels, num_categories)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/image_stylization/ops.py", line 97, in _label_conditioned_variable
    trainable=trainable)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 244, in model_variable
    caching_device=caching_device, device=device)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/arg_scope.py", line 177, in func_with_args
    return func(*args, **current_args)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/contrib/framework/python/ops/variables.py", line 208, in variable
    caching_device=caching_device)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 1024, in get_variable
    custom_getter=custom_getter)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 850, in get_variable
    custom_getter=custom_getter)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 346, in get_variable
    validate_shape=validate_shape)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 331, in _true_getter
    caching_device=caching_device, validate_shape=validate_shape)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 677, in _get_single_variable
    expected_shape=shape)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 224, in __init__
    expected_shape=expected_shape)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variables.py", line 327, in _init_from_args
    initial_value(), name="initial_value", dtype=dtype)
  File "/home/sashag/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/variable_scope.py", line 665, in <lambda>
    shape.as_list(), dtype=dtype, partition_info=partition_info)
TypeError: ones_initializer() got multiple values for keyword argument 'dtype'
```

Here are the versions of python packages installed in pip: 

```
backports-abc (0.5)
backports.shutil-get-terminal-size (1.0.0)
certifi (2016.9.26)
cloudpickle (0.2.1)
configparser (3.5.0)
cycler (0.10.0)
cymem (1.31.2)
decorator (4.0.10)
entrypoints (0.2.2)
enum34 (1.1.6)
funcsigs (1.0.2)
functools32 (3.2.3.post2)
h5py (2.6.0)
ipykernel (4.5.2)
ipython (5.1.0)
ipython-genutils (0.1.0)
ipywidgets (5.2.2)
Jinja2 (2.8)
jsonschema (2.5.1)
jupyter (1.0.0)
jupyter-client (4.4.0)
jupyter-console (5.0.0)
jupyter-core (4.2.1)
Keras (1.1.2)
magenta (0.1.6)
MarkupSafe (0.23)
matplotlib (1.5.3)
mido (1.1.18)
mistune (0.7.3)
mock (2.0.0)
murmurhash (0.26.4)
nbconvert (4.3.0)
nbformat (4.2.0)
notebook (4.3.0)
numpy (1.11.2)
pandas (0.18.1)
pathlib (1.0.1)
pathlib2 (2.1.0)
pbr (1.10.0)
pexpect (4.2.1)
pickleshare (0.7.4)
Pillow (3.4.2)
pip (9.0.1)
plac (0.9.6)
preshed (0.46.4)
pretty-midi (0.2.6)
prompt-toolkit (1.0.9)
protobuf (3.1.0)
ptyprocess (0.5.1)
py-mini-racer (0.1.6)
Pygments (2.1.3)
pyparsing (2.1.10)
python-dateutil (2.5.3)
python-rtmidi (1.0.0)
pytz (2016.6.1)
PyYAML (3.12)
pyzmq (16.0.2)
qtconsole (4.2.1)
scipy (0.18.1)
setuptools (28.0.0)
simplegeneric (0.8.1)
singledispatch (3.4.0.3)
six (1.10.0)
sputnik (0.9.3)
tensorflow (0.11.0rc2)
tensorflow-gpu (0.12.0rc1)
terminado (0.6)
Theano (0.8.2)
thinc (5.0.8)
tornado (4.4.2)
traitlets (4.3.1)
wcwidth (0.1.7)
wheel (0.29.0)
widgetsnbextension (1.2.6)
```

**Comment by cghawthorne** [comment]
I think this is fixed by #441. You can either try building from source or waiting until we cut a new pip package version, which should be in the next few days. Please reopen if one of these methods doesn't work.
