### ISSUE TITLE
'module' object has no attribute 'BasicLSTMCell'

### ISSUE THREAD

**Issue by boblsturm** [tensorflow/magenta#531]
I just updated my git and now things that were working yesterday are not:

bazel-bin/magenta/models/melody_rnn/melody_rnn_train \
> --config=basic_rnn \
> --run_dir=/homes/sturm/magenta_session \
> --sequence_example_file=/homes/sturm/datasets/basicrnnseq/training_melodies.tfrecord \
> --hparams="{'batch_size':100,'rnn_layer_sizes':[512,512,512],'decay_rate':0.97, 'initial_learning_rate':0.03,'decay_steps':800,'dropout_keep_prob':0.5,'skip_first_n_losses':8000}" \
> --num_training_steps=40000
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcublas.so locally
I tensorflow/stream_executor/dso_loader.cc:119] Couldn't open CUDA library libcudnn.so. LD_LIBRARY_PATH: :/usr/lib64:/usr/local/cuda/lib64:/homes/sturm/.local/lib
I tensorflow/stream_executor/cuda/cuda_dnn.cc:3459] Unable to load cuDNN DSO
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcufft.so locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcuda.so.1 locally
I tensorflow/stream_executor/dso_loader.cc:128] successfully opened CUDA library libcurand.so locally
Traceback (most recent call last):
  File "/homes/sturm/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 21, in <module>
    from magenta.models.melody_rnn import melody_rnn_config_flags
  File "/homes/sturm/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_config_flags.py", line 20, in <module>
    from magenta.models.melody_rnn import melody_rnn_model
  File "/homes/sturm/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_model.py", line 21, in <module>
    from magenta.models.shared import events_rnn_model
  File "/homes/sturm/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/shared/events_rnn_model.py", line 25, in <module>
    from magenta.models.shared import events_rnn_graph
  File "/homes/sturm/magenta/bazel-bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/shared/events_rnn_graph.py", line 24, in <module>
    base_cell=tf.contrib.rnn.BasicLSTMCell,
AttributeError: 'module' object has no attribute 'BasicLSTMCell'

**Comment by cghawthorne** [comment]
Hey Bob, you'll need to update your TensorFlow installation to the new 1.0 release. It has some API changes, and the latest git revision reflects those. Note that unfortunately this is also causing some (inaccurate) test failures. See #529 for details. If the test failures are causing you problems, you could also just reset your git repo to cbee9fa, which was before the API changes.
