### ISSUE TITLE
Issue generation melody_rnn with midi file

### ISSUE THREAD

**Issue by cgayner** [tensorflow/magenta#533]
Hello,
I am having an issue generating a melody_rnn with a midi file
Below are the various code and resultant error messages I get:

I am able to Convert the midi to sequence and then train the AI, however I get an error when I try to generate the midi from a specific midi file (the midi file is definitely in the right location - although it has polyphonic chords in the track, will that matter?):

————————————————————————————————
1. BUILD DATA SET (***WORKS)
convert_dir_to_note_sequences \
  --input_dir=/magenta-data/midi \
  --output_file=/tmp/notesequences.tfrecord \
  --recursive

2. CONVERT MIDI TO SEQUENCE (***WORKS)
melody_rnn_create_dataset \
--config=lookback_rnn \
--input=/tmp/notesequences.tfrecord \
--output_dir=/tmp/melody_rnn/sequence_examples \
--eval_ratio=0.10
 
3. TRAIN IT (***WORKS)
melody_rnn_train \
--config=lookback_rnn \
--run_dir=/tmp/melody_rnn/logdir/run7 \
--sequence_example_file=/tmp/melody_rnn/sequence_examples/training_melodies.tfrecord \
--hparams="{'batch_size':64,'rnn_layer_sizes':[64,64]}" \
--num_training_steps=1000

4. GENERATE MELODY (***DOES NOT WORK)
melody_rnn_generate \
--config=lookback_rnn \
--run_dir=/tmp/melody_rnn/logdir/run7 \
--output_dir=/magenta-data/lookback_rnn/generated2 \
--num_outputs=3 \
--num_steps=800 \
--hparams="{'batch_size’:64,’rnn_layer_sizes':[64,64]}" \
--primer_midi=/magenta-data/midi-test.mid> > > > > > >

*** ERROR 
INFO:tensorflow:hparams = {'rnn_layer_sizes': [128, 128], 'decay_rate': 0.95, 'dropout_keep_prob': 1.0, 'batch_size\xe2\x80\x99:64,\xe2\x80\x99rnn_layer_sizes': [64, 64], 'batch_size': 1, 'decay_steps': 1000, 'clip_norm': 5, 'initial_learning_rate': 0.01, 'skip_first_n_losses': 0}
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7f7c4ed68290>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell.BasicLSTMCell object at 0x7f7c4ecda790>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
INFO:tensorflow:Checkpoint used: /tmp/melody_rnn/logdir/run7/train/model.ckpt-1000

Traceback (most recent call last):
  File "/usr/local/bin/melody_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 258, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 254, in main
    run_with_flags(generator)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 225, in run_with_flags
    generated_sequence = generator.generate(input_sequence, generator_options)
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/sequence_generator.py", line 203, in generate
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/sequence_generator.py", line 149, in initialize
    self._model.initialize_with_checkpoint(checkpoint_file)
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/model.py", line 63, in initialize_with_checkpoint
    saver.restore(self._session, checkpoint_file)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1388, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 766, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 964, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1014, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1034, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128,40] rhs shape= [64,40]
     [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](fully_connected/weights, save/RestoreV2_5)]]

Caused by op u'save/Assign_5', defined at:

  File "/usr/local/bin/melody_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 258, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 43, in run
    sys.exit(main(sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 254, in main
    run_with_flags(generator)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 225, in run_with_flags
    generated_sequence = generator.generate(input_sequence, generator_options)
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/sequence_generator.py", line 203, in generate
    self.initialize()
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/sequence_generator.py", line 149, in initialize
    self._model.initialize_with_checkpoint(checkpoint_file)
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/model.py", line 60, in initialize_with_checkpoint
    saver = tf.train.Saver()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1000, in __init__
    self.build()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 1030, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 624, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 373, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/saver.py", line 130, in restore
    self.op.get_shape().is_fully_defined())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_state_ops.py", line 47, in assign
    use_locking=use_locking, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 759, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2240, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1128, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [128,40] rhs shape= [64,40]
     [[Node: save/Assign_5 = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/weights"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/cpu:0"](fully_connected/weights, save/RestoreV2_5)]]

————————————————————————————————

Welcome any Ideas on how to fix
Cheers

**Comment by cghawthorne** [comment]
Is there any chance you're accidentally referencing a directory with a checkpoint that was trained with a different network size? This is the important error from the stacktrace:

```
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [128,40] rhs shape= [64,40]
```

It seems to imply that the network you've constructed doesn't match the checkpoint you're trying to restore.
