### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'startswith'

### ISSUE THREAD

**Issue by agataTantinya** [tensorflow/magenta#569]
Hello, 

I'm trying to train the attention_rnn model. I created a notesequence.tfrecord from one folder of the the Lakh MIDI dataset as follows: 
```
$ sudo ./bazel-bin/magenta/scripts/convert_dir_to_note_sequences --input_dir=/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A --output_file=/Users/atufebt/agata/notesequences_miniexample.tfrecord --recursive 
```
The output of the command was this: 

```
INFO:tensorflow:Converting files in '/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A/'.
INFO:tensorflow:Converted 0 files in '/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A/'.
INFO:tensorflow:Could not parse 0 files.
INFO:tensorflow:Converting files in '/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A/TRAAAGR128F425B14B'.
/Users/atufebt/magenta/bazel-bin/magenta/scripts/convert_dir_to_note_sequences.runfiles/pretty_midi/pretty_midi.py:93: RuntimeWarning: Tempo, Key or Time signature change events found on non-zero tracks.  This is not a valid type 0 or type 1 MIDI file.  Tempo, Key or Time Signature may be wrong.
  RuntimeWarning)
INFO:tensorflow:Converted 4 files in '/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A/TRAAAGR128F425B14B'.
INFO:tensorflow:Could not parse 0 files.
INFO:tensorflow:Converting files in '/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A/TRAAAZF12903CCCF6B'.
INFO:tensorflow:Converted 6 files in '/Users/atufebt/Desktop/Magenta_docs/Lakh_MIDI_Dataset/lmd_matched/A/A/A/TRAAAZF12903CCCF6B'.
INFO:tensorflow:Could not parse 0 files.
INFO:tensorflow:Wrote 10 NoteSequence protos to '/Users/atufebt/agata/notesequences_miniexample.tfrecord'
```
Then I tried to create a dataset to train the model, so using the command: 
```
(tensorflow) atufebt: ~/magenta @$> sudo melody_rnn_create_dataset --config=attention_rnn —-input=/Users/atufebt/agata/notesequences_miniexample.tfrecord —-output_dir=/Users/atufebt/agata/melody_rnn/sequence_mini_examples —-eval_ratio=0.1
```
The output was: 
```
Traceback (most recent call last):
  File "/Users/atufebt/tensorflow/bin/melody_rnn_create_dataset", line 11, in <module>
    sys.exit(console_entry_point())
  File "/Users/atufebt/tensorflow/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_create_dataset.py", line 130, in console_entry_point
    tf.app.run(main)
  File "/Users/atufebt/tensorflow/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/atufebt/tensorflow/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_create_dataset.py", line 121, in main
    FLAGS.input = os.path.expanduser(FLAGS.input)
  File "/Users/atufebt/tensorflow/bin/../lib/python2.7/posixpath.py", line 254, in expanduser
    if not path.startswith('~'):
AttributeError: 'NoneType' object has no attribute 'startswith'
```

I've tried to search for this error but nothing clear came up. I've upgraded to bazel 0.4.5: 
```
(tensorflow) atufebt: ~/magenta @$> bazel version
Build label: 0.4.5-homebrew
Build target: bazel-out/local-opt/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 13:37:54 2017 (1489671474)
Build timestamp: 1489671474
Build timestamp as int: 1489671474
```
And also I think I'm on the latest version of magenta. 
Don't know what I'm missing. Any help would be much appreciated. Thanks.

**Comment by cghawthorne** [comment]
The problem seems to be that the command isn't seeing anything for the `--input` flag. Looking at the command you pasted, it looks like the first dash is actually a unicode em-dash (0x2014) instead of just a normal dash (0x2d). I'm guessing you maybe pasted it into some sort of editor that turned the two dashes into an em-dash? Can you try typing the command manually instead of doing any pasting?

**Comment by agataTantinya** [comment]
Thanks! You were right.
