### ISSUE TITLE
Unrecognized option: --noexperimental_python_import_all_repositories

### ISSUE THREAD

**Issue by dbl001** [tensorflow/magenta#578]
Trying to install Magenta and the development environment on OS X 10.11.6
$ curl https://raw.githubusercontent.com/tensorflow/magenta/master/magenta/tools/magenta-install.sh > /tmp/magenta-install.sh

$ bash /tmp/magenta-install.sh
$ source activate magenta
$ bazel version
Build label: 0.4.2
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Wed Dec 7 15:54:21 2016 (1481126061)
Build timestamp: 1481126061
Build timestamp as int: 1481126061

David-Laxers-MacBook-Pro:magenta davidlaxer$ bazel test //magenta/...
INFO: Options provided by the client:
  Inherited 'common' options: --isatty=1 --terminal_columns=80
INFO: Reading options for 'test' from /Users/davidlaxer/magenta/tools/bazel.rc:
  Inherited 'build' options: --define=allow_oversize_protos=true --copt -funsigned-char -c opt --noexperimental_python_import_all_repositories --spawn_strategy=standalone
Unrecognized option: --noexperimental_python_import_all_repositories

**Comment by cghawthorne** [comment]
Hi @dbl001. We require Bazel 0.4.5 to use the dev environment. I'll update the readme to reflect this.

**Comment by dbl001** [comment]
Different issu, but …

$ bazel version
Build label: 0.4.5
Build target: bazel-out/local-fastbuild/bin/src/main/java/com/google/devtools/build/lib/bazel/BazelServer_deploy.jar
Build time: Thu Mar 16 12:50:12 2017 (1489668612)
Build timestamp: 1489668612
Build timestamp as int: 1489668612

$ bazel run //magenta/models/melody_rnn:melody_rnn_generate -- --config=...
INFO: Found 1 target...
Target //magenta/models/melody_rnn:melody_rnn_generate up-to-date:
  bazel-bin/magenta/models/melody_rnn/melody_rnn_generate
INFO: Elapsed time: 1.651s, Critical Path: 0.68s

INFO: Running command line: bazel-bin/magenta/models/melody_rnn/melody_rnn_generate '--config=...'
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 246, in <module>
    console_entry_point()
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 242, in console_entry_point
    tf.app.run(main)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 44, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 223, in main
    config = melody_rnn_config_flags.config_from_flags()
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_config_flags.py", line 136, in config_from_flags
    melody_rnn_model.default_configs.keys(), FLAGS.config))
magenta.models.melody_rnn.melody_rnn_config_flags.MelodyRnnConfigFlagsException: `--config` must be one of ['basic_rnn', 'attention_rnn', 'lookback_rnn']. Got ....
ERROR: Non-zero return code '1' from command: Process exited with status 1.
David-Laxers-MacBook-Pro:magenta davidlaxer$

**Comment by cghawthorne** [comment]
You need to specify a valid config option. The `...` in the docs is meant as an example. The docs on the melody model provide some more concrete examples: https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn
