### ISSUE TITLE
Error while building a dataset.

### ISSUE THREAD

**Issue by huntedman** [tensorflow/magenta#613]
Hi,

I am trying to build a dataset based on the example from the documentation, but I'm getting this weird error.

convert_dir_to_note_sequences \
>  --input_dir = ~/Midis/ \
>  --output_file = ~/tmp/sequences.tfrecord \
>  --recursive 
Traceback (most recent call last):
  File "/usr/local/bin/convert_dir_to_note_sequences", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/scripts/convert_dir_to_note_sequences.py", line 185, in cons
ole_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/scripts/convert_dir_to_note_sequences.py", line 174, in main
    os.makedirs(os.path.dirname(output_file))
  File "/usr/lib/python2.7/os.py", line 157, in makedirs
    mkdir(name, mode)
OSError: [Errno 2] No such file or directory: ''

$ bazel version
Build label: 0.4.5

I really don't know what more relevant information could I provide.

**Comment by adarob** [comment]
Hi,
I think your issue is the spaces around the "=". There shouldn't be any on either side.
-Adam
