### ISSUE TITLE
melody_rnn_train codec can't decode byte

### ISSUE THREAD

**Issue by huntedman** [tensorflow/magenta#616]
Hey,

Trying to run a script copied from readme, but keep receiving some weird decoding error.
Even tried manually typing in the script in hopes of it being an invisible character to no avail.

melody_rnn_train \
--config=attention_rnn \
--run_dir=/tmp/melody_rnn/logdir/run1 \
--sequence_example_file=/tmp/notesequences.tfrecord \
--hparams="{'batch_size':128,'rnn_layer_sizes':[128,128]}" \
--num_training_steps=20000

```
INFO:tensorflow:hparams = {'rnn_layer_sizes': [128, 128], 'attn_length': 40, 'dropout_keep_prob': 0.5, 'batch_size'
: 128, 'decay_rate': 0.97, 'clip_norm': 3, 'initial_learning_rate': 0.001, 'decay_steps': 1000, 'skip_first_n_losses': 0}
INFO:tensorflow:Train dir: /tmp/melody_rnn/logdir/run1/train
2017-05-02 18:24:27.010331: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:24:27.010380: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:24:27.010387: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:24:27.010393: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:24:27.010397: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-05-02 18:24:27.192211: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:901] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-05-02 18:24:27.193194: I tensorflow/core/common_runtime/gpu/gpu_device.cc:900] Found device 0 with properties: 
name: Tesla K80
major: 3 minor: 7 memoryClockRate (GHz) 0.8235
pciBusID 0000:00:04.0
Total memory: 11.17GiB
Free memory: 11.09GiB
2017-05-02 18:24:27.193224: I tensorflow/core/common_runtime/gpu/gpu_device.cc:921] DMA: 0 
2017-05-02 18:24:27.193231: I tensorflow/core/common_runtime/gpu/gpu_device.cc:931] 0:   Y 
2017-05-02 18:24:27.193247: I tensorflow/core/common_runtime/gpu/gpu_device.cc:990] Creating TensorFlow device (/gpu:0) -> (device: 0, name: Tesla K80, pci bus id: 0000:00:04.0)
INFO:tensorflow:Restoring parameters from /tmp/melody_rnn/logdir/run1/train/model.ckpt-0
INFO:tensorflow:Starting standard services.
INFO:tensorflow:Starting queue runners.
rom SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
INFO:tensorflow:Saving checkpoint to path /tmp/melody_rnn/logdir/run1/train/model.ckpt
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode by
te 0x80 in position 106: invalid start byte
INFO:tensorflow:global_step/sec: 0
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Training complete.
Traceback (most recent call last):
  File "/usr/local/bin/melody_rnn_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 99, in console_
entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_train.py", line 95, in main
    FLAGS.summary_frequency)
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/shared/events_rnn_train.py", line 75, in run_training
    tf.logging.info('Training complete.')
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 962, in managed_sess
ion
    self.stop(close_summary_writer=close_summary_writer)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/supervisor.py", line 790, in stop
    stop_grace_period_secs=self._stop_grace_secs)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/training/queue_runner_impl.py", line 237, in _run
    enqueue_callable()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1060, in _single_operatio
n_run
    target_list_as_strings, status, None)
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 465, in raise_exce
ption_on_not_ok_status
    compat.as_text(pywrap_tensorflow.TF_Message(status)),
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
  File "/usr/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0x80 in position 106: invalid start byte
```

**Comment by huntedman** [comment]
Did a fresh install of the whole VM. 
Ran the script on the new machine, encountered it again. 
Changed the config and regenerated the dataset, got some other error.
Double checked my paths for the script.
Did an rm -rf for my --run_dir

Applying these steps in no particular order fixed it for me.
(I have no idea which one of them was to blame).
