### ISSUE TITLE
sketch_rnn: no 'cost' found when saving a checkpoint during training

### ISSUE THREAD

**Issue by silky** [tensorflow/magenta#661]
when the model attempts to save a checkpoint, it fails to find a `cost` field on the model

```
INFO:tensorflow:step: 500, lr: 0.000952, klw: 0.0221, cost: 0.8807, recon: 0.8594, kl: 0.9647, train_time_taken: 10.8615
Traceback (most recent call last):
  File "/home/noon/magenta/bazel-bin/magenta/models/sketch_rnn/sketch_rnn_train.runfiles/__main__/magenta/models/sketch_rnn/sketch_rnn_train.py", line 435, in <module>
    console_entry_point()
  File "/home/noon/magenta/bazel-bin/magenta/models/sketch_rnn/sketch_rnn_train.runfiles/__main__/magenta/models/sketch_rnn/sketch_rnn_train.py", line 431, in console_entry_point
    tf.app.run(main)
  File "/media/backup/data/ml/envs/noon/miniconda3/envs/magenta-dev/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/noon/magenta/bazel-bin/magenta/models/sketch_rnn/sketch_rnn_train.runfiles/__main__/magenta/models/sketch_rnn/sketch_rnn_train.py", line 427, in main
    trainer(model_params)
  File "/home/noon/magenta/bazel-bin/magenta/models/sketch_rnn/sketch_rnn_train.runfiles/__main__/magenta/models/sketch_rnn/sketch_rnn_train.py", line 419, in trainer
    train(sess, model, eval_model, train_set, valid_set, test_set)
  File "/home/noon/magenta/bazel-bin/magenta/models/sketch_rnn/sketch_rnn_train.runfiles/__main__/magenta/models/sketch_rnn/sketch_rnn_train.py", line 302, in train
    sess, eval_model, valid_set)
  File "/home/noon/magenta/bazel-bin/magenta/models/sketch_rnn/sketch_rnn_train.runfiles/__main__/magenta/models/sketch_rnn/sketch_rnn_train.py", line 184, in evaluate_model
    kl_cost) = sess.run([model.cost, model.r_cost, model.kl_cost], feed)
AttributeError: 'Model' object has no attribute 'cost'
```

this appears to be a bug here:

https://github.com/tensorflow/magenta/blob/master/magenta/models/sketch_rnn/model.py#L348

note that the two `if` statements have the same condition, and both result in there *not* being a `self.cost` if `is_training` is False.

i guess that the first one is meant to be: `if not(self.hps.is_training)`. (indeed, with this modification the code works for me.)

**Comment by cghawthorne** [comment]
@hardmaru does this fix look correct to you?

**Comment by hardmaru** [comment]
@dribnet kindly patched this issue, let me know if you still have a problem later.

https://github.com/tensorflow/magenta/pull/666

**Comment by hardmaru** [comment]
Hi @silky, I have resolved this issue. Can you take a look when you have the chance? Let us know if any issue. Thanks.

**Comment by silky** [comment]
it does fix it for me; but it still seems very odd to have the two if statements with exactly the same condition

as it is, you may as well just delete the first one; it contributes nothing.

**Comment by hardmaru** [comment]
I see, there was originally two sets in the research code to do more things, but that isn't needed anymore.  Will remove, thanks.
