### ISSUE TITLE
sketch_rnn: Key vector_rnn_1/beta2_power not found in checkpoint

### ISSUE THREAD

**Issue by dribnet** [tensorflow/magenta#676]
Using the included `sketch_rnn.ipynb`, I'm unable to call `load_checkpoint` on either the models downloaded or on models I train myself. Strange because the earlier `load_env` call on the model directory works fine. The error I get in each case is `Key vector_rnn_2/Variable not found in checkpoint`. I checked and the string `vector_rnn_2` doesn't appear anywhere in the magenta repo, so this might be a tensorflow deserialization issue or some such.

Full stacktrace below (warning: somewhat gnarly).

```bash
INFO:tensorflow:Loading model /develop/nets/magenta/magenta/models/sketch_rnn/models/zebra_horse1/vector-289500.
INFO:tensorflow:Restoring parameters from /develop/nets/magenta/magenta/models/sketch_rnn/models/zebra_horse1/vector-289500
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-17-40ef0dba7580> in <module>()
      1 # loads the weights from checkpoint into our model
----> 2 load_checkpoint(sess, model_dir)

/develop/nets/magenta/magenta/models/sketch_rnn/sketch_rnn_train.py in load_checkpoint(sess, checkpoint_path)
    222   ckpt = tf.train.get_checkpoint_state(checkpoint_path)
    223   tf.logging.info('Loading model %s.', ckpt.model_checkpoint_path)
--> 224   saver.restore(sess, ckpt.model_checkpoint_path)
    225 
    226 

/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in restore(self, sess, save_path)
   1455     logging.info("Restoring parameters from %s", save_path)
   1456     sess.run(self.saver_def.restore_op_name,
-> 1457              {self.saver_def.filename_tensor_name: save_path})
   1458 
   1459   @staticmethod

/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    776     try:
    777       result = self._run(None, fetches, feed_dict, options_ptr,
--> 778                          run_metadata_ptr)
    779       if run_metadata:
    780         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    980     if final_fetches or final_targets:
    981       results = self._do_run(handle, final_targets, final_fetches,
--> 982                              feed_dict_string, options, run_metadata)
    983     else:
    984       results = []

/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1030     if handle is None:
   1031       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1032                            target_list, options, run_metadata)
   1033     else:
   1034       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1050         except KeyError:
   1051           pass
-> 1052       raise type(e)(node_def, op, message)
   1053 
   1054   def _extend_graph(self):

NotFoundError: Key vector_rnn_2/Variable not found in checkpoint
     [[Node: save/RestoreV2_61 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_61/tensor_names, save/RestoreV2_61/shape_and_slices)]]
     [[Node: save/RestoreV2_25/_81 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_339_save/RestoreV2_25", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]

Caused by op u'save/RestoreV2_61', defined at:
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/__main__.py", line 3, in <module>
    app.launch_new_instance()
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 474, in start
    ioloop.IOLoop.instance().start()
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tornado/ioloop.py", line 887, in start
    handler_func(fd_obj, events)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tornado/stack_context.py", line 275, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 276, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 228, in dispatch_shell
    handler(stream, idents, msg)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 390, in execute_request
    user_expressions, allow_stdin)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 501, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2717, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2827, in run_ast_nodes
    if self.run_code(code, result):
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2881, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-17-40ef0dba7580>", line 2, in <module>
    load_checkpoint(sess, model_dir)
  File "/develop/nets/magenta/magenta/models/sketch_rnn/sketch_rnn_train.py", line 221, in load_checkpoint
    saver = tf.train.Saver(tf.global_variables())
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/anaconda2/envs/scratch2/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Key vector_rnn_2/Variable not found in checkpoint
     [[Node: save/RestoreV2_61 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save/Const_0, save/RestoreV2_61/tensor_names, save/RestoreV2_61/shape_and_slices)]]
     [[Node: save/RestoreV2_25/_81 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_339_save/RestoreV2_25", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/gpu:0"]()]]
```

**Comment by dribnet** [comment]
OK, I've found that reverting my change in #666 fixes it. Will keep looking.

**Comment by dribnet** [comment]
Yeah, the sketch_rnn notebook calls sketch_rnn_train.load_dataset(), which is where I had set `eval_model_params.is_training = 1` in #666. Evidently this breaks deserialization, maybe because TF is looking for 2 RNNs instead of just 1. In any case, setting this back to `eval_model_params.is_training = 0` fixes the problem for me.

I'll leave this open for now since the current code base will have the same problem for everyone else. I think the solution might be a fix to #661 that is different from #666.

**Comment by hardmaru** [comment]
will take a look

**Comment by hardmaru** [comment]
@dribnet this should be resolved now, can you help give it a go? let me know if any more issues. the multi-dateset is also in.
