### ISSUE TITLE
running rl_tuner.ipynb fails

### ISSUE THREAD

**Issue by johndpope** [tensorflow/magenta#711]
I successfully ran the mac os install script. and it completed without a problem.

When I do source activate magenta
navigate to rl_tuner directory
then type
**jupyter notebook**

I can get through step 7
rl_net = rl_tuner.RLTuner(**SAVE_PATH**, 
                          dqn_hparams=rl_tuner_hparams, 
                          algorithm=ALGORITHM,
                          reward_scaler=REWARD_SCALER,
                          output_every_nth=OUTPUT_EVERY_NTH,
                          num_notes_in_melody=NUM_NOTES_IN_COMPOSITION)

then it fails

WARNING:tensorflow:Can't find checkpoint file, using /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner/note_rnn.ckpt

https://github.com/tensorflow/magenta/blob/master/magenta/models/rl_tuner/rl_tuner.py#L179

<img width="840" alt="screen shot 2017-06-07 at 1 57 25 pm" src="https://user-images.githubusercontent.com/289994/26893457-696a071c-4b89-11e7-87a3-333ae908e1e7.png">

it initially seemed like  the web site  path is/was invalid. 
but I think it's a problem with the file not containing weights?
http://download.magenta.tensorflow.org/models/note_rnn.ckpt

**Comment by johndpope** [comment]
Retrieving checkpoint of Note RNN from Magenta download server.
INFO:tensorflow:Initializing q network
INFO:tensorflow:Using custom hparams
INFO:tensorflow:Initializing melody RNN graph for scope q_network
WARNING:tensorflow:<tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.LSTMCell object at 0x1187bee50>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
INFO:tensorflow:Initializing target q network
INFO:tensorflow:Using custom hparams
INFO:tensorflow:Initializing melody RNN graph for scope target_q_network
WARNING:tensorflow:<tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.LSTMCell object at 0x1199ca9d0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
INFO:tensorflow:Initializing reward network
INFO:tensorflow:Using custom hparams
INFO:tensorflow:Initializing melody RNN graph for scope reward_rnn
WARNING:tensorflow:<tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.LSTMCell object at 0x119a4d9d0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
INFO:tensorflow:Q network cell: <tensorflow.contrib.rnn.python.ops.core_rnn_cell_impl.MultiRNNCell object at 0x1187beb90>
INFO:tensorflow:Adding RL graph variables
INFO:tensorflow:Adding reward computation portion of the graph
INFO:tensorflow:Adding taking action portion of graph
INFO:tensorflow:Add estimating future rewards portion of graph
INFO:tensorflow:Adding q value prediction portion of graph
INFO:tensorflow:Summary name q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/weights:0 is illegal; using q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/weights_0 instead.
INFO:tensorflow:Summary name q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/weights:0/gradients is illegal; using q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/weights_0/gradients instead.
INFO:tensorflow:Summary name q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/biases:0 is illegal; using q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/biases_0 instead.
INFO:tensorflow:Summary name q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/biases:0/gradients is illegal; using q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/biases_0/gradients instead.
INFO:tensorflow:Summary name q_network/fully_connected/weights:0 is illegal; using q_network/fully_connected/weights_0 instead.
INFO:tensorflow:Summary name q_network/fully_connected/weights:0/gradients is illegal; using q_network/fully_connected/weights_0/gradients instead.
INFO:tensorflow:Summary name q_network/fully_connected/bias:0 is illegal; using q_network/fully_connected/bias_0 instead.
INFO:tensorflow:Summary name q_network/fully_connected/bias:0/gradients is illegal; using q_network/fully_connected/bias_0/gradients instead.
INFO:tensorflow:Summary name target_q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/weights:0 is illegal; using target_q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/weights_0 instead.
INFO:tensorflow:Summary name target_q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/biases:0 is illegal; using target_q_network/rnn/multi_rnn_cell/cell_0/lstm_cell/biases_0 instead.
INFO:tensorflow:Summary name target_q_network/fully_connected/weights:0 is illegal; using target_q_network/fully_connected/weights_0 instead.
INFO:tensorflow:Summary name target_q_network/fully_connected/bias:0 is illegal; using target_q_network/fully_connected/bias_0 instead.
INFO:tensorflow:Summary name reward_rnn/rnn/multi_rnn_cell/cell_0/lstm_cell/weights:0 is illegal; using reward_rnn/rnn/multi_rnn_cell/cell_0/lstm_cell/weights_0 instead.
INFO:tensorflow:Summary name reward_rnn/rnn/multi_rnn_cell/cell_0/lstm_cell/biases:0 is illegal; using reward_rnn/rnn/multi_rnn_cell/cell_0/lstm_cell/biases_0 instead.
INFO:tensorflow:Summary name reward_rnn/fully_connected/weights:0 is illegal; using reward_rnn/fully_connected/weights_0 instead.
INFO:tensorflow:Summary name reward_rnn/fully_connected/bias:0 is illegal; using reward_rnn/fully_connected/bias_0 instead.
INFO:tensorflow:Adding target network update portion of graph
INFO:tensorflow:Restoring variables from checkpoint
INFO:tensorflow:Checkpoint dir: /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner
WARNING:tensorflow:Can't find checkpoint file, using /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner/note_rnn.ckpt
INFO:tensorflow:Checkpoint file: /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner/note_rnn.ckpt
INFO:tensorflow:Restoring parameters from /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner/note_rnn.ckpt
---------------------------------------------------------------------------
NotFoundError                             Traceback (most recent call last)
<ipython-input-7-8910b466ad1e> in <module>()
      4                           reward_scaler=REWARD_SCALER,
      5                           output_every_nth=OUTPUT_EVERY_NTH,
----> 6                           num_notes_in_melody=NUM_NOTES_IN_COMPOSITION)

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.pyc in __init__(self, output_dir, dqn_hparams, reward_mode, reward_scaler, exploration_mode, priming_mode, stochastic_observations, algorithm, note_rnn_checkpoint_dir, note_rnn_checkpoint_file, note_rnn_type, note_rnn_hparams, num_notes_in_melody, input_size, num_actions, midi_primer, save_name, output_every_nth, training_file_list, summary_writer, initialize_immediately)
    234 
    235     if initialize_immediately:
--> 236       self.initialize_internal_models_graph_session()
    237 
    238   def initialize_internal_models_graph_session(self,

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.pyc in initialize_internal_models_graph_session(self, restore_from_checkpoint)
    298       # Initialize internal networks.
    299       if restore_from_checkpoint:
--> 300         self.q_network.initialize_and_restore(self.session)
    301         self.target_q_network.initialize_and_restore(self.session)
    302         self.reward_rnn.initialize_and_restore(self.session)

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.pyc in initialize_and_restore(self, session)
    140     """
    141     self.session = session
--> 142     self.restore_vars_from_checkpoint(self.checkpoint_dir)
    143 
    144   def initialize_new(self, session=None):

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.pyc in restore_vars_from_checkpoint(self, checkpoint_dir)
    282     tf.logging.info('Checkpoint file: %s', checkpoint_file)
    283 
--> 284     saver.restore(self.session, checkpoint_file)
    285 
    286   def load_primer(self):

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.pyc in restore(self, sess, save_path)
   1455     logging.info("Restoring parameters from %s", save_path)
   1456     sess.run(self.saver_def.restore_op_name,
-> 1457              {self.saver_def.filename_tensor_name: save_path})
   1458 
   1459   @staticmethod

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in run(self, fetches, feed_dict, options, run_metadata)
    776     try:
    777       result = self._run(None, fetches, feed_dict, options_ptr,
--> 778                          run_metadata_ptr)
    779       if run_metadata:
    780         proto_data = tf_session.TF_GetBuffer(run_metadata_ptr)

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _run(self, handle, fetches, feed_dict, options, run_metadata)
    980     if final_fetches or final_targets:
    981       results = self._do_run(handle, final_targets, final_fetches,
--> 982                              feed_dict_string, options, run_metadata)
    983     else:
    984       results = []

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1030     if handle is None:
   1031       return self._do_call(_run_fn, self._session, feed_dict, fetch_list,
-> 1032                            target_list, options, run_metadata)
   1033     else:
   1034       return self._do_call(_prun_fn, self._session, handle, feed_dict,

/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.pyc in _do_call(self, fn, *args)
   1050         except KeyError:
   1051           pass
-> 1052       raise type(e)(node_def, op, message)
   1053 
   1054   def _extend_graph(self):

NotFoundError: Tensor name "rnn_model/rnn/multi_rnn_cell/cell_0/lstm_cell/weights" not found in checkpoint files /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner/note_rnn.ckpt
	 [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_3', defined at:
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/traitlets/config/application.py", line 658, in launch_instance
    app.start()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel/kernelapp.py", line 477, in start
    ioloop.IOLoop.instance().start()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/zmq/eventloop/ioloop.py", line 177, in start
    super(ZMQIOLoop, self).start()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tornado/ioloop.py", line 888, in start
    handler_func(fd_obj, events)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 440, in _handle_events
    self._handle_recv()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 472, in _handle_recv
    self._run_callback(callback, msg)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/zmq/eventloop/zmqstream.py", line 414, in _run_callback
    callback(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tornado/stack_context.py", line 277, in null_wrapper
    return fn(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 283, in dispatcher
    return self.dispatch_shell(stream, msg)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 235, in dispatch_shell
    handler(stream, idents, msg)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel/kernelbase.py", line 399, in execute_request
    user_expressions, allow_stdin)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel/ipkernel.py", line 196, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/ipykernel/zmqshell.py", line 533, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2718, in run_cell
    interactivity=interactivity, compiler=compiler, result=result)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2822, in run_ast_nodes
    if self.run_code(code, result):
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-8910b466ad1e>", line 6, in <module>
    num_notes_in_melody=NUM_NOTES_IN_COMPOSITION)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.py", line 236, in __init__
    self.initialize_internal_models_graph_session()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.py", line 300, in initialize_internal_models_graph_session
    self.q_network.initialize_and_restore(self.session)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.py", line 142, in initialize_and_restore
    self.restore_vars_from_checkpoint(self.checkpoint_dir)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.py", line 274, in restore_vars_from_checkpoint
    saver = tf.train.Saver(var_list=var_dict)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1056, in __init__
    self.build()
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1086, in build
    restore_sequentially=self._restore_sequentially)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 669, in restore_v2
    dtypes=dtypes, name=name)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 768, in apply_op
    op_def=op_def)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2336, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/Users/jpope/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1228, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "rnn_model/rnn/multi_rnn_cell/cell_0/lstm_cell/weights" not found in checkpoint files /Users/jpope/Documents/gitWorkspace/magenta/magenta/models/rl_tuner/note_rnn.ckpt
	 [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_recv_save_1/Const_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

**Comment by johndpope** [comment]
same problem https://github.com/tensorflow/magenta/issues/590

**Comment by johndpope** [comment]
rl_tuner_train
Retrieving checkpoint of Note RNN from Magenta download server.
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x118524050>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:ERROR! No such primer file exists! ./testdata/primer.mid
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x118524dd0>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:ERROR! No such primer file exists! ./testdata/primer.mid
WARNING:tensorflow:<tensorflow.python.ops.rnn_cell_impl.LSTMCell object at 0x119697110>: Using a concatenated state is slower and will soon be deprecated.  Use state_is_tuple=True.
WARNING:tensorflow:ERROR! No such primer file exists! ./testdata/primer.mid
2017-06-07 14:07:58.519449: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 14:07:58.519468: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 14:07:58.519484: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 14:07:58.519489: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-06-07 14:07:58.519493: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
WARNING:tensorflow:Can't find checkpoint file, using /Users/jpope/note_rnn.ckpt
Traceback (most recent call last):
  File "/usr/local/bin/rl_tuner_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner_train.py", line 137, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner_train.py", line 115, in main
    algorithm=FLAGS.algorithm)
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.py", line 236, in __init__
    self.initialize_internal_models_graph_session()
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.py", line 300, in initialize_internal_models_graph_session
    self.q_network.initialize_and_restore(self.session)
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.py", line 142, in initialize_and_restore
    self.restore_vars_from_checkpoint(self.checkpoint_dir)
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.py", line 284, in restore_vars_from_checkpoint
    saver.restore(self.session, checkpoint_file)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.NotFoundError: Tensor name "rnn_model/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel" not found in checkpoint files /Users/jpope/note_rnn.ckpt
	 [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

Caused by op u'save_1/RestoreV2_3', defined at:
  File "/usr/local/bin/rl_tuner_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner_train.py", line 137, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner_train.py", line 115, in main
    algorithm=FLAGS.algorithm)
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.py", line 236, in __init__
    self.initialize_internal_models_graph_session()
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/rl_tuner.py", line 300, in initialize_internal_models_graph_session
    self.q_network.initialize_and_restore(self.session)
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.py", line 142, in initialize_and_restore
    self.restore_vars_from_checkpoint(self.checkpoint_dir)
  File "/usr/local/lib/python2.7/site-packages/magenta/models/rl_tuner/note_rnn_loader.py", line 274, in restore_vars_from_checkpoint
    saver = tf.train.Saver(var_list=var_dict)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 407, in _AddRestoreOps
    tensors = self.restore_op(filename_tensor, saveable, preferred_shard)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 247, in restore_op
    [spec.tensor.dtype])[0])
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/ops/gen_io_ops.py", line 640, in restore_v2
    dtypes=dtypes, name=name)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

NotFoundError (see above for traceback): Tensor name "rnn_model/rnn/multi_rnn_cell/cell_0/lstm_cell/kernel" not found in checkpoint files /Users/jpope/note_rnn.ckpt
	 [[Node: save_1/RestoreV2_3 = RestoreV2[dtypes=[DT_FLOAT], _device="/job:localhost/replica:0/task:0/cpu:0"](_arg_save_1/Const_0_0, save_1/RestoreV2_3/tensor_names, save_1/RestoreV2_3/shape_and_slices)]]

**Comment by Calvin-Shen** [comment]
how to solve this problem?thx  @ johndpope

**Comment by Calvin-Shen** [comment]
@johndpope
