### ISSUE TITLE
sketch-rnn-train - Error loading HParams

### ISSUE THREAD

**Issue by francescodelduchetto** [tensorflow/magenta#734]
When running the command for training
`$ sketch_rnn_train --log_root=models/ --data_dir=datasets/ --hparams="data_set=[theMonaLisa.npz]"`

I get the following error:
```

INFO:tensorflow:sketch-rnn
INFO:tensorflow:Hyperparams:
Traceback (most recent call last):
  File "/home/frahp/miniconda2/bin/sketch_rnn_train", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/frahp/miniconda2/lib/python2.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.py", line 476, in console_entry_point
    tf.app.run(main)
  File "/home/frahp/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/frahp/miniconda2/lib/python2.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.py", line 472, in main
    trainer(model_params)
  File "/home/frahp/miniconda2/lib/python2.7/site-packages/magenta/models/sketch_rnn/sketch_rnn_train.py", line 437, in trainer
    for key, val in model_params.keyvals.iteritems():
AttributeError: 'HParams' object has no attribute 'keyvals'
```
In _sketch_rnn_train.py", line 437_ the line `for key, val in model_params.keyvals.iteritems():` should be `for key, val in model_params.values().iteritems():` right?

**Comment by adarob** [comment]
Good catch. Could you submit a PR to fix?

**Comment by francescodelduchetto** [comment]
Done :thumbsup:

**Comment by hardmaru** [comment]
Thanks for the catch. We recently merged with TF's native HParams from the magenta HParams class
