### ISSUE TITLE
Error computing log likelihood of Performance RNN 

### ISSUE THREAD

**Issue by PeterMitrano** [tensorflow/magenta#766]
Here is how I'm trying to call it:

https://github.com/PeterMitrano/plonky/blob/performance_rnn/performance_fitness.py

Here is the traceback:
```
Traceback (most recent call last):
  File "./sassy.py", line 22, in <module>
    sys.exit(main(sys.argv))
  File "./sassy.py", line 18, in main
    fitness = ff.evaluate_fitness()
  File "/home/peter/Projects/plonky/performance_fitness.py", line 36, in evaluate_fitness
    return self.generator._model.performance_log_likelihood(sequence)
  File "/opt/miniconda2/envs/src_magenta/lib/python2.7/site-packages/magenta/models/performance_rnn/performance_model.py", line 62, in performance_log_likelihood
    return self._evaluate_log_likelihood([sequence])[0]
  File "/opt/miniconda2/envs/src_magenta/lib/python2.7/site-packages/magenta/models/shared/events_rnn_model.py", line 492, in _evaluate_log_likelihood
    initial_state[batch_indices])
TypeError: list indices must be integers, not xrange
```

The issue is that `initial_state`, in my case at least, ends up being a list, containing a list, containing a numpy array, like `[ [ numpy.array(lots of zeros here), numpy.array(lots of zeros here), ... more tensors of zeros ... ] ]`. I'm not sure if I'm doing something wrong or if there is a bug.

**Comment by iansimon** [comment]
It's a little bit awkward right now, but you have to pass a `Performance` object (not a list) to `performance_log_likelihood`.  And there's no easy way to create one from a list of events, you'll need to create an empty `Performance` and then append each event in turn.
