### ISSUE TITLE
Please don't overwrite existing .bash_profile contents

### ISSUE THREAD

**Issue by orgicus** [tensorflow/magenta#767]
I've just tried following the readme instructions and I proceeded confidently with this step:

```bash
WARNING:
    You currently have a PYTHONPATH environment variable set. This may cause
    unexpected behavior when running the Python interpreter in Miniconda2.
    For best results, please verify that your PYTHONPATH only points to
    directories of packages that are compatible with the Python interpreter
    in Miniconda2: /Users/George/miniconda2
Do you wish the installer to prepend the Miniconda2 install location
to PATH in your /Users/George/.bash_profile ? [yes|no]
[yes] >>> yes
```

Got a confirmation that sounds like what I expected:
```bash
Prepending PATH=/Users/George/miniconda2/bin to PATH in
newly created /Users/George/.bash_profile

For this change to become active, you have to open a new terminal.
```

However what I got in the end was totally not what I expected: my `.bash_profile` got totally wiped and replaced with:
```bash


# added by Miniconda2 4.3.21 installer
export PATH="/Users/George/miniconda2/bin:$PATH"
```
No prepend as described, no append, full replace! 👎 

I thought at least could have a play with magenta, but nope, not even that worked:

```python
Thank you for installing Miniconda2!

Share your notebooks and packages on Anaconda Cloud!
Sign up for free: https://anaconda.org


==============================
setting up magenta environment
==============================

Traceback (most recent call last):
  File "/Users/George/miniconda2/bin/conda", line 6, in <module>
    sys.exit(conda.cli.main())
  File "/Users/George/miniconda2/lib/python2.7/site-packages/conda/cli/main.py", line 179, in main
    return conda_exception_handler(_main, *args)
  File "/Users/George/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 636, in conda_exception_handler
    return handle_exception(e)
  File "/Users/George/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 626, in handle_exception
    print_unexpected_error_message(e)
  File "/Users/George/miniconda2/lib/python2.7/site-packages/conda/exceptions.py", line 588, in print_unexpected_error_message
    stderrlogger.info(get_main_info_str(get_info_dict()))
  File "/Users/George/miniconda2/lib/python2.7/site-packages/conda/cli/main_info.py", line 162, in get_info_dict
    from ..connection import user_agent
  File "/Users/George/miniconda2/lib/python2.7/site-packages/conda/connection.py", line 12, in <module>
    from requests import Session, __version__ as REQUESTS_VERSION
  File "/usr/local/lib/python2.7/site-packages/requests/__init__.py", line 52, in <module>
    from .packages.urllib3.contrib import pyopenssl
  File "/usr/local/lib/python2.7/site-packages/requests/packages/urllib3/contrib/pyopenssl.py", line 47, in <module>
    from cryptography import x509
  File "/Users/George/miniconda2/lib/python2.7/site-packages/cryptography/x509/__init__.py", line 7, in <module>
    from cryptography.x509.base import (
  File "/Users/George/miniconda2/lib/python2.7/site-packages/cryptography/x509/base.py", line 16, in <module>
    from cryptography.x509.extensions import Extension, ExtensionType
  File "/Users/George/miniconda2/lib/python2.7/site-packages/cryptography/x509/extensions.py", line 14, in <module>
    from asn1crypto.keys import PublicKeyInfo
  File "/Users/George/miniconda2/lib/python2.7/site-packages/asn1crypto/keys.py", line 22, in <module>
    from ._elliptic_curve import (
  File "/Users/George/miniconda2/lib/python2.7/site-packages/asn1crypto/_elliptic_curve.py", line 51, in <module>
    from ._int import inverse_mod
  File "/Users/George/miniconda2/lib/python2.7/site-packages/asn1crypto/_int.py", line 52, in <module>
    if platform.python_implementation() == 'PyPy':
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.py", line 1460, in python_implementation
    return _sys_version()[0]
  File "/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/platform.py", line 1422, in _sys_version
    repr(sys_version))
ValueError: failed to parse CPython sys.version: '2.7.13 |Continuum Analytics, Inc.| (default, Dec 20 2016, 23:05:08) \n[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]'

===========================================
Installation did not finish successfully.
Please follow the manual installation instructions at:
https://github.com/tensorflow/magenta
===========================================
```

Please update the installer script to actually prepend and not completely overwrite `.bash_profile`. It seems to backup the contents of the previous `.bash_profile` file `.profile` but the installer does not make this clear

Thank you,
George

**Comment by cghawthorne** [comment]
Hi @orgicus. Sorry to hear that your .bash_profile was overwritten. This part of the installation process is done by the miniconda installer, so I would suggest filing a bug report on their issue tracker: https://github.com/conda/conda/issues

For getting Magenta working, could you try following the manual installation instructions and see if that works?
