### ISSUE TITLE
NO attribute 'Hparams'

### ISSUE THREAD

**Issue by soma11soma11** [tensorflow/magenta#776]
https://github.com/tensorflow/magenta/tree/master/magenta/models/melody_rnn
When I tried to generate music with this code:

`melody_rnn_generate \
--config=${CONFIG} \
--bundle_file=${BUNDLE_PATH} \
--output_dir=/tmp/melody_rnn/generated \
--num_outputs=10 \
--num_steps=128 \
--primer_melody="[60]"`

I got an error saying:

`Traceback (most recent call last):
  File "/Users/soma/miniconda2/envs/magenta/bin/melody_rnn_generate", line 7, in <module>
    from magenta.models.melody_rnn.melody_rnn_generate import console_entry_point
  File "/Users/soma/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/__init__.py", line 17, in <module>
    from melody_rnn_model import MelodyRnnModel
  File "/Users/soma/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_model.py", line 143, in <module>
    tf.contrib.training.HParams(
AttributeError: 'module' object has no attribute 'HParams'
`

**Comment by cghawthorne** [comment]
This is likely caused by having an out of date version of TensorFlow. Can you check that you have the latest TensorFlow package installed and try again?
