### ISSUE TITLE
FailedPreconditionError when generating melodies with pre-trained model

### ISSUE THREAD

**Issue by davidlecea** [tensorflow/magenta#778]
I am getting a tensorflow.python.framework.errors_impl.FailedPreconditionError error whenever I try to generate a melody following the tutorial. The same thing happens regardless of which of the three pre-trained models.
Anybody can give me a hint of where the problem might be, please?
melody_rnn_generate \
> --config=${CONFIG} \
> --bundle_file=${BUNDLE_PATH} \
> --output_dir=/tmp/melody_rnn/generated \
> --num_outputs=10 \
> --num_steps=128 \
> --primer_melody="[60]"
Traceback (most recent call last):
  File "/usr/local/bin/melody_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 250, in console_entry_point
    tf.app.run(main)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 223, in main
    bundle = get_bundle()
  File "/usr/local/lib/python2.7/dist-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 127, in get_bundle
    return magenta.music.read_bundle_file(bundle_file)
  File "/usr/local/lib/python2.7/dist-packages/magenta/music/sequence_generator_bundle.py", line 34, in read_bundle_file
    bundle.ParseFromString(f.read())
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 125, in read
    pywrap_tensorflow.ReadFromStream(self._read_buf, length, status))
  File "/usr/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.FailedPreconditionError: /home/ubuntu/workspace/magenta/magenta-models

**Comment by adarob** [comment]
It looks like you might not be setting BUNDLE_PATH to point to the bundle
file you want to use. If you think you have set it, you can try typing the
command 'echo $BUNDLE_FILE' and see if it prints out the correct path.

-Adam

**Comment by davidlecea** [comment]
Indeed, I was pointing to the directory that contains to the models, not to the specific .mag file.
Thank you!
