### ISSUE TITLE
magenta.music.sequence_generator.SequenceGeneratorException: Checkpoint path does not exist: /tmp/melody_rnn/logdir/run1/train

### ISSUE THREAD

**Issue by dbl001** [tensorflow/magenta#786]
Here's my run command:
```
$ bazel run //magenta/models/melody_rnn:melody_rnn_generate -- --config=attention_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --output_dir=/tmp/melody_rnn/generated --num_outputs=10 --num_steps=128 --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --primer_melody="[60]"

$ ls -l /tmp/melody_rnn/
total 0
drwxr-xr-x  2 davidlaxer  wheel   68 Jul 19 11:51 generated
drwxr-xr-x  3 davidlaxer  wheel  102 Jul 19 12:13 logdir
```
Here's the output:
```
INFO: Running command line: bazel-bin/magenta/models/melody_rnn/melody_rnn_generate '--config=attention_rnn' '--run_dir=/tmp/melody_rnn/logdir/run1' '--output_dir=/tmp/melody_rnn/generated' '--num_outputs=10' '--num_steps=128' '--hparams=batch_size=64,rnn_layer_sizes=[64,64]' '--primer_melody=[60]'
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 254, in <module>
    console_entry_point()
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 250, in console_entry_point
    tf.app.run(main)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 246, in main
    run_with_flags(generator)
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_generate.py", line 209, in run_with_flags
    generated_sequence = generator.generate(input_sequence, generator_options)
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/music/sequence_generator.py", line 195, in generate
    self.initialize()
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_generate.runfiles/__main__/magenta/music/sequence_generator.py", line 128, in initialize
    'Checkpoint path does not exist: %s' % (self._checkpoint))
magenta.music.sequence_generator.SequenceGeneratorException: Checkpoint path does not exist: /tmp/melody_rnn/logdir/run1/train
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```
Any ideas?

**Comment by dbl001** [comment]
Perhaps melody_rnn:melody_rnn_generate is looking for an existing trained model.
I tried this:
$ bazel run //magenta/models/melody_rnn:melody_rnn_train -- --config=attention_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=./magenta/testdata/notesequences.tfrecord --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --num_training_steps=20000 --eval
INFO: Found 1 target...
Target //magenta/models/melody_rnn:melody_rnn_train up-to-date:
  bazel-bin/magenta/models/melody_rnn/melody_rnn_train
INFO: Elapsed time: 0.398s, Critical Path: 0.00s

INFO: Running command line: bazel-bin/magenta/models/melody_rnn/melody_rnn_train '--config=attention_rnn' '--run_dir=/tmp/melody_rnn/logdir/run1' '--sequence_example_file=./magenta/testdata/notesequences.tfrecord' '--hparams=batch_size=64,rnn_layer_sizes=[64,64]' '--num_training_steps=20000' --eval
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 112, in <module>
    console_entry_point()
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 108, in console_entry_point
    tf.app.run(main)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 76, in main
    os.path.expanduser(FLAGS.sequence_example_file))
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/lib/io/file_io.py", line 334, in get_matching_files
    compat.as_bytes(single_filename), status)
  File "/Users/davidlaxer/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 466, in raise_exception_on_not_ok_status
    pywrap_tensorflow.TF_GetCode(status))
tensorflow.python.framework.errors_impl.NotFoundError: ./magenta/testdata
ERROR: Non-zero return code '1' from command: Process exited with status 1
