### ISSUE TITLE
InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]

### ISSUE THREAD

**Issue by reido2012** [tensorflow/magenta#787]
I initially trained the performance_rnn on a set of midi files. Once the accuracy reached `90+%` I stopped the training and tried to generate a new performance from my model. This gave an error saying that the shapes of the tensors need to match. The error shown in the stack trace below. 

The error is the same no matter how many midi files you use.

So I then trained on a single midi file from the Yamaha Competition dataset . 

For the training command I used:

```
export CUDA_VISIBLE_DEVICES=2; performance_rnn_train \
--config='performance_with_dynamics' \       
--run_dir=/tmp/performance_rnn/logdir/2run1 \
--sequence_example_file=/tmp/performance_rnn/2/sequence_examples/training_performances.tfrecord`
```
I then ran the command for generation:

```
performance_rnn_generate \
--run_dir=/tmp/performance_rnn/logdir/2run1 \
--output_dir=/tmp/performance_rnn/generated \
--num_outputs=10 \
--num_steps=3000 \
--primer_melody="[60,62]"
```

The stack trace was 

```
INFO:tensorflow:hparams = {'rnn_layer_sizes': [512, 512, 512], 'learning_rate': 0.001, 'clip_norm': 3, 'batch_size': 1, 'dropout_keep_prob': 1.0}
2017-07-20 16:41:39.723856: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 16:41:39.723888: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 16:41:39.723897: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 16:41:39.723903: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX2 instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 16:41:39.723909: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use FMA instructions, but these are available on your machine and could speed up CPU computations.
2017-07-20 16:41:39.877811: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX TITAN X
major: 5 minor: 2 memoryClockRate (GHz) 1.076
pciBusID 0000:03:00.0
Total memory: 11.92GiB
Free memory: 378.12MiB
2017-07-20 16:41:39.877847: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-07-20 16:41:39.877857: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-07-20 16:41:39.877868: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX TITAN X, pci bus id: 0000:03:00.0)
INFO:tensorflow:Checkpoint used: /tmp/performance_rnn/logdir/2run1/train/model.ckpt-217
INFO:tensorflow:Restoring parameters from /tmp/performance_rnn/logdir/2run1/train/model.ckpt-217
2017-07-20 16:41:39.920743: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-20 16:41:39.929536: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-20 16:41:39.934642: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-20 16:41:39.937203: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-20 16:41:39.937390: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-20 16:41:39.937485: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-20 16:41:39.940061: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
Traceback (most recent call last):
  File "/home/oreid/.local/bin/performance_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/home/oreid/.local/lib/python2.7/site-packages/magenta/models/performance_rnn/performance_rnn_generate.py", line 251, in console_entry_point
    tf.app.run(main)
  File "/home/oreid/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/oreid/.local/lib/python2.7/site-packages/magenta/models/performance_rnn/performance_rnn_generate.py", line 247, in main
    run_with_flags(generator)
  File "/home/oreid/.local/lib/python2.7/site-packages/magenta/models/performance_rnn/performance_rnn_generate.py", line 209, in run_with_flags
    generated_sequence = generator.generate(primer_sequence, generator_options)
  File "/home/oreid/.local/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 195, in generate
    self.initialize()
  File "/home/oreid/.local/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 141, in initialize
    self._model.initialize_with_checkpoint(checkpoint_file)
  File "/home/oreid/.local/lib/python2.7/site-packages/magenta/music/model.py", line 63, in initialize_with_checkpoint
    saver.restore(self._session, checkpoint_file)
  File "/home/oreid/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/oreid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/oreid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/oreid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/oreid/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
```

Thanks

**Comment by sanz999** [comment]
I have this exact same problem. I'd love to see a workaround soon!
