### ISSUE TITLE
Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]

### ISSUE THREAD

**Issue by sanz999** [tensorflow/magenta#793]
I was following the tutorial on performance rnn and trained it from scratch on a new dataset. Now, I want to evaluate it and generate midi files, but I am getting an error when I run the scripts for these. Here's the full trace:

```
INFO:tensorflow:Checkpoint used: /tmp/performance_rnn/logdir/run1/train/model.ckpt-14520
INFO:tensorflow:Restoring parameters from /tmp/performance_rnn/logdir/run1/train/model.ckpt-14520
2017-07-21 19:48:41.712434: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-21 19:48:41.712446: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-21 19:48:41.713017: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-21 19:48:41.717734: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-21 19:48:41.724638: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
2017-07-21 19:48:41.734518: W tensorflow/core/framework/op_kernel.cc:1158] Invalid argument: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
Traceback (most recent call last):
  File "performance_rnn_generate.py", line 255, in <module>
    console_entry_point()
  File "performance_rnn_generate.py", line 251, in console_entry_point
    tf.app.run(main)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "performance_rnn_generate.py", line 247, in main
    run_with_flags(generator)
  File "performance_rnn_generate.py", line 209, in run_with_flags
    generated_sequence = generator.generate(primer_sequence, generator_options)
  File "/home/sanz999/.local/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 195, in generate
    self.initialize()
  File "/home/sanz999/.local/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 141, in initialize
    self._model.initialize_with_checkpoint(checkpoint_file)
  File "/home/sanz999/.local/lib/python2.7/site-packages/magenta/music/model.py", line 63, in initialize_with_checkpoint
    saver.restore(self._session, checkpoint_file)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1548, in restore
    {self.saver_def.filename_tensor_name: save_path})
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.InvalidArgumentError: Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
	 [[Node: save/RestoreV2_4/_8 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_28_save/RestoreV2_4", _device="/job:localhost/replica:0/task:0/cpu:0"](save/RestoreV2_4)]]

Caused by op u'save/Assign', defined at:
  File "performance_rnn_generate.py", line 255, in <module>
    console_entry_point()
  File "performance_rnn_generate.py", line 251, in console_entry_point
    tf.app.run(main)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "performance_rnn_generate.py", line 247, in main
    run_with_flags(generator)
  File "performance_rnn_generate.py", line 209, in run_with_flags
    generated_sequence = generator.generate(primer_sequence, generator_options)
  File "/home/sanz999/.local/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 195, in generate
    self.initialize()
  File "/home/sanz999/.local/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 141, in initialize
    self._model.initialize_with_checkpoint(checkpoint_file)
  File "/home/sanz999/.local/lib/python2.7/site-packages/magenta/music/model.py", line 60, in initialize_with_checkpoint
    saver = tf.train.Saver()
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1139, in __init__
    self.build()
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1170, in build
    restore_sequentially=self._restore_sequentially)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 691, in build
    restore_sequentially, reshape)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 419, in _AddRestoreOps
    assign_ops.append(saveable.restore(tensors, shapes))
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 155, in restore
    self.op.get_shape().is_fully_defined())
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/ops/state_ops.py", line 271, in assign
    validate_shape=validate_shape)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/ops/gen_state_ops.py", line 45, in assign
    use_locking=use_locking, name=name)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/sanz999/.local/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InvalidArgumentError (see above for traceback): Assign requires shapes of both tensors to match. lhs shape= [356] rhs shape= [388]
	 [[Node: save/Assign = Assign[T=DT_FLOAT, _class=["loc:@fully_connected/biases"], use_locking=true, validate_shape=true, _device="/job:localhost/replica:0/task:0/gpu:0"](fully_connected/biases, save/RestoreV2/_1)]]
	 [[Node: save/RestoreV2_4/_8 = _Send[T=DT_FLOAT, client_terminated=false, recv_device="/job:localhost/replica:0/task:0/gpu:0", send_device="/job:localhost/replica:0/task:0/cpu:0", send_device_incarnation=1, tensor_name="edge_28_save/RestoreV2_4", _device="/job:localhost/replica:0/task:0/cpu:0"](save/RestoreV2_4)]]

```
It seems like my trained checkpoint has different parameters than expected by the model. However, hparams should be the same because I didn't specify any for either. I used the default scripts on the readme on performance rnn's github page. I am using the latest version of tensorflow and magenta. What is going wrong? This could be a bug.

**Comment by cghawthorne** [comment]
I think this is the same problem as #787.
