### ISSUE TITLE
Error when building with primer.mid

### ISSUE THREAD

**Issue by rpagliarix** [tensorflow/magenta#82]
I'm getting this when generating the melody with primer.mid

```
Traceback (most recent call last):
  File "..../ec4a1d0982b871d144edb5a331b7959f/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn_generate.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_generate.py", line 275, in <module>
    tf.app.run()
  File ".../tensorflow/local/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File ".../ec4a1d0982b871d144edb5a331b7959f/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn_generate.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_generate.py", line 263, in main
    FLAGS.num_steps))
  File ".../ec4a1d0982b871d144edb5a331b7959f/execroot/magenta/bazel-out/local-opt/bin/magenta/models/basic_rnn_generate.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_generate.py", line 184, in sampler_loop
    saver.restore(session, checkpoint_file)
  File "..../tensorflow/local/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1102, in restore
    if not pywrap_tensorflow.get_matching_files(save_path):
  File "..../tensorflow/local/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 379, in get_matching_files
    return GetMatchingFiles(compat.as_bytes(filename), status)
  File "/...python2.7/site-packages/tensorflow/python/util/compat.py", line 44, in as_bytes
    raise TypeError('Expected binary or unicode string, got %r' % bytes_or_text)
TypeError: Expected binary or unicode string, got None
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by cinjon** [comment]
rpagliarix, did you solve this?

**Comment by rpagliarix** [comment]
nope

**Comment by elliotwaite** [comment]
It looks like the error is occurring because a checkpoint file cannot be found in the specified experiment_run_dir. When you call basic_rnn_generate, the code looks for a checkpoint file in the 'train' subdirectory within the specified --experiment_run_dir. For example, if --experiment_run_dir=/tmp/basic_rnn/run1, the code looks for a checkpoint file in /tmp/basic_rnn/run1/train/. Does that location contain a checkpoint file for your trained model? Your --experiment_run_dir flag should point to the same --experiment_run_dir used when calling basic_rnn_train.
