### ISSUE TITLE
Midi Decoding Error <type 'exceptions.IOError':MThd not found. 

### ISSUE THREAD

**Issue by VilmosSzav** [tensorflow/magenta#829]
Hello, I'm new to Magenta and was following the tutorial provided under Magenta's Melody_rnn section.  However, I've run into a problem that I can't for the life of me figure out.  My input was this:

`Josephs-MacBook:~ me$ melody_rnn_generate \
> --config=attention_rnn \
> --bundle_file=/Applications/Tensorflow/Magenta/attention_rnn.mag \
> --output_dir=/private/tmp/melody_rnn/generated \
> --num_outputs=10 \
> --num_steps=128 \
> --primer_midi=/Users/me/miniconda2/lib/python2.7/site-packages/magenta/models/melody_rnn/Avicii\ -\ Levels.mid `

To which the terminal responds with this: 

`Traceback (most recent call last):
  File "/Users/me/miniconda2/bin/melody_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/Users/me/miniconda2/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 250, in console_entry_point
    tf.app.run(main)
  File "/Users/me/miniconda2/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/me/miniconda2/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 246, in main
    run_with_flags(generator)
  File "/Users/me/miniconda2/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 156, in run_with_flags
    primer_sequence = magenta.music.midi_file_to_sequence_proto(primer_midi)
  File "/Users/me/miniconda2/lib/python2.7/site-packages/magenta/music/midi_io.py", line 309, in midi_file_to_sequence_proto
    return midi_to_sequence_proto(midi_as_string)
  File "/Users/me/miniconda2/lib/python2.7/site-packages/magenta/music/midi_io.py", line 82, in midi_to_sequence_proto
    (sys.exc_info()[0], sys.exc_info()[1]))
magenta.music.midi_io.MIDIConversionError: Midi decoding error <type 'exceptions.IOError'>: MThd not found. Probably not a MIDI file`

I am using a 2016 MacBook running python 2.7.  I have tried over 30 different midi files from different sources and all return this error.  Any help or ideas would be greatly appreciated.

**Comment by cghawthorne** [comment]
Hmm, I'm not sure what would cause that other than a corrupt midi file. Can you try using the example midi file from the Magenta repo and see if that works? https://github.com/tensorflow/magenta/raw/master/magenta/testdata/example.mid

**Comment by Vickyilango** [comment]
Not a proper midi format: Try changing the files. I found this script in another git https://github.com/mido/mido/issues/107

Script:
import mido
import os 
from mido import Message, MidiFile, MidiTrack
import sys

def process(filename):
    #mid = mido.read_syx_file(filename)
    mid = MidiFile(filename)
    for track in mid.tracks:
       for i, msg in enumerate(track):
            if msg.type == 'control_change':
                ped = msg.value
                pedfix = abs(ped-127)
                # Replace message in track.                                         
                track[i] = msg.copy(value=pedfix)

    mid.save('*' + filename)


for f in os.listdir('.'):
    # for f in os.listdir('./midifiles'):
    process(f)
