### ISSUE TITLE
Unicode error when trying to run basic rnn training

### ISSUE THREAD

**Issue by afuhrtrumpet** [tensorflow/magenta#83]
On Ubuntu 16.04 no GPU, I followed the instructions to create MIDI note sequences with these MIDI files:[dkc2.zip](https://github.com/tensorflow/magenta/files/348866/dkc2.zip) saved in /tmp/vgnotesequences2.tfrecord. Then ran the command

`./bazel-bin/magenta/models/basic_rnn_train --experiment_run_dir=/tmp/basic_rnn/run1 --sequence_example_file=/tmp/vgnotesequences2.tfrecord --eval=false --hparams='{"rnn_layer_sizes":[50]}' --num_training_steps=20000`

And ended up with this error:

`INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode byte 0xed in position 143: invalid continuation byte
Error reported to Coordinator: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode byte 0xed in position 143: invalid continuation byte
Got error reported to coordinator: PaddingFIFOQueue '_1_rnn_model/padding_fifo_queue' is closed and has insufficient elements (requested 128, current size 0)
	 [[Node: rnn_model/padding_fifo_queue_DequeueMany = QueueDequeueMany[_class=["loc:@rnn_model/padding_fifo_queue"], component_types=[DT_FLOAT, DT_INT64, DT_INT32], timeout_ms=-1, _device="/job:localhost/replica:0/task:0/cpu:0"](rnn_model/padding_fifo_queue, rnn_model/padding_fifo_queue_DequeueMany/n)]]
Caused by op u'rnn_model/padding_fifo_queue_DequeueMany', defined at:
  File "/home/alex/magenta/bazel-bin/magenta/models/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 449, in <module>
    tf.app.run()
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/platform/app.py", line 30, in run
    sys.exit(main(sys.argv))
  File "/home/alex/magenta/bazel-bin/magenta/models/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 422, in main
    hparams_string=FLAGS.hparams, is_eval_mode=FLAGS.eval)
  File "/home/alex/magenta/bazel-bin/magenta/models/basic_rnn_train.runfiles/__main__/magenta/models/basic_rnn/basic_rnn_train.py", line 203, in make_graph
    lengths) = basic_rnn_ops.dynamic_rnn_batch(file_list, hparams)
  File "/home/alex/magenta/magenta/models/basic_rnn/basic_rnn_ops.py", line 125, in dynamic_rnn_batch
    return queue.dequeue_many(hparams.batch_size)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/data_flow_ops.py", line 434, in dequeue_many
    self._queue_ref, n=n, component_types=self._dtypes, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_data_flow_ops.py", line 465, in _queue_dequeue_many
    timeout_ms=timeout_ms, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/op_def_library.py", line 704, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2260, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1230, in __init__
    self._traceback = _extract_stack()`

I assume there is some sort of incorrect character in the midi data, but the note sequence parser did not have any issue with these midis so there may be something else going on. I have gotten similar errors with other sets of MIDI files.

**Comment by cinjon** [comment]
afuhrtrumpet, did you figure this out?

**Comment by afuhrtrumpet** [comment]
I did not. I was looking at diving deeper into the source of the issue later.

**Comment by danabo** [comment]
I was able to reproduce the error earlier. Since then, I updated my TensorFlow install to 0.9.0 and we made changed to Magenta. Now when I create the dataset and run training it doesn't crash. Seems the issue may have been magically fixed.

Can you make sure you are running tensorflow 0.9.0 and pull in recent Magenta changes, and then try again?

**Comment by osetinsky** [comment]
@afuhrtrumpet I encountered something similar. I believe that you are confusing the output of convert_midi_dir_to_note_sequences.py. with that of basic_rnn_create_dataset.py

So first create a /tmp/notesequences.tfrecord with convert_midi_dir_to_note_sequences.py, and then create a /tmp/basic_rnn/sequence_examples/training_melodies.tfrecord with basic_rnn_create_dataset.py

It's training_melodies.tfrecord that you want to pass to --sequence_example_file

**Comment by afuhrtrumpet** [comment]
I think I was confusing the output. However I can't run the current version of basic_rnn_train due to #102 at the moment to verify this.

**Comment by cghawthorne** [comment]
@afuhrtrumpet sounds like #102 got resolved. Are you still having problems with this issue?

**Comment by afuhrtrumpet** [comment]
Nope, ran some training iterations last night, this seems to be resolved.

**Comment by dbl001** [comment]
Is this the same issue?
```
$ bazel run //magenta/models/melody_rnn:melody_rnn_train -- --config=attention_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=/Users/davidlaxer/magenta/magenta/testdata/notesequences.tfrecord --hparams="batch_size=10,rnn_layer_sizes=[64,64]" **--save_summaries_secs=10000 --save_interval_secs=10000** --num_training_steps=20000 
Killed non-responsive server process (pid=65119)
.
INFO: Found 1 target...
Target //magenta/models/melody_rnn:melody_rnn_train up-to-date:
  bazel-bin/magenta/models/melody_rnn/melody_rnn_train
INFO: Elapsed time: 9.400s, Critical Path: 0.65s

INFO: Running command line: bazel-bin/magenta/models/melody_rnn/melody_rnn_train '--config=attention_rnn' '--run_dir=/tmp/melody_rnn/logdir/run1' '--sequence_example_file=/Users/davidlaxer/magenta/magenta/testdata/notesequences.tfrecord' '--hparams=batch_size=10,rnn_layer_sizes=[64,64]' '**--save_summaries_secs=10000' '--save_interval_secs=10000**' '--num_training_steps=20000'
INFO:tensorflow:hparams = {'rnn_layer_sizes': [64, 64], 'attn_length': 40, 'dropout_keep_prob': 0.5, 'batch_size': 10, 'clip_norm': 3, 'learning_rate': 0.001}
INFO:tensorflow:Counting records in /Users/davidlaxer/magenta/magenta/testdata/notesequences.tfrecord.
INFO:tensorflow:Total records: 46
INFO:tensorflow:[<tf.Tensor 'random_shuffle_queue_Dequeue:0' shape=(?, 74) dtype=float32>, <tf.Tensor 'random_shuffle_queue_Dequeue:1' shape=(?,) dtype=int64>, <tf.Tensor 'random_shuffle_queue_Dequeue:2' shape=() dtype=int32>]
INFO:tensorflow:Train dir: /tmp/melody_rnn/logdir/run1/train
INFO:tensorflow:Starting training loop...
INFO:tensorflow:Create CheckpointSaverHook.
INFO:tensorflow:Error reported to Coordinator: <type 'exceptions.UnicodeDecodeError'>, 'utf8' codec can't decode byte 0xe0 in position 132: invalid continuation byte
INFO:tensorflow:Saving checkpoints for 0 into /tmp/melody_rnn/logdir/run1/train/model.ckpt.
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 112, in <module>
    console_entry_point()
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 108, in console_entry_point
    tf.app.run(main)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/melody_rnn/melody_rnn_train.py", line 104, in main
    checkpoints_to_keep=FLAGS.num_checkpoints)
  File "/private/var/tmp/_bazel_davidlaxer/182280691ad889ad33cd20c0640dc2b1/execroot/magenta/bazel-out/local-opt/bin/magenta/models/melody_rnn/melody_rnn_train.runfiles/__main__/magenta/models/shared/events_rnn_train.py", line 71, in run_training
    save_summaries_steps=summary_frequency)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/contrib/training/python/training/training.py", line 530, in train
    loss = session.run(train_op)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 521, in __exit__
    self._close_internal(exception_type)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 556, in _close_internal
    self._sess.close()
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 791, in close
    self._sess.close()
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/training/monitored_session.py", line 888, in close
    ignore_live_threads=True)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/training/coordinator.py", line 389, in join
    six.reraise(*self._exc_info_to_raise)
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/training/queue_runner_impl.py", line 238, in _run
    enqueue_callable()
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1063, in _single_operation_run
    target_list_as_strings, status, None)
  File "/Users/davidlaxer/anaconda/lib/python2.7/contextlib.py", line 24, in __exit__
    self.gen.next()
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/framework/errors_impl.py", line 465, in raise_exception_on_not_ok_status
    compat.as_text(pywrap_tensorflow.TF_Message(status)),
  File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/tensorflow/python/util/compat.py", line 84, in as_text
    return bytes_or_text.decode(encoding)
  File "/Users/davidlaxer/anaconda/lib/python2.7/encodings/utf_8.py", line 16, in decode
    return codecs.utf_8_decode(input, errors, True)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xe0 in position 132: invalid continuation byte
ERROR: Non-zero return code '1' from command: Process exited with status 1.
```

**Comment by cghawthorne** [comment]
@dbl001 that looks like a different error caused by copy/pasting unicode characters into your command. If you continue to have the problem, please open a new bug.

**Comment by dbl001** [comment]
Python indicates the bazel command is an ‘ordinary string’.

$ bazel run //magenta/models/melody_rnn:melody_rnn_train -- --config=attention_rnn --run_dir=/tmp/melody_rnn/logdir/run1 --sequence_example_file=/Users/davidlaxer/magenta/magenta/testdata/notesequences.tfrecord --hparams="batch_size=10,rnn_layer_sizes=[64,64]" **--save_summaries_secs=10000 --save_interval_secs=10000** --num_training_steps=20000

Open a new issue?

**Comment by dbl001** [comment]
Also, something in ‘magenta’ wanted me to revert from numpy 0.20.3 to umpy 0.19.2

Error: 

File "/Users/davidlaxer/anaconda/lib/python2.7/site-packages/dask/dataframe/core.py", line 38, in <module>
    pd.computation.expressions.set_use_numexpr(False)
AttributeError: 'module' object has no attribute 'computation'

In [2]: print pandas.__version__
0.20.3

In [3]: quit
David-Laxers-MacBook-Pro:magenta davidlaxer$ conda install pandas=0.19.2
