### ISSUE TITLE
Nsynth - RuntimeError: Folder must contain .wav or .npy files.

### ISSUE THREAD

**Issue by tatecarson** [tensorflow/magenta#830]
I'm getting this error when trying to run the nsynth example. Here the input and the error message. Any ideas? The folder definitely has wav files in it. 

```
(magenta) tate-2:jupyter-notebooks tatecarson$ nsynth_generate \
> --checkpoint_path= /Users/tatecarson/Documents/tensorflow/magenta/pre-trained/wavenet-ckpt/model.ckpt-200000.data-00000-of-00001 \
> --source_path= '/Users/tatecarson/Desktop/Kea' \
> --save_path= /private/tmp/nsynth  \
> --batch_size=4
Traceback (most recent call last):
  File "/Users/tatecarson/miniconda2/envs/magenta/bin/nsynth_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/Users/tatecarson/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 89, in console_entry_point
    tf.app.run(main)
  File "/Users/tatecarson/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/tatecarson/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 57, in main
    raise RuntimeError("Folder must contain .wav or .npy files.")
RuntimeError: Folder must contain .wav or .npy files.
```

**Comment by jesseengel** [comment]
That's odd, these are the relevant lines of code from nsynth_generate.py. It explicitly is looking for files ending in ".wav" so you can make sure that's the case. you could also try throwing in a print statement to see if it's picking up the files properly.

```python
    files = tf.gfile.ListDirectory(source_path)
    exts = [os.path.splitext(f)[1] for f in files]
    if ".wav" in exts:
      postfix = ".wav"
    elif ".npy" in exts:
      postfix = ".npy"
    else:
      raise RuntimeError("Folder must contain .wav or .npy files.")
```

**Comment by tatecarson** [comment]
```
(magenta) tate-2:~ tatecarson$ nsynth_generate \
> --checkpoint_path= /Users/tatecarson/Documents/tensorflow/magenta/pre-trained/wavenet-ckpt/model.ckpt-200000.data-00000-of-00001 \
> --source_path= /Users/tatecarson/Desktop/Kea \
> --save_path= /private/tmp/nsynth  \
> --batch_size=4
source path is /Users/tatecarson
Traceback (most recent call last):
  File "/Users/tatecarson/miniconda2/envs/magenta/bin/nsynth_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/Users/tatecarson/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 92, in console_entry_point
    tf.app.run(main)
  File "/Users/tatecarson/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/tatecarson/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/nsynth/wavenet/nsynth_generate.py", line 60, in main
    raise RuntimeError("Folder must contain .wav or .npy files.")
RuntimeError: Folder must contain .wav or .npy files.
(magenta) tate-2:~ tatecarson$ 
```

See `source path is /Users/tatecarson` . Why does that not = `--source_path= /Users/tatecarson/Desktop/Kea` ?

**Comment by jesseengel** [comment]
I think you have a space after you equals sign. It should work if you get rid of the whitespaces.

`--source_path= /Users/tatecarson/Desktop/Kea \`
-->
`--source_path=/Users/tatecarson/Desktop/Kea \`

**Comment by tatecarson** [comment]
Fixed, thank you!
