### ISSUE TITLE
why the .mag file can't use to generated midi file?

### ISSUE THREAD

**Issue by mbs6176966** [tensorflow/magenta#900]
Use the other machine to generate .mag file, why not use it on machines that are not generated.I use A computer train model and generate .mag file using A's GPU tensorflow. and then I transfer .mag file from A to computer B,  i just want to use B's CPU tensorflow through .mag file to generate midi file. but I can't work!
Error like this:
INFO:tensorflow:Restoring parameters from /var/folders/rd/nj0gbtjn02g6t95_976lwxch0000gn/T/tmpCwHYnE/model.ckpt
Traceback (most recent call last):
  File "/Users/calvin/miniconda2/envs/magenta/bin/melody_rnn_generate", line 11, in <module>
    sys.exit(console_entry_point())
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 258, in console_entry_point
    tf.app.run(main)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 254, in main
    run_with_flags(generator)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_generate.py", line 225, in run_with_flags
    generated_sequence = generator.generate(input_sequence, generator_options)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/music/sequence_generator.py", line 204, in generate
    return self._generate(input_sequence, generator_options)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_sequence_generator.py", line 114, in _generate
    end_step - melody.start_step, melody, **args)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/melody_rnn/melody_rnn_model.py", line 61, in generate_melody
    branch_factor, steps_per_iteration)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/shared/events_rnn_model.py", line 392, in _generate_events
    control_events, modify_events_callback)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/shared/events_rnn_model.py", line 305, in _beam_search
    inputs, initial_state, temperature)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/shared/events_rnn_model.py", line 197, in _generate_branches
    all_event_sequences, all_inputs, all_final_state, temperature)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/shared/events_rnn_model.py", line 136, in _generate_step
    temperature)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/models/shared/events_rnn_model.py", line 97, in _generate_step_for_batch
    [graph_final_state, graph_softmax], feed_dict)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 895, in run
    run_metadata_ptr)
  File "/Users/calvin/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1100, in _run
    % (np_val.shape, subfeed_t.name, str(subfeed_t.get_shape())))
ValueError: Cannot feed value of shape (1, 2, 74) for Tensor u'Placeholder:0', which has shape '(64, ?, 74)'

**Comment by mbs6176966** [comment]
I will be grateful if anyone can help~

**Comment by mbs6176966** [comment]
this is the command i typed in the terminal.
melody_rnn_generate --config='attention_rnn' --bundle_file=/Users/calvin/Desktop/generate.mag  --output_dir=/Users/calvin/Desktop/  --num_outputs=1 --num_steps=1280 --primer_melody="[60]"

**Comment by cghawthorne** [comment]
Where did generate.mag come from? Are you sure it came from an attention_rnn config? If it came from a different config, that would explain the error message.

**Comment by mbs6176966** [comment]
The .mag file was trained by myself using the attention_rnn config at A computer.   Then I transfer the gernerated .mag file From A computer to B computer to gernerate midi file.  Facing the problem above.   @cghawthorne

**Comment by cghawthorne** [comment]
Can you include the commands you used to train and save the bundle file?

**Comment by Calvin-Shen** [comment]
okay,thanks for your attention~
The training commands are like this:
melody_rnn_train --config=attention_rnn --run_dir=/home/kunsound/Desktop/run --sequence_example_file=/home/kunsound/Desktop/sequence-example/eval_melodies.tfrecord --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --num_training_steps=100000

And the save bundle file command is like this:
melody_rnn_generate --config=attention_rnn --run_dir=/home/kunsound/Desktop/run  --hparams="batch_size=64,rnn_layer_sizes=[64,64]" --bundle_file=/home/kunsound/Desktop/MyAttention.mag --save_generator_bundle

**Comment by Jovonni** [comment]
Curious about this as well

**Comment by Ruslan-Pantaev** [comment]
It's possible that the hparams used when training / saving bundle / generating with attention_rnn were different. Are you sure you used the same values during all steps? Otherwise it should work if you used attention_rnn all throughout. Perhaps different systems or pc builds set diffrrent "default" hparams values? In that case, manually enter the same hparams used on machine B as machine A.
