### ISSUE TITLE
Blas GEMM launch failed on a second instance of the MIDI interface

### ISSUE THREAD

**Issue by CircuV** [tensorflow/magenta#903]
I'm getting an error when running a second instance of the MIDI interface (magenta_midi).
Starting that instance runs fine but when I send MIDI notes that instance crashes with the 
following error.
First instance runs ok.
Any idea? 
Thx
--cv

INFO:tensorflow:State: Idle
INFO:tensorflow:State: Listening
INFO:tensorflow:State: Listening
INFO:tensorflow:State: Listening
INFO:tensorflow:State: Responding
INFO:tensorflow:Generating sequence using 'multiconditioned_performance_with_dynamics' generator.
DEBUG:tensorflow:Generator Details: id: "multiconditioned_performance_with_dynamics"
description: "Density- and pitch-conditioned Performance RNN"

DEBUG:tensorflow:Bundle Details: description: "Density- and pitch-conditioned Performance RNN with dynamics"

DEBUG:tensorflow:Generator Options: input_sections {
  end_time: 6.0
}
generate_sections {
  start_time: 6.0
  end_time: 12.0
}
args {
  key: "temperature"
  value {
    float_value: 1.0
  }
}

WARNING:tensorflow:Conditioning on note density but none requested, using default.
WARNING:tensorflow:Conditioning on pitch histogram but none requested, using default.
INFO:tensorflow:Need to generate 599 more steps for this sequence, will try asking for 240 RNN steps
2017-09-30 16:38:25.254519: E tensorflow/stream_executor/cuda/cuda_blas.cc:365] failed to create cublas handle: CUBLAS_STATUS_NOT_INITIALIZED
2017-09-30 16:38:25.254557: W tensorflow/stream_executor/stream.cc:1601] attempting to perform BLAS operation using StreamExecutor without BLAS support
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/interfaces/midi/midi_interaction.py", line 450, in run
    response_start_time + response_duration)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/interfaces/midi/midi_interaction.py", line 339, in _generate
    adjust_sequence_times(input_sequence, -zero_time), generator_options)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/music/sequence_generator.py", line 196, in generate
    return self._generate(input_sequence, generator_options)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/models/performance_rnn/performance_sequence_generator.py", line 242, in _generate
    len(performance) + rnn_steps_to_gen, performance, **args)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/models/performance_rnn/performance_model.py", line 86, in generate_performance
    extend_control_events_callback=extend_control_events_callback)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/models/shared/events_rnn_model.py", line 361, in _generate_events
    steps_per_iteration=steps_per_iteration)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/common/beam_search.py", line 134, in beam_search
    beam_entries, generate_step_fn, branch_factor, first_iteration_num_steps)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/common/beam_search.py", line 67, in _generate_branches
    all_sequences, all_states, all_scores)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/models/shared/events_rnn_model.py", line 215, in _generate_step
    temperature)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/models/shared/events_rnn_model.py", line 129, in _generate_step_for_batch
    [graph_final_state, graph_softmax], feed_dict)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
InternalError: Blas GEMM launch failed : a.shape=(1, 920), b.shape=(920, 2048), m=1, n=2048, k=920
	 [[Node: rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/concat, rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
	 [[Node: rnn/while/Exit_5/_53 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_289_rnn/while/Exit_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

Caused by op u'rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/MatMul', defined at:
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/interfaces/midi/magenta_midi.py", line 391, in <module>
    console_entry_point()
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/interfaces/midi/magenta_midi.py", line 387, in console_entry_point
    tf.app.run(main)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/platform/app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/interfaces/midi/magenta_midi.py", line 317, in main
    generators.append(_load_generator_from_bundle_file(bundle_file))
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/interfaces/midi/magenta_midi.py", line 284, in _load_generator_from_bundle_file
    generator.initialize()
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/music/sequence_generator.py", line 157, in initialize
    checkpoint_filename, metagraph_filename)
  File "/home/cv/magenta-dev/magenta/bazel-bin/magenta/interfaces/midi/magenta_midi.runfiles/__main__/magenta/music/model.py", line 75, in initialize_with_checkpoint_and_metagraph
    new_saver = tf.train.import_meta_graph(metagraph_filename)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/training/saver.py", line 1686, in import_meta_graph
    **kwargs)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/meta_graph.py", line 504, in import_scoped_meta_graph
    producer_op_list=producer_op_list)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/importer.py", line 311, in import_graph_def
    op_def=op_def)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/home/cv/anaconda3/envs/magenta/lib/python2.7/site-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

InternalError (see above for traceback): Blas GEMM launch failed : a.shape=(1, 920), b.shape=(920, 2048), m=1, n=2048, k=920
	 [[Node: rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/MatMul = MatMul[T=DT_FLOAT, transpose_a=false, transpose_b=false, _device="/job:localhost/replica:0/task:0/gpu:0"](rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/concat, rnn/while/rnn/multi_rnn_cell/cell_0/cell_0/basic_lstm_cell/basic_lstm_cell/MatMul/Enter)]]
	 [[Node: rnn/while/Exit_5/_53 = _Recv[client_terminated=false, recv_device="/job:localhost/replica:0/task:0/cpu:0", send_device="/job:localhost/replica:0/task:0/gpu:0", send_device_incarnation=1, tensor_name="edge_289_rnn/while/Exit_5", tensor_type=DT_FLOAT, _device="/job:localhost/replica:0/task:0/cpu:0"]()]]

**Comment by cghawthorne** [comment]
This is probably because multiple TensorFlow instances can't use the same GPU at the same time. You could try disabling GPU usage on the second instance by setting the `CUDA_VISIBLE_DEVICES` environment variable before starting it.

```
CUDA_VISIBLE_DEVICES=-1
```

**Comment by CircuV** [comment]
Thx a lot. Didn't know about those restriction when using GPU.
