### ISSUE TITLE
temp file access error with image_stylization_transform on Windows, Py 3.5

### ISSUE THREAD

**Issue by eps696** [tensorflow/magenta#913]
i get 'permission denied' error while trying to run image_stylization_transform script:
```Traceback (most recent call last):
  File "F:\_work\_neuro\magenta\models\image_stylization\image_stylization_transform.py", line 148, in <module>
    console_entry_point()
  File "F:\_work\_neuro\magenta\models\image_stylization\image_stylization_transform.py", line 144, in console_entry_point
    tf.app.run(main)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\tensorflow\python\platform\app.py", line 48, in run
    _sys.exit(main(_sys.argv[:1] + flags_passthrough))
  File "F:\_work\_neuro\magenta\models\image_stylization\image_stylization_transform.py", line 127, in main
    os.path.expanduser(FLAGS.input_image)), 0)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\magenta\models\image_stylization\image_utils.py", line 250, in load_np_image
    image = scipy.misc.imread(f.name)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\numpy\lib\utils.py", line 101, in newfunc
    return func(*args, **kwds)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\scipy\misc\pilutil.py", line 164, in imread
    im = Image.open(name)
  File "C:\Users\eps\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\Image.py", line 2530, in open
    fp = builtins.open(filename, "rb")
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\eps\\AppData\\Local\\Temp\\tmp08jxzere'
```

exactly same error on other occasions was logged (and solved) on issues #858 and #893, but still appears with style transfer script (i guess the code to check is around line 248 in models\image_stylization\image_utils.py - but it's only guess)

magenta-gpu 0.3.1, tensorflow-gpu 1.3.0, py 3.5.2, windows 8.1 or 10

**Comment by eps696** [comment]
pardon for half-baked request; 
issue is fixed by removing ".name" on line 250 of image_utils.py:
    image = scipy.misc.imread(f)

**Comment by zhangyingji** [comment]
I hava the same error,but I couldn't solve the problem after doing as you said

**Comment by soraryu** [comment]
Got the same error, which can be fixed by changing the above.
Would be great if a default installation "just worked".
