### ISSUE TITLE
Just Starting, but errors

### ISSUE THREAD

**Issue by nickolasnikolic** [tensorflow/magenta#920]
Trying to get magenta up and running on a macbook pro. Any help would be appreciated.

(magenta) Nickolass-MacBook-Pro:magenta nickolasnikolic$ image_stylization_transform --num_styles=32 --checkpoint='../multistyle-pastiche-generator-varied.ckpt' --input_image='../nicpic.jpg' --which_styles="[0,1,2,3,4,5,6,7,8,9,10]" --output_dir="../" --output_basename="yo-"

Traceback (most recent call last):
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/bin/image_stylization_transform", line 7, in <module>
    from magenta.models.image_stylization.image_stylization_transform import console_entry_point
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/__init__.py", line 26, in <module>
    import magenta.common.concurrency
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/common/__init__.py", line 19, in <module>
    from . import state_util
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/magenta/common/state_util.py", line 20, in <module>
    from tensorflow.python.util import nest as tf_nest
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/__init__.py", line 24, in <module>
    from tensorflow.python import *
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/__init__.py", line 51, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 52, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow.py", line 41, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/pywrap_tensorflow_internal.py", line 24, in swig_import_helper
    _mod = imp.load_module('_pywrap_tensorflow_internal', fp, pathname, description)
ImportError: dlopen(/Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so, 10): Library not loaded: @rpath/libcublas.8.0.dylib
  Referenced from: /Users/nickolasnikolic/miniconda2/envs/magenta/lib/python2.7/site-packages/tensorflow/python/_pywrap_tensorflow_internal.so
  Reason: image not found

Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/install_sources#common_installation_problems

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.

**Comment by cghawthorne** [comment]
That looks like a problem with your tensorflow installation. I'd suggest reinstalling TensorFlow and perhaps trying the non-GPU version of TensorFlow.
